### PR TITLE
fix: subpath imports in glob imports failing to find files

### LINKED ISSUE #8884: [Bug]: glob subpath imports fail to load any files
### Reproduction link or steps

test case in PR I am submitting

### What is expected?

to match the files at the subpath import

### What is actually happening?

Failing to resolve the subpath import

Image
SS from my local repo. Basically it should have resovled to `/home/kalvens/mono3/apps/src/hooks/*.ts`

### System Info

```Shell
System:
    OS: Linux 6.18 Alpine Linux
    CPU: (16) x64 Common KVM processor
    Memory: 21.88 GB / 62.81 GB
    Container: Yes
    Shell: 5.3.3 - /bin/bash
  Binaries:
    Node: 24.13.0 - /usr/bin/node
    npm: 11.11.0 - /usr/bin/npm
    pnpm: 10.29.3 - /home/kalvens/.local/share/pnpm/pnpm
    bun: 1.3.3 - /home/kalvens/.bun/bin/bun
  Browsers:
    Chromium: 146.0.7680.153
```

### Any additional comments?

from what I could gather from AI, https://github.com/vitejs/vite/blob/v8.0.0/packages/vite/src/node/plugins/resolve.ts#L491-L520 resolves the subpath to be relative to the importer so `../hooks/*.ts`? But then it gets passed to rolldown based plugin and it thinks its relative to the root of the project?

### PR DESCRIPTION
**Pull request by kalvenschraut**
fixes #8884
generated with AI, I understand the code itself but hard to know if it is the right fix. Another fix was to fix vite's side but AI thought should have fixed rolldown and I figured at least start here then. Can see issue additional comments for some of the explanation I could gather

### CODE REVIEW

**Comment by kalvenschraut** [comment]
image
not sure where to enable the edit. Docs don't show where I am looking. Maybe because the branch is under my org and not my own user?
https://github.com/orgs/community/discussions/5634 okay seems to be restriction due to cross org PR

File: crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs [hunk 1]
```diff
@@ -268,7 +268,17 @@ impl Plugin for ViteResolvePlugin {
         .get(&rolldown_plugin_utils::constants::ViteImportGlob)
         .is_some_and(|v| v.is_sub_imports_pattern())
       {
-        let joined = Path::new(&self.resolve_options.root).join(id.as_ref());
+        let joined = if Path::new(id.as_ref()).is_absolute() {
```
Comment (kalvenschraut) [inline crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs]: I guess my specific test case is more the else if block, not sure if it is desired to also suppose absolute paths for whatever reason?

Comment (kalvenschraut) [reply crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs]: just going remove this path

**Comment by shulaoda** [comment]
@kalvenschraut Could you give me access to https://github.com/RTVision/rolldown, so I can make some changes?

**Comment by shulaoda** [comment]
I did some refactoring and moved the tests to the Vite side. See https://github.com/vitejs/vite/pull/22059.

**Review by shulaoda — APPROVED** [review]

**Comment by shulaoda** [comment]
Thank you for your contribution! ❤
