### PR TITLE
fix(hmr): rewrite `this` to `exports` for cjs modules

### LINKED ISSUE #5616: [Bug]: `this` in CJS module should be `module.exports` but is `undefined` in HMR patch file
See #5615

### PR DESCRIPTION
**Pull request by hyf0**
- Fixes https://github.com/rolldown/rolldown/issues/5616
- Closes https://github.com/rolldown/rolldown/pull/5615

### CODE REVIEW

**Comment by hyf0** [comment]
* **#5647** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5647?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5646** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5641** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5641?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by IWANABETHATGUY — APPROVED** [review]

File: crates/rolldown/src/hmr/impl_traverse_for_hmr_ast_finalizer.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  fn exit_expression(
+    &mut self,
+    node: &mut oxc::ast::ast::Expression<'ast>,
+    ctx: &mut oxc_traverse::TraverseCtx<'ast, ()>,
+  ) {
+    if ctx.is_current_scope_valid_for_tla() && matches!(node, ast::Expression::ThisExpression(_)) {
+      // Rewrite this to `undefined` or `exports`
+      if self.module.exports_kind.is_commonjs() {
+        // Rewrite this to `exports`
+        *node = quote_expr(self.alloc, "exports");
```
Comment (sapphi-red) [inline crates/rolldown/src/hmr/impl_traverse_for_hmr_ast_finalizer.rs:17]: Would this work for cases like below? (not a blocker for this PR as it's an edge case though)
```js
const exports = {}
this.foo = 'foo'
```

**Review by sapphi-red — APPROVED** [review]

File: crates/rolldown/src/hmr/impl_traverse_for_hmr_ast_finalizer.rs (hunk 1 above)
Comment (hyf0) [reply crates/rolldown/src/hmr/impl_traverse_for_hmr_ast_finalizer.rs:17]: What's the expectation here?

I probably thinking about following webpack and rename `exports` to `__rolldown_exports__`. And it will solve this case like

```js
function (__rolldown_exports__, __rolldown_module__) {
const exports = {}
__rolldown_exports__.foo = 'foo'
}
```

Declaring `__rolldown_exports__` manually is UB and rolldown won't handle such case.

Comment (sapphi-red) [reply crates/rolldown/src/hmr/impl_traverse_for_hmr_ast_finalizer.rs:17]: Actually the code I wrote didn't work with `SyntaxError: Identifier 'exports' has already been declared`. A valid example would be:
```js
{
  const exports = {}
  this.foo = 'foo'
}
```

The expectation is to work the same with Node. Your suggestion looks good to me.
