### PR TITLE
fix: generate init calls for excluded re-exports in strict execution order

### LINKED ISSUE #8777: [Bug]: strictExecutionOrder + sideEffects: false drops init calls for named re-exports, leaving variables undefined
### Reproduction link or steps

https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-aeizewzc?file=dist%2Findex.mjs

### What is expected?

Foo and Bar should be defined objects. The `init_Foo` wrapper (for Foo/index.js) should call `init_Foo$1()` (for Foo.js) so that the Foo variable gets assigned:                                       
                                                                                                                                                                                                     
```js
  var init_Foo = __esmMin((() => {                                                                                                                                                                   
      init_Foo$1();        // ← initialize Foo.js (assigns the Foo variable)                                                                                                                         
      init_fooClasses();                                                                                                                                                                             
      init_fooClasses();                                                                                                                                                                             
  })); 
```

### What is actually happening?

Foo and Bar are undefined. The Foo.js module wrapper becomes anonymous and is never called. The Foo/index.js wrapper only initializes fooClasses, skipping Foo.js:

```js
  // Foo.js — anonymous wrapper, never called! Foo stays undefined.
  var Foo;
  __esmMin((() => {
      init_fooClasses();
      Foo = { name: "Foo", root: fooClasses.root };
  }));
```

```js
  // Foo/index.js — missing init_Foo$1() call
  var init_Foo = __esmMin((() => {
      init_fooClasses();   // ← only classes — no Foo.js init!
      init_fooClasses();
  }));
```

### System Info

```Shell
rolldown v1.0.0-rc.9
Node.js v22.21.1
Linux x86_64
```

### Any additional comments?

A lot of iterating found that we needed the following to be true to hit this:

1. strictExecutionOrder: true
2. "sideEffects": false in a parent package.json
3. Nested barrel re-export pattern (barrel → sub-barrel → component)

This is true seemingly in our usage of the mui material-ui package which is how we first encountered it.

A very very rough and novice look suggests that this is because in https://github.com/rolldown/rolldown/blob/e17f131a39d4fa8891cefa8f5a61ff0ee690505b/crates/rolldown/src/stages/link_stage/reference_needed_symbols.rs#L187-L194

For a named re-export like `export { default } from './Foo.js'`:

- is_reexport_all is false (it's not export *)
- importee.side_effects is UserDefined(false) (from package.json)

So stmt_info.side_effect is set to false

https://github.com/rolldown/rolldown/blob/e17f131a39d4fa8891cefa8f5a61ff0ee690505b/crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs#L647-L665

The `export { default } from './Foo.js' `re-export in Foo/index.js is excluded from stmt_info_included. When `module_finalizers/mod.rs:remove_unused_top_level_stmt()` later processes Foo/index.js, it never sees this re-export statement, never calls `transform_or_remove_import_export_stmt` for it, and never
  generates the `init_Foo$1() `call that would initialise the Foo variable.

Then, UserDefined(false) from package.json short-circuits
https://github.com/rolldown/rolldown/blob/e17f131a39d4fa8891cefa8f5a61ff0ee690505b/crates/rolldown/src/stages/link_stage/tree_shaking/determine_side_effects.rs#L54-L56
while normally `determine_side_effects` would detect the wrapped ESM importee via the `export * from / WrapKind::Esm` check and return `Analyzed(true)`.

The semantics here seem kinda deliberate so I wanted to discuss but I can raise a change that marks re-export statements as always having side_effect: true when strictExecutionOrder is enabled, importee has WrapKind:Esm? But I'm open to any solutions.

Apologies again if this overview is totally in the wrong direction, first forays into rolldown and the bundler internals so feel free to course correct

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closes #8777

## Summary
- In strict execution order mode, tree-shaken re-export statements (`export { x } from` / `export * from`) in ESM-wrapped modules were missing `init_*()` calls, causing runtime failures with barrel-file patterns (e.g. MUI-style re-exports)
- Fixes this in the module finalizer by generating init calls for excluded re-export statements, traversing transitively through non-included barrel modules to find the included importees
- Adds two regression tests: `issue_8777` (MUI-style barrel re-exports) and `exports_chain_shared_barrel_fixpoint` (multi-level barrel chain)

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#8858** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8858?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8858?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8858).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 1]
```diff
@@ -1268,11 +1315,31 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
       .enumerate()
       .zip(self.ctx.module.stmt_infos.iter_enumerated().skip(1))
       .for_each(|((_top_stmt_idx, mut top_stmt), (stmt_info_idx, _stmt_info))| {
-        if !self.ctx.linking_info.stmt_info_included.has_bit(stmt_info_idx) {
+        let is_stmt_included = self.ctx.linking_info.stmt_info_included.has_bit(stmt_info_idx);
+
+        if !is_stmt_included {
+          // In strict execution order with ESM wrapping, excluded re-export
+          // statements still need init calls for correct initialization order.
+          if self.ctx.options.is_strict_execution_order_enabled()
```
Comment (hyf0) [inline crates/rolldown/src/module_finalizers/mod.rs]: I think without `is_strict_execution_order_enabled`? This situation could happen too?

```js
// main.js

...


require('./main.js') // This could trigger wrapping on all modules too
```

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/src/module_finalizers/mod.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/mod.rs]: fixed

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Mar 31, 12:16 PM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Mar 31, 12:19 PM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Mar 31, 12:24 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
