### PR TITLE
fix(resolver): ensure we always pass an absolute path to oxc_resolver

### LINKED ISSUE #1441: modules fail to resolve when importing a node_modules via an alias
the title isn't a great description.

I have an `index.ts`:

```ts
import '@/foo'
```
then `foo.ts`
```ts
import { z } from 'zod'
```

and a `rollup.config.mjs`

```js
import { defineConfig } from 'rolldown';

export default defineConfig({
    input: './src/index.ts',
    platform: 'node',
    resolve: {
        tsconfigFilename: 'tsconfig.json',
    },
    output: {
        format: 'esm',
    },
});
```

you will recieve the following output when building:
```
[UNRESOLVED_IMPORT] Warning: "zod" is imported by "src/config.ts", but could not be resolved – treating it as an external dependency.
```

however if you change the config to:
```
import nodePath from 'node:path';
import nodeUrl from 'node:url';

import { defineConfig } from 'rolldown';

export default defineConfig({
    logLevel: 'debug',
    input: './src/index.ts',
    platform: 'node',
    resolve: {
        tsconfigFilename: nodePath.join(nodePath.dirname(nodeUrl.fileURLToPath(import.meta.url)), 'tsconfig.json'),
    },
});
```

it will build successfully. 

this is because the `config_file` property that is passed to `TsconfigOptions`:

https://github.com/rolldown/rolldown/blob/26ca3da3d0968a39b18cb217454213ae3c8e82a9/crates/rolldown_resolver/src/resolver.rs#L69-L72

will be relative rather than absolute.

the other strange thing is that the tsconfig file is successfully found and read, there is no `TsconfigNotFound` error

### PR DESCRIPTION
**Pull request by camc314**
### Description

closes #1441

not sure how to write a test for this so any advice would be much appreciated

### CODE REVIEW

**Comment by Boshen** [comment]
Thank you @camc314 for testing and helping out! 

To maintainers of Rolldown: @camc314 is a long contributor of oxc, contributed almost half of the linter rules. Guide him and he'll give you lots of code 😁

**Review by IWANABETHATGUY — APPROVED** [review]
Thanks

File: crates/rolldown_resolver/src/resolver.rs [hunk 1]
```diff
@@ -66,9 +66,12 @@ impl<F: FileSystem + Default> Resolver<F> {
     };
 
     let resolve_options_with_default_conditions = OxcResolverOptions {
-      tsconfig: raw_resolve.tsconfig_filename.map(|p| TsconfigOptions {
-        config_file: p.into(),
-        references: oxc_resolver::TsconfigReferences::Disabled,
+      tsconfig: raw_resolve.tsconfig_filename.map(|p| {
+        let path = PathBuf::from(&p);
+        TsconfigOptions {
+          config_file: if path.is_relative() { cwd.join(path) } else { path },
```
Comment (hyf0) [inline crates/rolldown_resolver/src/resolver.rs:72]: Probably should check if the path exist and give a warning about if the file is not existed in rolldown's side.

**Review by hyf0 — APPROVED** [review]
Thanks

File: crates/rolldown_resolver/src/resolver.rs (hunk 1 above)
Comment (Boshen) [reply crates/rolldown_resolver/src/resolver.rs:72]: Maybe a bug on my end

```rust
#[derive(Debug, Clone)]
pub struct TsconfigOptions {
    /// Allows you to specify where to find the TypeScript configuration file.
    /// You may provide
    /// * a relative path to the configuration file. It will be resolved relative to cwd.
    /// * an absolute path to the configuration file.
    pub config_file: PathBuf,

    /// Support for Typescript Project References.
    pub references: TsconfigReferences,
}
```

Comment (hyf0) [reply crates/rolldown_resolver/src/resolver.rs:72]: I think the behavior of joining path to absolute in rolldown is correctly, due to we support passing cwd as an argument, we need to use the user-passed cwd.

Comment (camc314) [reply crates/rolldown_resolver/src/resolver.rs:72]: so if you pass a relative path to the tsconfig, oxc_resolver will find (and be able to read - although maybe it's read via the filesystem trait.), and parse it.

but when it starts looking in parent directories, it's resolved `ResolvedPath` is still relative, and not absolute. this is the bit that causes issues.
