### PR TITLE
fix: generate correct CSS filename in `preserveModules` mode

### LINKED ISSUE #4934: [Bug]: Invalid path handling with CSS, when preserveModules is true on Windows
### Reproduction link or steps

https://github.com/stevebeauge/tsdown-css-windows-repro

`pnpm build` => KO (wrong CSS outpath)

### What is expected?

When using `output/preserveModule` parameter, and CSS files, the emitted CSS files should be inside `dist `folder.

* `src/MyComponent.module.css` should output `dist\MyComponent.module-BlAtsAg0.css` (or whatever hash)

### What is actually happening?

Using Windows, the output path is `src\MyComponent.module-BlAtsAg0.css` (inside the src folder).

Full console output:

```
pnpm build                                                                                       ─╯

> @repro/sharedui@1.0.0 build D:\code\repro\tsdown-css-windows-repro
> rolldown -c

<DIR>/D:\code\repro\tsdown-css-windows-repro\src\MyComponent.module-Cbibx9P8.css               asset │ size:  0.09 kB
<DIR>/src/index.js                                                                             chunk │ size:  0.07 kB
<DIR>/src/MyComponent.module.js                                                                chunk │ size:  0.14 kB
<DIR>/node_modules/.pnpm/react@19.1.0/node_modules/react/index.js                              chunk │ size:  0.47 kB
<DIR>/src/MyComponent.js                                                                       chunk │ size:  0.53 kB
<DIR>/node_modules/.pnpm/react@19.1.0/node_modules/react/jsx-runtime.js                        chunk │ size:  0.54 kB
<DIR>/_virtual/rolldown_runtime.js                                                             chunk │ size:  1.16 kB
<DIR>/node_modules/.pnpm/react@19.1.0/node_modules/react/cjs/react-jsx-runtime.development.js  chunk │ size: 10.28 kB
<DIR>/node_modules/.pnpm/react@19.1.0/node_modules/react/cjs/react.development.js              chunk │ size: 36.11 kB

✔ Finished in 20.44 ms
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 6.74 GB / 31.46 GB
  Binaries:
    Node: 22.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.12.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (136.0.3240.50)
  npmPackages:
    rolldown: 1.0.0-beta.15 => 1.0.0-beta.15
```

### Any additional comments?

Seems there's something missing in path normalization

Originally posted as tsdown issue https://github.com/rolldown/tsdown/issues/319

### PR DESCRIPTION
**Pull request by shulaoda**
closes #4934

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#5175** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5175?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5175?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_common/src/chunk/mod.rs [hunk 1]
```diff
@@ -255,8 +255,13 @@ impl Chunk {
         hash
       }
     });
+    let chunk_name = if options.preserve_modules {
+      self.get_preserve_modules_chunk_name(options, chunk_name.as_str())
+    } else {
+      Cow::Borrowed(chunk_name.as_str())
+    };
```
Comment (IWANABETHATGUY) [inline crates/rolldown_common/src/chunk/mod.rs]: https://github.com/rolldown/rolldown/blob/d36407c1f591805fc98d55a35a70a0662241c151/crates/rolldown_common/src/chunk/mod.rs?plain=1#L188-L192, this may be extracted as a function?

**Comment by IWANABETHATGUY** [comment]
Also, can you add a test case? Since it seems like a general issue related to css + preseveModules

**Review by IWANABETHATGUY — APPROVED** [review]
