### PR TITLE
fix(hmr): should detect hmr boundary correctly

### LINKED ISSUE #5150: [Bug]: HMR boundary not work correctly
in this situation, `common`'s updates shall be captured and accepted, and no forceReload is needed.

```mermaid
graph LR

entry --> messenger
messenger --> foo
messenger --> bar
messenger --> common
foo --> common
bar --> common

messenger["🔥messenger"]
common["✏️common"]
```

### Reproduction link or steps

(`vite` can handle this correctly)

### POC

```js
import { rolldown } from "rolldown";
import fs, { realpath } from 'node:fs/promises';
import { chdir } from "node:process";

async function main() {
  const baseDir = './temp-1/';

  await fs.rm(baseDir, { recursive: true, force: true });
  await fs.mkdir(baseDir, { recursive: true });
  chdir(baseDir);

  await fs.writeFile('index.js', `
    import { sayMessage } from './messenger.js';
    setInterval(sayMessage, 1000);
    `);

  await fs.writeFile('messenger.js', `
    import { foo } from './foo.js';
    import { bar } from './bar.js';
    import { prefix } from './common.js';
    import { prefix as p2 } from './common.js';
    import { prefix as p3 } from './common.js';

    export let msg = [
      prefix,
      foo,
      bar,
      p2,
      p3,
    ].join(",")
    export function sayMessage() {
      console.log(msg);
    }

    if (import.meta.hot) {
      import.meta.hot.accept((mod) => {
        console.log('replaced with new msg: ', mod.msg);
        msg = mod.msg;
      });
    }
    `)

  await fs.writeFile('foo.js', `
    import { prefix } from './common.js';
    export const foo = prefix + 'foo';
    `)

  await fs.writeFile('bar.js', `
    import { prefix } from './common.js';
    export const bar = prefix + 'bar';
    `)

  await fs.writeFile('common.js', `
    export const prefix = 'prefix:';
    `)

  const r = await rolldown({
    input: 'index.js',
    experimental: {
      hmr: true,
    },
  });
  const out = await r.generate({})
  fs.writeFile('_output.js', out.output[0].code);


  // ----------------------------------------------
  // hmr test

  await fs.writeFile('common.js', `
    export const prefix = 'prefix-new:';
    `)

  const hmrPatch = await r.generateHmrPatch([await realpath('common.js')]);
  console.log('hmrPatch', hmrPatch);

  await fs.writeFile('_hmr-patch.js', hmrPatch.code);
}

main().catch(err => { console.error(err); process.exit(1); })
```

### What is expected?

generating a HMR patch. all changes are accepted by `messenger.js`

### What is actually happening?

in console, a fullReload is required by rolldown:

```js
hmrPatch {
  code: '',
  filename: '',
  hmrBoundaries: [],
  fullReload: true,
  isSelfAccepting: false
}
```

### System Info

```Shell
System:
    OS: macOS 15.5
    CPU: (14) arm64 Apple M4 Pro
    Memory: 192.86 MB / 48.00 GB
    Shell: 5.2.37 - /opt/homebrew/bin/bash
  Binaries:
    Node: 20.19.2 - ~/.nvm/versions/node/v20.19.2/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.19.2/bin/npm
    pnpm: 10.12.4 - ~/.nvm/versions/node/v20.19.2/bin/pnpm
  npmPackages:
    rolldown: 1.0.0-beta.21 => 1.0.0-beta.21
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by hyf0**
Fixes https://github.com/rolldown/rolldown/issues/5150.

### CODE REVIEW

**Comment by hyf0** [comment]
* **#5406** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5406?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5405** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5405?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5402** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5402?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5401** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5401?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5400** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5400?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5400?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_loader/module_loader.rs [hunk 1]
```diff
@@ -641,6 +641,9 @@ impl<'a> ModuleLoader<'a> {
           // Note: (Compat to rollup)
           // The `dynamic_importers/importers` should be added after `module_parsed` hook.
           let importers = &self.intermediate_normal_modules.importers[idx];
+          module.importers.clear();
```
Comment (hyf0) [inline crates/rolldown/src/module_loader/module_loader.rs]: @IWANABETHATGUY A heads-up here. If I didn't do this, the order of `imports` would be sometimes different against the initial build.

Comment (hyf0) [reply crates/rolldown/src/module_loader/module_loader.rs]: Doesn't work, so I used https://github.com/rolldown/rolldown/blob/7435ecd0cd71024d5b5ce75be67a6b1c61246f28/crates/rolldown/src/hmr/hmr_manager.rs#L462-L464.

File: crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+		var import_common_0 = __rolldown_runtime__.loadExports("common.js");
+		const foo = import_common_0.prefix + "foo";
+	} finally {}
+});
+
+//#endregion
+init_messenger_0()
+init_messenger_0()
+init_messenger_0()
+__rolldown_runtime__.applyUpdates(['messenger.js','messenger.js','messenger.js']);
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap:155]: I think this should be deduped.

File: crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+
+- full_reload: false
+- first_invalidated_by: None
+- is_self_accepting: false
+- full_reload_reason: None
+### Hmr Boundaries
+
+- boundary: messenger.js, accepted_via: bar.js
+- boundary: messenger.js, accepted_via: foo.js
+- boundary: messenger.js, accepted_via: common.js
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap:167]: I expect this to be:
```suggestion
- boundary: messenger.js, accepted_via: messenger.js
```
because `import.meta.hot.accept(() => { /* ... */ })` exists in `messager.js`.

```
- boundary: messenger.js, accepted_via: bar.js
- boundary: messenger.js, accepted_via: foo.js
- boundary: messenger.js, accepted_via: common.js
```
happens when `import.meta.hot.accept('./bar.js', () => { /* ... */ })` and `import.meta.hot.accept('./foo.js', () => { /* ... */ })` and `import.meta.hot.accept('./common.js', () => { /* ... */ })` exists in `messenger.js`.

File: crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap (hunk 2 above)
Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/hmr/issue_5150/artifacts.snap:155]: I'll fix this in the later PR.

**Review by sapphi-red — APPROVED** [review]
