### PR TITLE
fix: wasm build panic on stackblitz

### LINKED ISSUE #369: WASM build panic on stackblitz
### Describe the bug

Derived from #368, the WASM Build of rolldown-vite results in a panic when running it.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qifa3tcf

### Steps to reproduce

Start stackblitz, see error

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^5.0.0 => 5.0.0 
    rolldown-vite:  7.1.1
```

### Used Package Manager

npm

### Logs

<details><summary>Details</summary>
<p>

(node:12) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/napi-3.2.2/src/tokio_runtime.rs:113:6:
Access tokio runtime failed in spawn
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error when starting dev server:
RuntimeError: unreachable executed
    at wrappedPlugin[key] (file:///home/projects/vitejs-vite-qifa3tcf/node_modules/rolldown/dist/shared/src-p50l1OMU.mjs:83:67)
    at resolveId (file:///home/projects/vitejs-vite-qifa3tcf/node_modules/vite/dist/node/chunks/dep-BBmQs1ZR.js:30561:56)

</p>
</details> 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by shulaoda**
closes https://github.com/vitejs/rolldown-vite/issues/369

### CODE REVIEW

File: crates/rolldown_binding/src/lib.rs [hunk 1]
```diff
@@ -52,14 +58,23 @@ pub fn init() {
...
 /// Shutdown the tokio runtime manually.
 ///
 /// This is required for the wasm target with `tokio_unstable` cfg.
 /// In the wasm runtime, the `park` threads will hang there until the tokio::Runtime is shutdown.
 pub fn shutdown_async_runtime() {
   #[cfg(all(target_family = "wasm", tokio_unstable))]
-  napi::bindgen_prelude::shutdown_async_runtime();
+  {
+    if ACTIVE_TASK_COUNT.load(Ordering::Relaxed) > 0 {
+      if ACTIVE_TASK_COUNT.fetch_sub(1, Ordering::Relaxed) == 1 {
```
Comment (shulaoda) [inline crates/rolldown_binding/src/lib.rs:73]: Make sure that the call to `shutdown_async_runtime` is always executed on the same thread.

**Review by IWANABETHATGUY — APPROVED** [review]

File: crates/rolldown_binding/src/lib.rs (hunk 1 above)
Comment (shulaoda) [reply crates/rolldown_binding/src/lib.rs:73]: Let @Brooooooklyn to confirm

Comment (shulaoda) [reply crates/rolldown_binding/src/lib.rs:73]: Here I want to confirm whether, in a regular `#[napi]` function, the `dispose` function inside an `AsyncBlock` is executed on the same thread as the function itself.

Comment (Brooooooklyn) [reply crates/rolldown_binding/src/lib.rs:73]: > Here I want to confirm whether, in a regular #[napi] function, the dispose function inside an AsyncBlock is executed on the same thread as the function itself.

Yes, this is the purpose of using `AsyncBlock`: to always run dispose on the JavaScript thread.

**Review by Brooooooklyn — APPROVED** [review]
