### PR TITLE
fix: use correct index when inserting keepNames statements during export default transformation

### LINKED ISSUE #7852: Incorrect emit order: __name runtime helper called before variable is defined
@IWANABETHATGUY  : reproduced

this code
```js
const baseFontSize = 16;
export default px => parseFloat(px) / baseFontSize;
```

becomes:

```js
var baseFontSize = 16;
__name(lib_default, "default");
var lib_default = (px) => parseFloat(px) / baseFontSize;
```

https://repl.rolldown.rs/#eNptUL1uwyAQfpUTixMpcpSlA1Y6dmyldmUh8bmixQeCc0pr+d0LtaMkSgUDH3f3/dwoOiFHYajFVHMsbxLygjfiWGDvXWDwCbrgeqjqrTWH+iNWjaJyfFrt1k1uRiE5DDhtRHDWtu6L6qOjzrxfcf9TuVHhb48wwuvS9uLZOIowLdrn8QqKcuaIDDOTvJvZw6gIwA3sB5YzAPhE9M+6xyihmC2fk6J8FWH6s9Bipwd75hU5Tsl7ibCg2fZJBzjoiE+O+M38YFbdPTQq3LHl9e0fweuQe63TvPJpDdub2esdZtVT0dKMkcX0C+YAkbI=

also

```js
console.log('aaa');
export default px => {parseFloat(px) / 16};
```
```js
console.log("aaa");
__name(lib_default, "default");
var lib_default = (px) => {
	parseFloat(px) / 16;
};
```

instead

```js
export default px => {parseFloat(px) / 16};
```

```js
var lib_default = (px) => {
	parseFloat(px) / 16;
};
__name(lib_default, "default");
```

_Originally posted by @brokenmass in https://github.com/rolldown/rolldown/issues/7151#issuecomment-3738909386_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #7852

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7853** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7853?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7853?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7853).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 1]
```diff
@@ -1287,7 +1287,8 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
                 };
 
                 if let Some(binding) = binding {
-                  let insert_position = self.cur_stmt_index + 1;
+                  // current statement will be pushed to program.body, so the insert position is program.body.len() + 1
+                  let insert_position = program.body.len() + 1;
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/module_finalizers/mod.rs:1291]: `cur_stmt_index` is always 0 during `remove_unused_top_level_stmt`, since import statement will be removed, we can't use `_top_stmt_idx` either

File: crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+## main.js
+
+```js
+import assert from "node:assert";
+
+// HIDDEN [rolldown:runtime]
+//#region main.js
+const baseFontSize = 16;
+const pxToRem = (px) => parseFloat(px) / baseFontSize;
```
Comment (hyf0) [inline crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap]: where is the `__name` helper?

Comment (IWANABETHATGUY) [reply crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap]: Fixed, it is removed after I let cc add some assertion.

File: crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+# Assets
+
+## main.js
+
+```js
+// HIDDEN [rolldown:runtime]
+//#region main.js
+const baseFontSize = 16;
+var main_default = (px) => parseFloat(px) / baseFontSize;
+__name(main_default, "default");
```
Comment (hyf0) [inline crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap:13]: The fix LGTM. However, do we consider esbuild emits better output and want to align with it in the future?

https://hyrious.me/esbuild-repl/?version=0.27.2&b=e%00entry.js%00const+baseFontSize+%3D+16%3B%0A%0Aexport+default+px+%3D%3E+parseFloat%28px%29+%2F+baseFontSize%3B&o=--bundle+--keep-names

Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap:13]: If it is, probably create an issue to track it.

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap (hunk 3 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/tests/rolldown/topics/keep_names/issue_7852/artifacts.snap:13]: that's worth improving
