### PR TITLE
fix: deconflict for duplicate canonical names

### LINKED ISSUE #364: Bug: should generate conflict-less name for duplicated generated names
The current implementation assigned symbol name is append `${count}` if the symbol is conflicting. But the new name maybe also happen conflict. See blowing example.

Input 
``` .ts
// shared.js
const a = 'shared.js'

export { a }

// main.js
import { a as a2 } from './shared'
const a = 'index.js'
const a$1 = 'index.js'

console.log(a, a2, a$1)
```

Build Output 

```js
// shared.js
const a = 'shared.js'


// main.js

const a$1 = 'index.js'
const a$1 = 'index.js'

console.log(a$1, a, a$1)
```

We should assign a name with the current scope that is not a used name, like esbuild  `findNameUse` https://github.com/evanw/esbuild/blob/main/internal/renamer/renamer.go#L564. We need to collect the all symbols for scope at first, we only collect `unresolved` symbols at now.

### PR DESCRIPTION
**Pull request by hyf0**
### Description

Fixes #364

### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #365** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/365?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #367** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/367?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #369** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/369?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #370** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/370?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #371** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/371?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #372** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/372?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #374** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #375** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/375?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #377** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/377?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #378** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/378?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #379** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/379?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #380** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/380?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #381** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/381?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #382** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/382?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #383** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/383?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #388** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/388?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/365?utm_source=stack-comment).

File: crates/rolldown/src/bundler/utils/renamer.rs [hunk 1]
```diff
@@ -41,11 +41,15 @@ impl<'name> Renamer<'name> {
...
-        let canonical_name = if *count == 0 {
-          original_name
+        let mut canonical_name = if *count == 0 {
+          original_name.clone()
         } else {
           Cow::Owned(format!("{}${}", original_name, *count).into())
         };
+        while self.used_canonical_names.contains(&canonical_name) {
+          *count += 1;
+          canonical_name = Cow::Owned(format!("{}${}", original_name, *count).into());
```
Comment (underfin) [inline crates/rolldown/src/bundler/utils/renamer.rs:51]: The fix can be work, but it isn't efficient at some cases. If the scope has `a/a$1/a$2` symbols declared. The fix will caused `a/a$1/a$2` every symbol need rename. Please read the esbuild implementiontion, it will only rename once `a` -> `a$3`.

Comment (hyf0) [reply crates/rolldown/src/bundler/utils/renamer.rs:51]: From my point of view, it's efficient enough. Feel free to open a team meeting for this.

Comment (underfin) [reply crates/rolldown/src/bundler/utils/renamer.rs:51]: I remember we need to follow esbuild implementation, it will reduce our different ideas.

Comment (underfin) [reply crates/rolldown/src/bundler/utils/renamer.rs:51]: Here has lots of issue need to merge, I just approved it. I open a new issue to track this https://github.com/rolldown-rs/rolldown/issues/389.

**Review by underfin — APPROVED** [review]

**Comment by Boshen** [comment]
### Merge activity

* **Nov 26, 10:26 PM**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/365).
* **Nov 26, 10:26 PM**: @Boshen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/365).
