### PR TITLE
fix: update cur_stmt_index when processing top level statements

### LINKED ISSUE #7153: [Bug]: `__name` is injected before the default exported class
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNptj88KgzAMh18l9DRBZLt2DPYEO+7kpdQo3WorbeoE8d3X+ofJ8FDoLyHfl4ysZnxkylQ4FC+f/obxX86ZjLEXDqQNhuAG52vpSpMeDp11BBXWImgCqYX3ME5bOyZ0VHjR4lPogKeZkMMlmwkRjYyTCzjlrMJuZ1/T4v6z1MFIUtbAKVtdLM47q3VlP6aQ1tSq2bEOOofcMaEAbKAuEN8iwBuxe8QTPIe061Kevas82vuIaxTdW6Fi4QukGHQz)

### What is expected?

The output to have a code like:
```js
var index_default = class {};
__name(index_default, "default");
```

### What is actually happening?

The output has a code like:
```js
__name(index_default, "default");
var index_default = class {};
```

### System Info

```Shell
https://github.com/rolldown/rolldown/commit/6ca52aa9eb3f475cecfcb8c80ee9dd9425ca870c
```

### Any additional comments?

Caused by #7150
My bad, I didn't notice this one when reviewing

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #7153

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7157** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7157?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7157?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7157).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 1]
```diff
@@ -1140,6 +1140,7 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
         if !stmt_info.is_included {
           return;
         }
+        self.cur_stmt_index = program.body.len();
```
Comment (hyf0) [inline crates/rolldown/src/module_finalizers/mod.rs]: Could you add some comment about what does `cur_stmt_index` do?

I know it's for tracking the statement position while visiting.

But here, it seems that the visit is not happining.

Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/mod.rs]: It is used in https://github.com/rolldown/rolldown/blob/05f038e29c80a696721225727efd34a250b8ac67/crates/rolldown/src/module_finalizers/mod.rs?plain=1#L1337-L1344 and https://github.com/rolldown/rolldown/blob/05f038e29c80a696721225727efd34a250b8ac67/crates/rolldown/src/module_finalizers/mod.rs?plain=1#L1317-L1322

Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/mod.rs]: You are right, I should use `program.body.length` instead.

**Review by sapphi-red — APPROVED** [review]
