### PR TITLE
fix: filter should not stabilize args.specifier

### LINKED ISSUE #3970: [Bug]: hook filter (both rolldown and vite) not working same as `createFilter` util
### Reproduction link or steps

Related: https://github.com/rolldown/rolldown/issues/3964#issuecomment-2753552053

I'm not sure if this alignment is actually desired, but bringing it up just in case since current string filter implementation is causing a different behavior on wasi https://github.com/rolldown/rolldown/issues/3964.

Reproduction: 
https://stackblitz.com/edit/vitejs-vite-fwouqgsj?file=vite.config.ts (vite)
https://stackblitz.com/edit/vitejs-vite-nxw8ft8e?file=vite.config.ts (rolldown-vite) (needs to be tested locally to avoid wasi specific behavior)

Probably natural expectation is that two plugins below should work same, but it turns out `createFilter("virtual:foo")` doesn't match `"virtual:foo"`.

```js
import { defineConfig, createFilter, type Plugin } from "vite";

const virtualId = "virtual:foo";

const hookFilterPlugin: Plugin = {
  name: "test-hook-filter",
  resolveId: {
    filter: {
      id: "virtual:foo",
    },
    handler(id) {
      // matches when id === "virtual:foo"
    },
  },
}

const filter = createFilter("virtual:foo")

const createFilterPlugin: Plugin = {
  name: "test-createFilter",
  resolveId(id) {
    if (filter(id)) {
      // doesn't match when id === "virtual:foo" because
      // filter("virtual:foo")("virtual:foo") is false
    }
  },
}
```

```sh
# ok
npm run build

# error
test_createFilter=1 npm run build
```

### What is expected?

Not sure. Current behavior seems fine since `filter: { id: "virtual:foo" }` looks so intuitive. But, if current implementation is kept, wasi runtime specific behavior difference needs to be fixed somehow https://github.com/rolldown/rolldown/issues/3964

### What is actually happening?

rollup `createFilter` and vite/rolldown hook filter is not equivalent

### System Info

```Shell
rolldown-vite: https://pkg.pr.new/vitejs/rolldown-vite@bbddbf0
vite: https://pkg.pr.new/vite@35ee848
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed https://github.com/rolldown/rolldown/issues/3970

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#3972** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3972?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3972?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/watch/watcher_task.rs [hunk 1]
```diff
@@ -120,31 +119,28 @@ impl WatcherTask {
         continue;
       }
       let path = Path::new(file.as_str());
-      if path.exists() {
-        let normalized_path = path.relative(&options.cwd);
-        let normalized_id = normalized_path.to_string_lossy();
-        if pattern_filter::filter(
+      if path.exists()
+        && pattern_filter::filter(
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/watch/watcher_task.rs:123]: clippy suggests collapse them

File: packages/rolldown/tests/fixtures/builtin-plugin/ecma-transform/exclude/_config.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ export default defineTest({
     input: './main.ts',
     plugins: [
       transformPlugin({
-        exclude: ['node_modules/**'],
+        exclude: ['**/node_modules/**'],
```
Comment (IWANABETHATGUY) [inline packages/rolldown/tests/fixtures/builtin-plugin/ecma-transform/exclude/_config.ts:11]: rollup createFilter will return false for `node_modules/**` either
```js
import {createFilter} from '@rollup/pluginutils'


const test = createFilter('node_modules/**')
console.log(`test('/virtual/foo/node_modules/bar.js'): `, test('/foo/bar/node_modules/bar.js'))

```

test('/virtual/foo/node_modules/bar.js'):  false

**Review by hi-ogawa — COMMENTED** [review]
Porting `get_matcher_string` would break a following pattern, so I'm not sure if aligning with `createFilter` is necessary.

```js
{
  name: 'repro',
  resolveId: {
    filter: {
      id: 'virtual:foo'
    },
    handler(...args) {
      console.log("[resolveId]", args)
      return '\0virtual:foo'
    }
  },
  load: {
    filter: {
      id: '\0virtual:foo'
    },
    handler(...args) {
      console.log("[load]", args)
      return `console.log("ok")`;
    }
  },
}
```

I didn't know `createFilter` is aware of cwd and, from what I've seen, I think people normally don't rely on that and explicitly uses `**` for string pattern instead, so breaking that away from `createFilter` might be fine in practice. Any thoughts? @sapphi-red

**Comment by IWANABETHATGUY** [comment]
> b

Maybe we should also handle any string prefix with `virtual:` specially?

**Comment by IWANABETHATGUY** [comment]
In this case we recommended user to use regexp instead

**Comment by IWANABETHATGUY** [comment]
> Porting `get_matcher_string` would break a following pattern, so I'm not sure if aligning with `createFilter` is necessary.
> 
> ```js
> {
>   name: 'repro',
>   resolveId: {
>     filter: {
>       id: 'virtual:foo'
>     },
>     handler(...args) {
>       console.log("[resolveId]", args)
>       return '\0virtual:foo'
>     }
>   },
>   load: {
>     filter: {
>       id: '\0virtual:foo'
>     },
>     handler(...args) {
>       console.log("[load]", args)
>       return `console.log("ok")`;
>     }
>   },
> }
> ```
> 
> I didn't know `createFilter` is aware of cwd and, from what I've seen, I think people normally don't rely on that and explicitly uses `**` for string pattern instead, so breaking that away from `createFilter` might be fine in practice. Any thoughts? @sapphi-red

Another reason I prefer to align with rollup is user may have less mental burden when migrating from rollup to rolldown

File: crates/rolldown_utils/src/pattern_filter.rs [hunk 3]
```diff
@@ -232,30 +248,43 @@ mod tests {
...
         cases: vec![
-          ("foo.js", "foo.js", FilterResult::Match(false)), // exclude has higher priority
-          ("bar.js", "bar.js", FilterResult::Match(true)),
-          ("foo.ts", "foo.ts", FilterResult::Match(false)),
+          ("foo.js", FilterResult::Match(false)), // exclude has higher priority
+          ("bar.js", FilterResult::Match(true)),
+          ("foo.ts", FilterResult::Match(false)),
+        ],
+      },
+      // https://github.com/rolldown/rolldown/issues/3970
```
Comment (IWANABETHATGUY) [inline crates/rolldown_utils/src/pattern_filter.rs:269]: test added here.

**Comment by hi-ogawa** [comment]
> Maybe we should also handle any string prefix with `virtual:` specially?

 Virtual module naming is not restricted to `virtual:`, just like Vite internally uses `vite/modulepreload-polyfill`. 

> Another reason I prefer to align with rollup is user may have less mental burden when migrating from rollup to rolldown

I understand both ways. I'm also wondering which is less mental burden for users, either 1. exactly same as `createFilter` but not being able to use intuitive-looking `{ filter: { id: "virtual:xxx" } }` (and need to use exact regex like https://github.com/vitejs/rolldown-vite/pull/89 or less accurate `**/virtual:xxx` ) or, 2. not exactly same as `createFilter` but allows `filter: { id: "virtual:xxx" }`.

**Comment by sapphi-red** [comment]
It seems createFilter of pluginutils recommends setting `resolve: false` for matching virtual modules.
https://github.com/rollup/plugins/tree/d32bcf69168d3505def66f27c03d64ad33672601/packages/pluginutils#:~:text=This%20can%20be%20useful%20if%20you%20want%20to%20create%20a%20filter%20for%20virtual%20module%20names.

**Comment by sapphi-red** [comment]
I wonder if which is more common, matching a virtual module or filtering under `process.cwd`. Maybe matching a virtual module is more common? Vite has a concept of `root` which is different from `process.cwd` and probably won't work well together with it.

**Comment by sapphi-red** [comment]
Probably depends on how the filter is used. If the value is passed from the user, aligning with createFilter is useful I guess: https://github.com/search?q=path%3Arollup.config.js+%2Finclude%3A%2F&type=code&p=1

**Comment by sapphi-red** [comment]
My personal conclusion is: I prefer this PR, maybe good to add a `@rolldown/pluginutils` package (or add to `@rollup/pluginutils`) that exposes the following functions:
```js
export const extactRegExp = str => new RegExp(`^${RegExp.escape(str)}$`)
export const prefixRegExp = str => new RegExp(`^${RegExp.escape(str)}`)
export const suffixRegExp = str => new RegExp(`${RegExp.escape(str)}$`)
```

**Review by hi-ogawa — APPROVED** [review]
I'm good with this too as intended behavior is clear now :+1:

**Review by sapphi-red — APPROVED** [review]
