### PR TITLE
fix: path compression in symbol linking

### LINKED ISSUE #7384: [Bug]: variable is not defined with re-exports
### Reproduction link or steps

https://stackblitz.com/edit/vh8pztjx?file=rolldown.config.mts
- `pnpm build && node dist/index.js`

### What is expected?

No errors

### What is actually happening?

```
ReferenceError: t$1 is not defined
```

### System Info

```Shell
N/A
```

### Any additional comments?

Found this bug on React Router: https://github.com/remix-run/react-router/pull/14423

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #7384

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7392** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7392?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7392?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7392).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_common/src/types/symbol_ref_db.rs [hunk 1]
```diff
@@ -249,7 +249,10 @@ impl SymbolRefDb {
   pub fn find_mut(&mut self, target: SymbolRef) -> SymbolRef {
     let mut canonical = target;
     while let Some(parent) = self.get_mut(canonical).link {
-      self.get_mut(canonical).link = self.get_mut(parent).link;
```
Comment (hyf0) [inline crates/rolldown_common/src/types/symbol_ref_db.rs:252]: So the problem is that is `self.get_mut(parent).link` sometimes is `None` and overwrite ` self.get_mut(canonical).link` unexpectedly?

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown_common/src/types/symbol_ref_db.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown_common/src/types/symbol_ref_db.rs:252]: yes

Comment (IWANABETHATGUY) [reply crates/rolldown_common/src/types/symbol_ref_db.rs:252]: yes
