### PR TITLE
fix: `process` is not defined in repl

### LINKED ISSUE #6146: ReferenceError: process is not defined
Looks like a recent deployment broke the REPL. It always errors with this error message for me, regardless of the code. Tried clearing caches and a different browser as well.

```sh
Error: process is not defined

ReferenceError: process is not defined
    at https://repl.rolldown.rs/api/proxy/@1.0.0-beta.37/dist/experimental-index.browser.mjs:529:16
```

The error occurs here:

```ts
//#region src/cli/logger.ts
/**
* Console logger
*/
const logger = process.env.ROLLDOWN_TEST ? createTestingLogger() : createConsola({ formatOptions: { date: false } });
function createTestingLogger() {
	const types = [
		"silent",
		"fatal",
		"error",
		"warn",
		"log",
		"info",
		"success",
```

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #6146

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6147** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6147?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6147?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6147).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/build.ts [hunk 1]
```diff
@@ -46,6 +46,11 @@ if (isBrowserPkg) {
   configs.push(
     withShared({
       browserBuild: true,
+      // `experimental-index` now dependents on `logger` in cli to emit warning which require `process.env.ROLLDOWN_TEST` to initialize logger correctly.
```
Comment (IWANABETHATGUY) [inline packages/rolldown/build.ts]: usage https://github.com/rolldown/rolldown/blob/022aea64d17a3232513941d07980eb7e3bd302ec/packages/rolldown/src/builtin-plugin/replace-plugin.ts?plain=1#L43-L45

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
b4fd731

with this pkg.pr commit hash repl now worked, 
image
