### PR TITLE
fix: make sure the sort compare function satisfy `total order`

### LINKED ISSUE #2616: [Bug]: build panics on certain conditions
### Reproduction link or steps

1. Install `@arcgis/core` npm package:
```sh
$ npm i '@arcgis/core'
```
2. Create `index.js`:
```js
import Graphic from "@arcgis/core/Graphic";
```
3. Build it with rolldown:
```sh
$ rolldown 'index.js' --dir 'dist'
```

### What is expected?

The project should build.

### What is actually happening?

Rolldown panics.

```
thread 'tokio-runtime-worker' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: user-provided comparison function does not correctly implement a total order] {
  code: 'GenericFailure'
}

Node.js v23.1.0
```

### System Info

```
  Binaries:
    Node: 23.1.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
  npmPackages:
    rolldown: latest => 0.14.0 
```

### Any additional comments?

Reproducibility is not 100%. It's more like 50/50.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
according to the doc: 
> If the comparison function `compare` does not implement a [total order](https://en.wikipedia.org/wiki/Total_order) the resulting order
of elements in the slice is unspecified. All original elements will remain in the slice and
any possible modifications via interior mutability are observed in the input. Same is true
if `compare` panics.
1. Closed https://github.com/rolldown/rolldown/issues/2616
## Ref
https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#new-sort-implementations

### CODE REVIEW

File: crates/rolldown/src/stages/generate_stage/render_chunk_to_assets.rs [hunk 1]
```diff
@@ -166,15 +166,13 @@ impl<'a> GenerateStage<'a> {
...
 
     // The chunks order make sure the entry chunk at first, the assets at last, see https://github.com/rollup/rollup/blob/master/src/rollup/rollup.ts#L266
-    output.sort_unstable_by(|a, b| match (a, b) {
-      (Output::Chunk(a), Output::Chunk(b)) => {
-        if a.is_entry || b.is_entry {
-          std::cmp::Ordering::Greater
-        } else {
-          a.filename.cmp(&b.filename)
-        }
+    output.sort_unstable_by(|a, b| {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/generate_stage/render_chunk_to_assets.rs:169]: almost `1:1` copy from rollup impl

**Comment by IWANABETHATGUY** [comment]
The diff because we sort the filename whatever now.

**Review by underfin — APPROVED** [review]
