### PR TITLE
fix: improve variable renaming to avoid unnecessary shadowing in nested scopes

### LINKED ISSUE #6586: [Bug]: Unnecessary variable renaming
### Reproduction link or steps

https://repl.rolldown.rs/#eNptT00LwjAM/SuhFxXG8FyYf0Hw3MvYOimsaelSnZT+d7MvnOglJHkv7+Ul0QmZhMFWjyUNU49CfuZCNDzq0btA0DgcCDBaqOCs8GvLtTN3Bo6Mn6C6TDyFLKCFpBB1LkRwfd+6J5YLeef3B1mcjZ096OU1JLittKsnw66QoQvOwmE7PyhUuP9H/pxUkBQCGPSRJCzypdVUl/OqUJgnkTVbq7s69psax8kc48F/9TXpgUR+A8vPcLQ=

### What is expected?

```js
//#region index.ts
const num = 0;
const config = (num) => num;

//#endregion
export { config, num };
```

### What is actually happening?

```js
//#region index.ts
const num = 0;
const config = (num$1) => num$1;

//#endregion
export { config, num };
```

### System Info

```Shell
N/A
```

### Any additional comments?

Relate to dts plugin

Image

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #6586

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7859** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7859?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7859?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7859).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/renamer.rs [hunk 1]
```diff
@@ -195,16 +215,64 @@ impl<'name> Renamer<'name> {
...
+          //
+          // Excluded from this set:
+          // - Reserved names (keywords, globals) - these have no owner
+          let names_to_avoid: FxHashSet<CompactStr> = used_canonical_names
+            .iter()
+            .filter(|(_, info)| {
+              info.owner.is_some_and(|owner| owner != module.idx || info.was_renamed)
+            })
+            .map(|(name, _)| name.clone())
+            .collect();
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/renamer.rs]: Seems problematic

**Review by shulaoda — APPROVED** [review]
