### PR TITLE
fix: renamed exports when enabled preserveModules

### LINKED ISSUE #4698: [Bug]: Don't renamed exports when `preserveModules`
### Reproduction link or steps

https://bundler.sxzz.dev/#eNqtUEsKwjAQvcqQTUFq1W3AhQfwBt3UdiJKTEIy8UPJ3U0sSErqzs3AvMfM+4xMMD4yVGRf664hlzbFeI7UrE/A02hLsAJh9Q2qZpO4KpLIOFmPoWZWSznoh2p6rcTl3Fy/3xaY2dcBReclwdgqAO3JeOLTAmAsOrR3POrBS3QcklqduBBnaBWL0rn10nRUdQQH2MNuOzkWnXTJ8hTzVAT/ID+CJ24ePL8vL0v1rC9vltua4f/sKoQ3lQ6iNQ==

### What is expected?

`entry-a.js` and `entry-b.js` should be the same (which is Rollup's behavior)

### What is actually happening?

```js
import { A$1 as A } from "./a.js";

export { A };
```

### System Info

```Shell
N/A
```

### Any additional comments?

Downstream: https://github.com/rolldown/tsdown/issues/269

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
- Should deconflict the export symbol name at the single chunk level rather than the whole build level.
- Closed #4698

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4728** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4728?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4728?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs [hunk 1]
```diff
@@ -369,10 +369,9 @@ impl GenerateStage<'_> {
     // Generate cross-chunk exports. These must be computed before cross-chunk
     // imports because of export alias renaming, which must consider all export
     // aliases simultaneously to avoid collisions.
-    let mut name_count =
-      FxHashMap::with_capacity(index_chunk_exported_symbols.iter().map(FxHashSet::len).sum());
 
     for (chunk_id, chunk) in chunk_graph.chunk_table.iter_mut_enumerated() {
+      let mut name_count = FxHashMap::with_capacity(index_chunk_exported_symbols[chunk_id].len());
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs:374]: Should deconflict the export name at the single chunk level rather than the whole build level.

File: crates/rolldown/tests/rolldown/issues/3438/artifacts.snap [hunk 2]
```diff
@@ -75,5 +75,5 @@ const clear$1 = "repro3_clear$1";
 const clear = "repro3_clear";
 
 //#endregion
-export { clear$1 as clear$1$2, clear$2, clear as clear$3 };
+export { clear, clear$1, clear$2 };
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/issues/3438/artifacts.snap:78]: As you can see the new output is more intuitive since all export symbols in chunk `repro32.js` are not conflicted at all, they should keep it as is.

File: crates/rolldown/tests/rolldown/issues/3438/_test.mjs [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import assert from 'node:assert'
+import main from './dist/main.js'
+
+assert.equal(main[0], 'repro1_clear')
+assert.equal(main[1], 'repro2_clear')
+assert.equal(main[2], 'repro2_clear$1')
+assert.equal(main[3], 'repro3_clear')
+assert.equal(main[4], 'repro3_clear$1')
+assert.equal(main[5], 'repro3_clear$2')
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/issues/3438/_test.mjs:9]: Add more assertion to make sure runtime behavior is correct.

File: crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs (hunk 1 above)
Comment (hyf0) [reply crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs:374]: Such a long time mistake. Great catch!

**Review by hyf0 — APPROVED** [review]
