### PR TITLE
fix(strict_execution_order): wrapped module should be included on demand

### LINKED ISSUE #3981: Advanced chunking seems to revert any treeshaking
I've been testing various iterations of the upcoming Rolldown-based Vite at work. The main difference between the configs is transposing the manualChunk section to the advancedChunks one (assuming I did it right).

At work, I use the Tabler Icons for flashy iconography. Building my project with stock Vite with manualChunks, everything gets treeshaken properly. Trying the Rolldown-based one with the advancedChunks, it seems to always decides to pack _all_ icon code/SVG into the chunk, regardless of whether the icon is in-use or not (quasi undoing any treeshaking/minification).

I just tried to create a repro for an issue and noticed that advancedChunks is the cause of it.
(Repro here: https://stackblitz.com/edit/github-z1badibh-fgajb3rp?file=vite.config.js )

Build output without it:
```
vite v6.3.0-beta.3 building for production...
The built-in minifier is still under development. Setting "minify: true" is not recommended for production use.
transforming (1) index.jsxtarget was modified to include ES2021 because useDefineForClassFields is set to false and oxc does not support transforming useDefineForClassFields=false for ES2022+ yet
✓ 5901 modules transformed.
dist/index.html                                 0.40 kB │ gzip:  0.25 kB
dist/assets/IconSkull-CtyFQlbR.js               0.54 kB │ gzip:  0.30 kB
dist/assets/createReactComponent-BQD9wsXb.js    9.02 kB │ gzip:  3.43 kB
dist/assets/index-Deub4-rD.js                 176.06 kB │ gzip: 55.41 kB
✓ built in 3.50s
```

Build output with it. Note the 2.5MB huge chunk:
```
vite v6.3.0-beta.3 building for production...
The built-in minifier is still under development. Setting "minify: true" is not recommended for production use.
transforming (1) index.jsxtarget was modified to include ES2021 because useDefineForClassFields is set to false and oxc does not support transforming useDefineForClassFields=false for ES2022+ yet
✓ 5901 modules transformed.
dist/index.html                    0.30 kB │ gzip:   0.22 kB
dist/assets/index-DRv2rl1A.js    176.11 kB │ gzip:  55.47 kB
dist/assets/icons-DP5JVsVA.js  2,606.37 kB │ gzip: 493.89 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 4.75s
```

This is with this config:
```
advancedChunks: {
    groups: [{ name: 'icons', test: '@tabler/icons-react' }],
},
```

In comparison, stock Vite with manualChunks:
```
vite v6.2.3 building for production...
✓ 5910 modules transformed.
dist/index.html                  0.30 kB │ gzip:  0.22 kB
dist/assets/icons-DZ3J7wzX.js    9.60 kB │ gzip:  3.65 kB
dist/assets/index-CuvGa-97.js  177.50 kB │ gzip: 56.15 kB
✓ built in 2.84s
```

### PR DESCRIPTION
**Pull request by hyf0**
### Description

This PR fixes the size problem of enabling `strictExecutionOrder` at https://github.com/rolldown/rolldown/issues/3981.

---

Fixes https://github.com/rolldown/rolldown/issues/3981.

### CODE REVIEW

**Comment by hyf0** [comment]
* **#4687** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4687?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4687?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs [hunk 1]
```diff
@@ -218,6 +218,7 @@ impl LinkStage<'_> {
     });
     self.resolve_member_expr_refs(&side_effects_modules, &normal_symbol_exports_chain_map);
     self.update_cjs_module_meta();
+    self.normal_symbol_exports_chain_map = normal_symbol_exports_chain_map
```
[the remark this answers is not in the document]
Comment (hyf0) [reply crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs]: Fixed

File: packages/rolldown/package.json [hunk 2]
```diff
@@ -72,7 +72,7 @@
     "build-binding:wasi:release": "pnpm build-binding --profile release-wasi --target wasm32-wasip1-threads",
     "# Scrips for node #": "_",
     "build-node": "oxnode ./build.ts",
-    "build-types-check": "tsc -p ./tsconfig.check.json",
+    "build-types-check": "",
```
[the remark this answers is not in the document]
Comment (hyf0) [reply packages/rolldown/package.json]: Fixed

File: crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs [hunk 3]
```diff
@@ -465,7 +470,7 @@ impl LinkStage<'_> {
                 if cursor > 0 {
                   resolved_map.insert(
                     member_expr_ref.span,
-                    (Some(canonical_ref), member_expr_ref.props[cursor..].to_vec()),
```
Comment (hyf0) [inline crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs:468]: @IWANABETHATGUY I didn't turn off the feature. Let's give a try and see if it could survive

File: crates/rolldown/tests/esbuild/dce/package_json_side_effects_false_keep_bare_import_and_require_es6/bypass.md [hunk 4]
```diff
@@ -36,7 +36,6 @@ var init_demo_pkg = __esm({ "node_modules/demo-pkg/index.js"() {
 //#endregion
 //#region src/entry.js
 init_demo_pkg();
-init_demo_pkg();
```
Comment (hyf0) [inline crates/rolldown/tests/esbuild/dce/package_json_side_effects_false_keep_bare_import_and_require_es6/bypass.md:39]: Removing is expected. `Users/user/project/node_modules/demo-pkg/index.js` is marked with `sideEffect: fasle`. We have the same result as esbuild.

File: crates/rolldown/tests/esbuild/default/exports_and_module_format_common_js/artifacts.snap [hunk 5]
```diff
@@ -11,21 +10,21 @@ snapshot_kind: text
 const node_assert = __toESM(require("node:assert"));
 
 //#region foo/test.js
-var test_exports$1 = {};
-__export(test_exports$1, { foo: () => foo });
+var test_exports = {};
```
Comment (hyf0) [inline crates/rolldown/tests/esbuild/default/exports_and_module_format_common_js/artifacts.snap:13]: Since we marked some import statements as included, they participate in the deconflicting and make some symbols to be deconflicted early than they used to be.

File: packages/rollup-tests/src/ignored-tests.js [hunk 6]
```diff
@@ -19,7 +19,10 @@ const ignoreTests = [
 
   "rollup@hooks@assigns chunk IDs before creating outputBundle chunks", // The `renderChunk` is called at parallel, collect chunk info to array is unstable.  https://github.com/rolldown/rolldown/issues/2364
   "rollup@form@non-empty-block-statement: do not remove non an empty block statement@generates es", // https://github.com/rolldown/rolldown/pull/3541#issuecomment-2649731213
-  "rollup@function@es5-class-called-without-new" // rolldown align directive rendering with esbuild
+  "rollup@function@es5-class-called-without-new", // rolldown align directive rendering with esbuild
+
+  // hyf0: We can align the deconflict logic with rollup, but it requires unnecessary logic and doesn't have payoff.
+  "rollup@form@deconflict-module-priority: prioritizes entry modules over dependencies when deconflicting",
```
Comment (hyf0) [inline packages/rollup-tests/src/ignored-tests.js]: Since static import stmts are included now. `import { foo } from './foo.js'` in `entry.js` will cause symbol `foo` in `foo.js` participate in the deconflict early than others.

This test wants to ensure all entry's declared symbols get processed first. I feel unnecessary to put effort on this one.

**Review by IWANABETHATGUY — APPROVED** [review]
