### PR TITLE
fix: rename variable to better reflect its purpose and fix CJS imports

### LINKED ISSUE #6587: [Bug]: Error: Panic in async function
### Reproduction link or steps

https://github.com/better-auth/better-auth/pull/5370

### What is expected?

Should works

### What is actually happening?

```
/Users/himself65/.local/state/fnm_multishells/96656_1756417264388/bin/pnpm run build

> better-auth@1.4.0-beta.11 build /Users/himself65/Code/better-auth/packages/better-auth
> tsdown

ℹ tsdown v0.15.6 powered by rolldown v1.0.0-beta.43
ℹ Using tsdown config: /Users/himself65/Code/better-auth/packages/better-auth/tsdown.config.ts
ℹ entry: src/index.ts, src/adapters/index.ts, src/adapters/test.ts, src/api/index.ts, src/client/index.ts, src/cookies/index.ts, src/crypto/index.ts, src/db/index.ts, src/integrations/next-js.ts, src/integrations/node.ts, src/integrations/react-start.ts, src/integrations/solid-start.ts, src/integrations/svelte-kit.ts, src/oauth2/index.ts, src/social-providers/index.ts, src/plugins/index.ts, src/test-utils/index.ts, src/types/index.ts, src/adapters/drizzle-adapter/index.ts, src/adapters/kysely-adapter/index.ts, src/adapters/memory-adapter/index.ts, src/adapters/prisma-adapter/index.ts, src/adapters/mongodb-adapter/index.ts, src/client/lynx/index.ts, src/client/plugins/index.ts, src/client/react/index.ts, src/client/solid/index.ts, src/client/svelte/index.ts, src/client/vue/index.ts, src/plugins/admin/index.ts, src/plugins/access/index.ts, src/plugins/anonymous/index.ts, src/plugins/bearer/index.ts, src/plugins/custom-session/index.ts, src/plugins/captcha/index.ts, src/plugins/device-authorization/index.ts, src/plugins/email-otp/index.ts, src/plugins/generic-oauth/index.ts, src/plugins/haveibeenpwned/index.ts, src/plugins/jwt/index.ts, src/plugins/magic-link/index.ts, src/plugins/multi-session/index.ts, src/plugins/oauth-proxy/index.ts, src/plugins/oidc-provider/index.ts, src/plugins/one-tap/index.ts, src/plugins/one-time-token/index.ts, src/plugins/open-api/index.ts, src/plugins/organization/index.ts, src/plugins/passkey/index.ts, src/plugins/phone-number/index.ts, src/plugins/siwe/index.ts, src/plugins/two-factor/index.ts, src/plugins/username/index.ts, src/plugins/admin/access/index.ts, src/plugins/organization/access/index.ts
ℹ tsconfig: tsconfig.json
ℹ Build start

thread 'tokio-runtime-worker' panicked at crates/rolldown/src/types/generator.rs:79:52:
no entry found for key
stack backtrace:
   0:        0x11dc49f7c - _napi_register_module_v1
   1:        0x11d49bc2c - _blake3_compress_in_place_portable
   2:        0x11dc499fc - _napi_register_module_v1
   3:        0x11dc49e3c - _napi_register_module_v1
   4:        0x11dc49614 - _napi_register_module_v1
   5:        0x11dc6e60c - _napi_register_module_v1
   6:        0x11dc6e57c - _napi_register_module_v1
   7:        0x11dc6f3ec - _napi_register_module_v1
   8:        0x11dcd72e4 - _napi_register_module_v1
   9:        0x11dcd7750 - _napi_register_module_v1
  10:        0x11d9e0bbc - _napi_register_module_v1
  11:        0x11d9db190 - _napi_register_module_v1
  12:        0x11d9d9ae8 - _napi_register_module_v1
  13:        0x11d19fb50 - <unknown>
  14:        0x11d1acc78 - <unknown>
  15:        0x11d3b2600 - <unknown>
  16:        0x11d3b4808 - <unknown>
  17:        0x11d3a3820 - <unknown>
  18:        0x11d3beca0 - <unknown>
  19:        0x11d3b7460 - <unknown>
  20:        0x11d3bc718 - <unknown>
  21:        0x11d27f750 - <unknown>
  22:        0x11d2fa1e8 - <unknown>
  23:        0x11dc857e4 - _napi_register_module_v1
  24:        0x11dc83c24 - _napi_register_module_v1
  25:        0x11dc8b920 - _napi_register_module_v1
  26:        0x11dc7ba8c - _napi_register_module_v1
  27:        0x11dc88550 - _napi_register_module_v1
  28:        0x11dc6f798 - _napi_register_module_v1
  29:        0x19682cc08 - __pthread_cond_wait

 ERROR  Error: Panic in async function

 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
```

### System Info

```Shell
System:
    OS: macOS 26.0.1
    CPU: (16) arm64 Apple M4 Max
    Memory: 27.31 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.18.0 - ~/.local/state/fnm_multishells/31100_1760649957840/bin/node
    npm: 10.9.3 - ~/.local/state/fnm_multishells/31100_1760649957840/bin/npm
    pnpm: 10.18.1 - ~/.local/state/fnm_multishells/31100_1760649957840/bin/pnpm
    bun: 1.3.0 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 141.0.7390.107
    Safari: 26.0.1
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #6587

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6663** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6663?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6663?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6663).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/reference_needed_symbols.rs [hunk 1]
```diff
@@ -98,8 +98,7 @@ impl LinkStage<'_> {
                       if matches!(
                         self.options.format,
                         OutputFormat::Cjs | OutputFormat::Iife | OutputFormat::Umd
-                      ) && !rec.meta.contains(ImportRecordMeta::IsPlainImport)
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/link_stage/reference_needed_symbols.rs:101]: This optimization is used to eliminate unused runtime code, see crates/rolldown/tests/rolldown/function/format/cjs/plain_import_should_not_introduce_to_esm/artifacts.snap as an example, but since now we generate different external import code like: 
```js
let import_xxx = require('external');
import_xxx = __toESM(import_xxx);
```
This optimization is no longer valid, reverted it.

**Review by shulaoda — APPROVED** [review]
