### PR TITLE
fix(rolldown_plugin_vite_resolve): correctly handle Windows drive paths with leading slash

### LINKED ISSUE #412: Native resolver plugins throw errors in Astro projects when running in `debug` mode
### Description

I came across this issue while debugging [rolldown/rolldown#6164](https://github.com/rolldown/rolldown/issues/6164). To reproduce, first set up a basic Astro project, ref: [Astro basics example](https://github.com/withastro/astro/tree/main/examples/basics).

After that, link both rolldown-vite and rolldown locally as below:
```js
"pnpm": {
  "overrides": {
    "vite": "link:D:\\shulaoda\\rolldown-vite\\packages\\vite"
  }
}
```

Afterwards, run `just build` under `rolldown` to build the debug program. Next, run `pnpm build` in the basic Astro project. At this point, the following error will be shown:
```bash
thread 'tokio-runtime-worker' panicked at C:\Users\dalao\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\oxc_resolver-11.7.1\src\lib.rs:475:9:
assertion failed: Path::new(specifier).components().next().is_some_and(|c|
        matches!(c, Component::CurDir | Component::ParentDir |
            Component::Normal(_)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens because the `resolver` receives an `args.id` like `/D:/shulaoda/basics/src/middleware`. When passed to `oxc-resolver` (see [here](https://github.com/rolldown/rolldown/blob/f42cec6b/crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs#L406)), it goes through `self.require_absolute`, which then calls `self.load_roots`. Inside `load_roots`, after `strip_prefix SLASH_START`, it falls back to `require_relative`. However, this case is not handled, leading to a `debug_assert` failure in `require_relative` ([oxc-resolver/src/lib.rs#L475-L478](https://github.com/oxc-project/oxc-resolver/blob/a51c82b7/src/lib.rs#L475-L478)).

### PR DESCRIPTION
**Pull request by shulaoda**
closes https://github.com/vitejs/rolldown-vite/issues/412

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#6209** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6209?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6209?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6209).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs [hunk 1]
```diff
@@ -224,7 +224,21 @@ impl Plugin for ViteResolvePlugin {
       return Ok(Some(HookResolveIdOutput { id: args.specifier.into(), ..Default::default() }));
     }
 
-    let mut id = Cow::Borrowed(args.specifier);
+    let mut id = {
+      #[cfg(windows)]
+      {
```
Comment (sapphi-red) [inline crates/rolldown_plugin_vite_resolve/src/vite_resolve_plugin.rs:229]:
```suggestion
      {
        // handle /C:/foo/bar
```

**Review by sapphi-red — APPROVED** [review]
