### PR TITLE
fix: correctly handle inlined CommonJS exports in member expressions

### LINKED ISSUE #6080: [Bug]: inlining constants in CJS by `optimization.inlineConst` breaks the code
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNptkLFuwzAMRH+F4JIUCNR0FdCpH9FFi2DTqQqZDCQmDWro30PbcJAhgwYeT/dOmnBAP2GRnHv5Y9cJD+nkfuusMvpXmwN2tqDbWYpCT0O8ZIUpMICcNY3pP2oS9qsEkDgnpi/hqh60XGiWW+CG7YCJe7o94R7zCknjAikUO4WhyAg7975M5tmFEng+Vq3aWgQ+V6u7UqnWwVWNRet30p99wI+Ab5tdMrksp71dWjTjEfq5nZXaAI8/2Obnl9cNYlDLdkd3DLhENYu4mi9HparY7nqueOI=)

### What is expected?

The output to be like:
```js
//#region index.js
var import_react = /* @__PURE__ */ __toESM(require_react());
const foo = "1.0.0".startsWith("1");
console.log(foo);

//#endregion
```

### What is actually happening?

The output is:
```js
//#region index.js
var import_react = /* @__PURE__ */ __toESM(require_react());
const foo = "1.0.0"("1");
console.log(foo);

//#endregion
```
(`.startsWith` is removed incorrectly)

### System Info

```Shell
REPL 1.0.0-beta.36
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Fixes #6080

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6090** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6090?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6090?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6090).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 1]
```diff
@@ -639,20 +639,29 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
...
+              target_commonjs_exported_symbol_meta
+                .is_some_and(|(_symbol, is_exports_default)| !is_exports_default),
+            )
+          };
+          self.snippet.member_expr_or_ident_ref(
+            object_ref_expr,
+            // For commonjs member_expr resolving, the resolved ref is always namespace_alias,
+            // so the props actually inclulde the exported name, when inline member_expr access of commonjs exported
+            // symbol, we should skip the first prop
+            &props[usize::from(is_inlined_commonjs_export)..],
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/module_finalizers/mod.rs:662]: Clippy suggested writing like this,

File: crates/rolldown/tests/rolldown/tree_shaking/commonjs_inline_const/main.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import * as ns from "./src/basic_ns/";
+import default_cjs from "./src/basic_ref_with_named_default";
+import * as export_star_from_cjs from "./src/export_star_from_cjs/";
+import { a } from "./src/named_import_export_star_from_cjs/";
+import {another as another1} from "./src/nested_export_star_from_cjs/";
+import react from './src/indirect_common_js/'
+
+assert.equal(ns.a, "basic-a");
+assert.equal(ns.a.startsWith("b"), true);
+// //
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/tree_shaking/commonjs_inline_const/main.js]:
```suggestion

```

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 3]
```diff
@@ -639,20 +639,29 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
...
+              object_ref,
+              false,
+              target_commonjs_exported_symbol_meta
+                .is_some_and(|(_symbol, is_exports_default)| !is_exports_default),
+            )
+          };
+          self.snippet.member_expr_or_ident_ref(
+            object_ref_expr,
+            // For commonjs member_expr resolving, the resolved ref is always namespace_alias,
+            // so the props actually inclulde the exported name, when inline member_expr access of commonjs exported
```
Comment (sapphi-red) [inline crates/rolldown/src/module_finalizers/mod.rs]:
```suggestion
            // so the props actually include the exported name, when inline member_expr access of commonjs exported
```

**Review by sapphi-red — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Sep 9, 10:44 AM UTC**: The merge label 'graphite: merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Sep 9, 11:19 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown).
* **Sep 9, 11:31 AM UTC**: The [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown) couldn't merge this PR because **it was not satisfying all requirements** (Failed CI: 'node-test (macos-latest) / Node Test').
* **Sep 9, 11:54 AM UTC**: The merge label 'graphite: merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Sep 9, 11:57 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown).
* **Sep 9, 12:08 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.dev/merges?org=rolldown&repo=rolldown).
