### PR TITLE
fix: optimization.inlineConst: true generates invalid code when importing a module statically and dynamically

### LINKED ISSUE #5197: [Bug]: `optimization.inlineConst: true` generates invalid code when importing a module statically and dynamically
### Reproduction link or steps

1. Open [https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-tt3ajde1?file=rolldown.config.mjs,src%2Findex.mjs,src%2Fbar.mjs,dist%2Findex.js](https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-tt3ajde1?file=rolldown.config.mjs,src%2Findex.mjs,src%2Fbar.mjs,dist%2Findex.js)
2. `pnpm i` runs automatically
3. `pnpm build` runs automatically

### What is expected?

`renderChunk` hook is called with a valid code.

### What is actually happening?

`renderChunk` hook is called with an invalid code.

```
import "./bar-!~{002}~.js";

export { bar_default as default };
```

### System Info

```Shell
StackBlitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.3https://linear.app/voidzero/issue/ENG-805/bug-optimizationinlineconst-true-generates-invalid-code-when-importing0GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @rolldown/browser:  1.0.0-beta.24
```

### Any additional comments?

Found while testing `optimization.inlineConst` in rolldown-vite ([https://github.com/vitejs/rolldown-vite/pull/314](https://github.com/vitejs/rolldown-vite/pull/314)).

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #5197

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#5399** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5399?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5398** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5398?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5398?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs [hunk 1]
```diff
@@ -120,7 +126,7 @@ impl LinkStage<'_> {
                 include_statement(context, module, stmt_info_id);
               },
             );
-            include_symbol(context, *symbol_ref);
+            include_symbol(context, *symbol_ref, IncludeKind::DynamicImport);
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs:129]: We can always inline always static symbol linking and rewrite it into a `literal`, but for all symbols export by entry point, we need to inclued it anyway.

**Review by hyf0 — APPROVED** [review]
