### PR TITLE
fix: avoid unresolved promise if load same id at concurrent

### LINKED ISSUE #2751: [Bug]: gets stuck when calling `this.load` with same id in parallel
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-qaagcu?file=rolldown.config.mjs,package.json
2. `npm run build` runs automatically
3. Rolldown command does not end

Note this happens not only on Stackblitz but also on Windows as well.

### What is expected?

The build finishes.

### What is actually happening?

The build does not finish.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@cce5cde => 0.14.0
```

### Any additional comments?

I found this when I tried to enable some disabled tests in rolldown-vite.

### PR DESCRIPTION
**Pull request by underfin**
### Description

close https://github.com/rolldown/rolldown/issues/2751

### CODE REVIEW

File: packages/rolldown/src/plugin/plugin-context.ts [hunk 1]
```diff
@@ -74,17 +74,32 @@ export class PluginContext extends MinimalPluginContext {
...
-      })
-      await context.load(
-        id,
-        bindingifySideEffects(options.moduleSideEffects),
-        resolveFn!,
-      )
-      await promise
+
+      async function createLoadModulePromise() {
+        if (data.loadModulePromiseMap.has(id)) {
```
Comment (IWANABETHATGUY) [inline packages/rolldown/src/plugin/plugin-context.ts]: get and checking if it is null, could avoid hash twice.

Comment (underfin) [reply packages/rolldown/src/plugin/plugin-context.ts]: Done.

**Comment by IWANABETHATGUY** [comment]
I try the issue case locally,  it does not seems to work, still stuck when bundling

**Review by IWANABETHATGUY — APPROVED** [review]
