### PR TITLE
fix(rolldown_plugin_import_glob): correctly handle alias glob patterns

### LINKED ISSUE #4971: [Bug]: thread 'tokio-runtime-worker' panicked at rolldown_plugin_import_glob: Invalid glob pattern: @/assets/**/*.png
### Reproduction link or steps

https://stackblitz.com/edit/github-gzbuzr-8ysvjcvj

> For some reason, pnpm i hangs in stackblitz, please download the project and run it locally

1. Run `pnpm i`
2. Run `pnpm build`
3. Observe that you get error log and the remaining build hangs
```
thread 'tokio-runtime-worker' panicked at crates\rolldown_plugin_import_glob\src\utils.rs:316:7:
Invalid glob pattern: @/assets/**/*.png
```

### What is expected?

The build should be successful, the build/glob works if vite experimental native plugin is not enabled.

### What is actually happening?

rolldown_plugin_import_glob is giving an error with invalid import glob. I'm not actually sure if this is an issue with rolldown-vite, as I'm using that with nuxt, but the error points to source code within the rolldown plugin, so I'll open the issue here.

> Background context: I'm currently trying to migrate my whole nuxt app to rolldown vite! Everything is going well until I enable the native plugins, and this error pops up. If native plugin is disabled, app builds successfully.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 7730U with Radeon Graphics
    Memory: 5.04 GB / 38.83 GB
  Binaries:
    Node: 24.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.2.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.2.15 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (135.0.3179.85)
    Internet Explorer: 11.0.26100.1882
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
closes #4971

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#5007** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5007?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5007?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#5006** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5006?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_utils/src/futures.rs [hunk 1]
```diff
@@ -37,3 +37,14 @@ where
...
 }
+
+pub fn block_on<F: Future>(f: F) -> F::Output {
+  #[cfg(target_family = "wasm")]
+  {
+    futures::executor::block_on(f)
+  }
+  #[cfg(not(target_family = "wasm"))]
+  {
+    tokio::task::block_in_place(move || tokio::runtime::Handle::current().block_on(f))
```
Comment (hyf0) [inline crates/rolldown_utils/src/futures.rs:48]: I remember this breaks under wasm env. Could you give a try on stackblitz?

Comment (shulaoda) [reply crates/rolldown_utils/src/futures.rs:48]: Yes! I was planning to do it.

Comment (shulaoda) [reply crates/rolldown_utils/src/futures.rs:48]: It works. See https://stackblitz.com/edit/vitejs-rolldown-vite-eck8xc7z?file=src%2Fmain.js,package.json,vite.config.js,dist%2Fassets%2Findex-BI75GIKl.js

**Review by IWANABETHATGUY — APPROVED** [review]
