### PR TITLE
fix: resolve symbol deconfliction order for cross-chunk imports



### LINKED ISSUE #5737: [Bug]: Rolldown renames function when import has same name as export
### Reproduction link or steps

`package.json`:
```json
{
	"type": "module",
	"devDependencies": {
		"rolldown": "1.0.0-beta.32",
		"rollup": "^4.46.2"
	}
}
```
`roll.config.js`:
```js
export default { input: { "foo": "src/foo.js", "bar": "src/bar.js" }, output: { dir: "dist" } }
```
`src/foo.js`:
```js
export const foo = 0
```
`src/bar.js`:
```js
import { foo as foo_ } from "./foo.js"

export const foo = () => foo_

console.log(foo.name)
```

### What is expected?

when running `node src/bar.js`, it prints `foo`.

when running `pnpm rollup --config roll.config.js` then `node dist/bar.js`, it prints `foo`.

### What is actually happening?

when running `pnpm rolldown --config roll.config.js` then `node dist/bar.js`, it prints `foo$1`.

### System Info

```Shell
System:
    OS: Linux 6.12 cpe:/o:nixos:nixos:25.05 25.05 (Warbler)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12500
    Memory: 22.57 GB / 31.14 GB
    Container: Yes
    Shell: 4.0.2 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 22.17.1 - /run/current-system/sw/bin/node
    npm: 10.9.2 - /run/current-system/sw/bin/npm
    pnpm: 10.14.0 - /etc/profiles/per-user/samual/bin/pnpm
  npmPackages:
    rolldown: 1.0.0-beta.32 => 1.0.0-beta.32
```

### Any additional comments?

first, there's no conflicts so `foo_` shouldn't need changing in the first place. in any case, Rollup makes sure to rename where it has no semantic difference whereas Rolldown doesn't

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #5737

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#5742** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5742?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5742?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/chunk/deconflict_chunk_symbols.rs [hunk 1]
```diff
@@ -156,6 +133,29 @@ pub fn deconflict_chunk_symbols(
...
+      (
+        *id,
+        renamer.create_conflictless_name(&legitimize_identifier_name(&format!(
+          "require_{}",
+          index_chunk_id_to_name[id]
+        ))),
+      )
+    })
+    .collect();
+
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/chunk/deconflict_chunk_symbols.rs:158]: Deconflict symbol imported from another chunk after renaming all symbols in the current chunk could ensure that if a symbol defined in the current chunk conflicts with an imported symbol from another chunk, always prefer renaming the imported symbol.

File: crates/rolldown/tests/rolldown/topics/deconflict/issue_5737/artifacts.snap [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+export { foo };
+```
+## foo.js
+
+```js
+//#region foo.js
+const foo = 0;
+
+//#endregion
+export { foo };
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/topics/deconflict/issue_5737/artifacts.snap:33]: # Rolldown latest
https://repl.rolldown.rs/#eNptjs0KgzAQhF9l2ZOC3dr2JtgnCRS1iVhitsT0B8R370Zr6cHT7jDfMDOiwWLEuvJ0G+LnsFhVho2Irr+zDzCCYYZqiOcCExjPPSikvWiBFSqnnH7PbMNuCDNfQpJCeZ5DEYgOW02W2yQGXdXrVIo0FsE/9JShZ2uv/HIkqOlaCr9VG86yECW2rFjRr1rsjVG5cn+lEn8Kd6Cc8l2tQ0WnI04f5GVahQ==

# ROllup
https://rollupjs.org/repl/?version=4.46.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMGFzJTIwZm9vXyUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGZm9vLmpzJTVDJTIyJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwZm9vXyU1Q24lNUNuY29uc29sZS5sb2coZm9vLm5hbWUpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwMCU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE

**Review by shulaoda — APPROVED** [review]
