### PR TITLE
fix: remove redundant node check in dynamic entry graph construction

### LINKED ISSUE #5871: investigate panic for https://github.com/rolldown/rolldown/pull/5869
n/a

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #5871

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6730** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6730?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6730?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6730).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs [hunk 1]
```diff
@@ -295,14 +295,10 @@ impl LinkStage<'_> {
     for entry in dynamic_entries.iter() {
       let mut entry_module_idx = entry.idx;
       let cur = entry_module_idx;
-      if graph.contains_node(cur) {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs:298]: We can't skip visited the node, since if two dynamic entry modules reference each other, it will generate a wrong graph.

**Review by hyf0 — APPROVED** [review]
