### PR TITLE
fix:  crashes if json file is imported when experimental.hmr is enabled

### LINKED ISSUE #4818: [Bug]: crashes if json file is imported when `experimental.hmr` is enabled
### Reproduction link or steps

1. Open https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-kqp4hh3n
2. `pnpm i` runs automatically
3. `pnpm build` runs automatically

### What is expected?

No panic

### What is actually happening?

It panics with
```
thread 'tokio-runtime-worker' panicked at crates/rolldown_common/src/types/symbol_ref_db.rs:95:26:
No symbol found for 2 -> SymbolId(4294967292)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
worker (tid = 43) sent an error! unreachable
```

### System Info

```Shell
StackBlitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @rolldown/browser:  1.0.0-beta.11
```

### Any additional comments?

I'll set a higher priority when this gets important.

Currently this is not a blocker. I made the issue so that we can fix it later.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
Closed #4818

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4829** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4829?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4828** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4828?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4828?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/tests/fixtures/misc/issues/4818/_config.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { defineTest } from 'rolldown-tests'
+
+export default defineTest({
+  config: {
+    experimental: {
+      hmr: {},
```
Comment (hyf0) [inline packages/rolldown/tests/fixtures/misc/issues/4818/_config.ts:6]: Just a heads-up, you could write it in rust too.

**Review by hyf0 — APPROVED** [review]

File: packages/rolldown/tests/fixtures/misc/issues/4818/_config.ts (hunk 1 above)
Comment (IWANABETHATGUY) [reply packages/rolldown/tests/fixtures/misc/issues/4818/_config.ts:6]: Yeah, just want to reduce the snapshot tests if possible.
