### PR TITLE
fix(rolldown_plugin_json): avoid generating named exports for `eval` and `arguments`

### LINKED ISSUE #436: Cannot assign to 'eval' in strict mode
### Describe the bug

Adopting rolldown-vite in place of vite is making our build fail with:

```
✗ Build failed in 35.91s
error during build:
Build failed with 1 error:

[PARSE_ERROR] Error: Cannot assign to 'eval' in strict mode
    ╭─[ ../../node_modules/.pnpm/jsdom@25.0.1/node_modules/jsdom/lib/jsdom/browser/js-globals.json:54:14 ]
    │
 54 │ export const eval = {"writable":true,"enumerable":false,"configurable":true};
    │              ──┬─  
    │                ╰─── 
────╯

    at normalizeErrors (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown@1.0.0-beta.41/node_modules/rolldown/dist/shared/src-DkvlJJsC.mjs:2157:18)
    at handleOutputErrors (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown@1.0.0-beta.41/node_modules/rolldown/dist/shared/src-DkvlJJsC.mjs:2892:34)
    at transformToRollupOutput (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown@1.0.0-beta.41/node_modules/rolldown/dist/shared/src-DkvlJJsC.mjs:2886:2)
    at RolldownBuild.write (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown@1.0.0-beta.41/node_modules/rolldown/dist/shared/src-DkvlJJsC.mjs:4093:10)
    at buildEnvironment (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown-vite@7.1.14_@types+node@22.18.0_esbuild@0.25.10_jiti@2.5.1_terser@5.39.0_tsx@4.20.3_yaml@2.8.1/node_modules/rolldown-vite/dist/node/chunks/dep-ySrR9pW8.js:33173:64)
    at Object.build (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown-vite@7.1.14_@types+node@22.18.0_esbuild@0.25.10_jiti@2.5.1_terser@5.39.0_tsx@4.20.3_yaml@2.8.1/node_modules/rolldown-vite/dist/node/chunks/dep-ySrR9pW8.js:33577:19)
    at Object.buildApp (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/vike@0.4.240_react-streaming@0.4.2_react-dom@18.3.1_react@18.3.1__react@18.3.1__rolldow_a2c59aa9d563e14d171d9deb68ac7e30/node_modules/vike/dist/esm/node/vite/plugins/build/pluginBuildApp.js:34:33)
    at Object.buildApp (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown-vite@7.1.14_@types+node@22.18.0_esbuild@0.25.10_jiti@2.5.1_terser@5.39.0_tsx@4.20.3_yaml@2.8.1/node_modules/rolldown-vite/dist/node/chunks/dep-ySrR9pW8.js:33573:38)
    at CAC.<anonymous> (file:///Users/gajus/Developer/contra/gaia/node_modules/.pnpm/rolldown-vite@7.1.14_@types+node@22.18.0_esbuild@0.25.10_jiti@2.5.1_terser@5.39.0_tsx@4.20.3_yaml@2.8.1/node_modules/rolldown-vite/dist/node/cli.js:641:3)
```

### Reproduction

N/A

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: macOS 26.0
    CPU: (16) arm64 Apple M4 Max
    Memory: 13.40 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.6.0 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/node
    npm: 11.5.1 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/npm
    pnpm: 10.17.0 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/pnpm


  System:
    OS: macOS 26.0
    CPU: (16) arm64 Apple M4 Max
    Memory: 12.72 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.6.0 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/node
    npm: 11.5.1 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/npm
    pnpm: 10.17.0 - ~/.local/state/fnm_multishells/2901_1759245529802/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^5.0.1 => 5.0.1
    rolldown-vite:  7.1.14
    rollup: 4.52.0 => 4.52.0
```

### Used Package Manager

pnpm

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sapphi-red**
fixes https://github.com/vitejs/rolldown-vite/issues/436
refs #6140

### CODE REVIEW

**Comment by sapphi-red** [comment]
* **#6381** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6381?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6381?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#6382** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6382?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#6383](https://github.com/rolldown/rolldown/pull/6383) <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6383?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6381).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_utils/src/ecmascript.rs [hunk 1]
```diff
@@ -21,7 +21,10 @@ pub fn none_preserved_keyword_or_global_object_ext(name: &str) -> bool {
 }
 
 pub fn is_validate_assignee_identifier_name(name: &str) -> bool {
-  identifier::is_identifier_name(name) && !keyword::is_reserved_keyword_or_global_object(name)
+  identifier::is_identifier_name(name)
+    && !keyword::is_reserved_keyword_or_global_object(name)
+    && name != "arguments"
+    && name != "eval"
```
Comment (IWANABETHATGUY) [inline crates/rolldown_utils/src/ecmascript.rs]: Probably you could reuse this function? https://github.com/rolldown/rolldown/pull/6381/files#diff-6a3fb4be77e17012048912b7a250cd574d36433e6911bbb7c496e05b850a28deR19-R21

**Review by IWANABETHATGUY — APPROVED** [review]

**Review by IWANABETHATGUY — APPROVED** [review]
