### PR TITLE
fix(hmr): ensure correctness of `typeof require === 'function'`

### LINKED ISSUE #5619: [Bug]: `typeof require === 'function'` in CJS module should be `true` but is `false` in HMR patch file
See #5618

### PR DESCRIPTION
**Pull request by hyf0**
- Fixes https://github.com/rolldown/rolldown/issues/5619
- Closes https://github.com/rolldown/rolldown/pull/5618

### CODE REVIEW

**Comment by hyf0** [comment]
* **#5651** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5651?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5651?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#5650** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5650?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/hmr/hmr_ast_finalizer.rs [hunk 1]
```diff
@@ -667,13 +668,32 @@ impl<'ast> HmrAstFinalizer<'_, 'ast> {
...
-  // Rewrite `require(...)` to `(require_xxx(), __rolldown_runtime__.loadExports())` or keep it as is for external module importee.
-  pub fn try_rewrite_require(&self, it: &mut ast::Expression<'ast>) {
+  pub fn try_rewrite_require(
+    &self,
+    it: &mut ast::Expression<'ast>,
+    ctx: &oxc_traverse::TraverseCtx<'ast, ()>,
+  ) {
+    let scoping = ctx.scoping();
+
+    // Rewrite standalone `require` to `__rolldown_runtime__.loadExports`
```
Comment (sapphi-red) [inline crates/rolldown/src/hmr/hmr_ast_finalizer.rs:678]: Why is this rewritten to `__rolldown_runtime__.loadExports` instead of `__require`?

Comment (hyf0) [reply crates/rolldown/src/hmr/hmr_ast_finalizer.rs:678]: I haven't thought through the correct behavior. Webpack rewrites it into `__webpack_require__` while esbuild rewrites to `__require`. I just picked a way to solve #5619 first.

**Review by sapphi-red — APPROVED** [review]
