### PR TITLE
fix(hmr): should not panic for editing modules that contain `import(..)`

### LINKED ISSUE #5249: [Bug]: panics with `no entry found for key` when editing dynamic imports while HMR is enabled
### Reproduction link or steps

See #5248

### What is expected?

Does not crash.

### What is actually happening?

Crashes with
```
thread 'fixture_with_config_tests__rolldown__topics__hmr__dynamic_import_then__config_json' panicked at crates\rolldown\src\hmr\hmr_ast_finalizer.rs:234:65:
no entry found for key
```

### System Info

```Shell
https://github.com/rolldown/rolldown/tree/6dcfc7063a89b6857698298a21e3676036f22ab6
```

### Any additional comments?

related to https://github.com/rolldown/rolldown/pull/5223

### PR DESCRIPTION
**Pull request by hyf0**
Run

```
RD_LOG=hmr=trace RUST_BACKTRACE=FULL cargo test -p rolldown -- fixture_with_config_tests__rolldown__topics__hmr__dynamic_import__config_json --nocapture
```

Closes https://github.com/rolldown/rolldown/issues/5249
Closes https://github.com/rolldown/rolldown/pull/5248

### CODE REVIEW

**Comment by hyf0** [comment]
* **#5358** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5358?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5351** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5351?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5351?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/hmr/hmr_manager.rs [hunk 1]
```diff
@@ -191,10 +198,26 @@ impl HmrManager {
 
     let mut modules_to_invalidate = changed_modules.clone();
     // FIXME(hyf0): In general, only modules got edited need to be invalidated, because we need to refetch their latest content.
-    // For those modules that are not edited, we should be able to reuse their AST. But currently we don't have a good way to do that
-    // due to architecture limitation.
+    // For those modules that are not edited but affected, we should be able to reuse their previous AST instead of going through the whole
+    // module loading process again. But currently we don't have a good way to do that due to architecture limitation.
     modules_to_invalidate.extend(affected_modules.clone());
 
+    // FIXME: It's expected that `rolldown:runtime` appears in the `affected_modules`. But the module loader can't handle it properly, it'll
```
Comment (hyf0) [inline crates/rolldown/src/hmr/hmr_manager.rs:205]: @IWANABETHATGUY Just a heads-up.

File: crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap [hunk 2]
```diff
@@ -51,6 +53,175 @@ var init_main_0 = __rolldown_runtime__.createEsmInitializer(function() {
...
+			return to;
+		};
+		var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
+			value: mod,
+			enumerable: true
+		}) : target, mod));
+		var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
+		var __toDynamicImportESM = (isNodeMode) => (mod) => __toESM(mod.default, isNodeMode);
+	} finally {}
+});
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap:91]: [nit] Maybe this part should be hidden?

File: crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap [hunk 3]
```diff
@@ -51,6 +53,175 @@ var init_main_0 = __rolldown_runtime__.createEsmInitializer(function() {
...
+	try {
+		var ns_foo = {};
+		__rolldown_runtime__.__export(ns_foo, { foo: () => foo });
+		__rolldown_runtime__.registerModule("foo/index.mjs", { exports: ns_foo });
+		const hot_foo = __rolldown_runtime__.createModuleHotContext("foo/index.mjs");
+		const foo = "foo";
+	} finally {}
+});
+
+var init_rolldown_hmr_4 = __rolldown_runtime__.createEsmInitializer(function() {
```
Comment (sapphi-red) [inline crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap:113]: [nit] this one too.

**Review by sapphi-red — APPROVED** [review]

File: crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap (hunk 2 above)
Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/hmr/deconflict_import_bindings/artifacts.snap:91]: Let me do it in a seperate PR.
