### PR TITLE
fix: mark Node.js builtin modules as side-effect-free when resolved via `external` config

### LINKED ISSUE #8299: [rc.4 regression] `node:module` is added as side-effect to dist
While upgrading from rolldown rc.3 to rc.4 in obuild, i noticed it is unconditionally adding `node:module` import.

Here is a minimal reproduction:

https://github.com/pi0/reproductions/tree/rolldown/node-platform

```js
import { builtinModules } from "node:module";

import { build } from "rolldown"

await build({
  input: "src/index.ts", // console.log("Hello!");
  platform: "node",
  external: [
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ]
})
```

This will generate:

```js
import "node:module";

//#region src/index.ts
console.log("Hello!");

//#endregion
export {  };
```

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #8299

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#8304** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8304?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8304?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8304).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_plugin/src/utils/resolve_id_check_external.rs [hunk 1]
```diff
@@ -116,7 +117,13 @@ async fn resolve_external(
       ResolvedExternal::Absolute
     };
 
-  Ok(Some(ResolvedId { id: ModuleId::new(id), external, ..Default::default() }))
+  Ok(Some(ResolvedId {
+    is_external_without_side_effects: matches!(options.platform, rolldown_common::Platform::Node)
+      && is_nodejs_builtin_module(&id),
```
Comment (sapphi-red) [inline crates/rolldown_plugin/src/utils/resolve_id_check_external.rs:122]: I think we should align this with https://github.com/rolldown/rolldown/blob/d37377afe9f9dab57dad9252a4f008523d9c171d/crates/rolldown_plugin/src/utils/resolve_id_with_plugins.rs#L147-L149
(change this to `is_external_without_side_effects: is_nodejs_builtin_module(&id)`)

Comment (IWANABETHATGUY) [reply crates/rolldown_plugin/src/utils/resolve_id_check_external.rs:122]: The branch can only be reached when `platform: 'node'` is set, related code https://github.com/rolldown/rolldown/blob/daa5640795cb939ada7d1550526ad837258b0fbd/crates/rolldown_resolver/src/resolver_config.rs#L132

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Feb 13, 4:00 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Feb 13, 4:04 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Feb 13, 4:16 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).

File: crates/rolldown_plugin/src/utils/resolve_id_check_external.rs (hunk 1 above)
Comment (sapphi-red) [reply crates/rolldown_plugin/src/utils/resolve_id_check_external.rs:122]: I see.

**Review by sapphi-red — APPROVED** [review]

**Review by hyf0 — APPROVED** [review]
