### PR TITLE
fix: legal comments above directives are not preserved

### LINKED ISSUE #6536: [Bug]: Legal comments above directives are not preserved
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNptT0FqxDAM/IqqS2AJ2btLT31AoWdfQqIsLrYcbKXdEvL3Kvame9gFG8GMZkaz4oRmxRS9H+MPd0PkyV06yTvKaJ4xLQ5KuDDHJCC/M8EKn7e1j1lc5AwbTCkGaA55Y9myWmSBamQeJG+wWgZwPC9ioNp3gaTvCtTuZFyksGUTwNOl9+8xBGLJBhrH3jFpFsBmWZ9lupYzR5r6xR/hlnFr0fFI1y58/Xe9A7Xi+fRik5qdapCKS1LFzvsoH5dMkCW5QSy+HvAtuHaeYtR+jY5m59Sf0EhaaNM7vjXK90JZcPsDF3SMQQ==)

### What is expected?

```js
/*!
 * legal comment
 */
```
is output

### What is actually happening?

```js
/*!
 * legal comment
 */
```
is not output

### System Info

```Shell
REPL 1.0.0-beata.43
```

### Any additional comments?

Probably related to #5482

### PR DESCRIPTION
**Pull request by shulaoda**
closes #6536

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#6787** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6787?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6787?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6787).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/pre_process_ecma_ast.rs [hunk 1]
```diff
@@ -37,6 +37,25 @@ impl PreProcessEcmaAst {
...
+          while i < program.comments.len() {
+            let comment = &mut program.comments[i];
+            if comment.attached_to == directive.span.start {
+              comment.attached_to = 0;
+            } else if comment.attached_to > directive.span.start {
+              break;
+            }
+            i += 1;
+          }
+        }
```
Comment (sapphi-red) [inline crates/rolldown/src/utils/pre_process_ecma_ast.rs:55]: I think this is more simple.
```rust
 let last_directive_pos = program.directives.last().span.start
 while i < program.comments.len() {
    let comment = &mut program.comments[i];
    if comment.attached_to >= last_directive_pos {
      break;
    }
    comment.attached_to = 0;
    i += 1;
}
```

**Review by sapphi-red — COMMENTED** [review]
Does this work with `minify: 'dce-only'`?

File: crates/rolldown/src/utils/pre_process_ecma_ast.rs (hunk 1 above)
Comment (shulaoda) [reply crates/rolldown/src/utils/pre_process_ecma_ast.rs:55]: We must first verify that the comment is attached to the directive; otherwise we might reassign the wrong thing. Comments could be attached to the hashbang or other nodes, so account for those as well.

**Comment by shulaoda** [comment]
> Does this work with `minify: 'dce-only'`?

Yes,

File: crates/rolldown/src/utils/pre_process_ecma_ast.rs (hunk 1 above)
Comment (shulaoda) [reply crates/rolldown/src/utils/pre_process_ecma_ast.rs:55]: In addition, a single directive may have multiple attached comments.

Comment (shulaoda) [reply crates/rolldown/src/utils/pre_process_ecma_ast.rs:55]: I can’t be certain that the first few comments are always attached to the directives.

Comment (sapphi-red) [reply crates/rolldown/src/utils/pre_process_ecma_ast.rs:55]: Ok, let's keep it as-is.

File: crates/rolldown/src/utils/pre_process_ecma_ast.rs [hunk 2]
```diff
@@ -37,6 +37,25 @@ impl PreProcessEcmaAst {
     has_lazy_export: bool,
   ) -> BuildResult<ParseToEcmaAstResult> {
     let source = ast.source().clone();
+
+    // Step 0: Keep directive comments attached to 0.
```
Comment (sapphi-red) [inline crates/rolldown/src/utils/pre_process_ecma_ast.rs]:
```suggestion
    // Step 0: Move directive comments attached to 0 so that it's not removed when the directives are removed
```

**Review by sapphi-red — APPROVED** [review]
