### PR TITLE
fix: TypeError when loading CJS files after bundling mixed CJS+TS project 

### LINKED ISSUE #5930: [Bug]: TypeError when loading CJS files after bundling mixed CJS+TS project
### Reproduction link or steps

https://github.com/9romise/rolldown-cjs-issue

1. pnpm install
2. pnpm run build
3. pnpm run test

### What is expected?

No error

### What is actually happening?

When using `rolldown` to bundle a mixed CommonJS + TypeScript project, running the output results in a runtime error when require a CommonJS file:

`TypeError: require_rule$1.require_rule is not a function`

### System Info

```Shell
System:
    OS: macOS 26.0
    CPU: (12) arm64 Apple M4 Pro
    Memory: 368.41 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.16.0 - ~/.nvm/versions/node/v22.16.0/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.16.0/bin/npm
    pnpm: 10.5.0 - ~/.nvm/versions/node/v22.16.0/bin/pnpm
  Browsers:
    Chrome: 139.0.7258.139
    Safari: 26.0
  npmPackages:
    rolldown: 1.0.0-beta.34 => 1.0.0-beta.34
```

### Any additional comments?

I’m unsure if this is due to my configuration or usage.

If I’m doing something wrong, please let me know.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #5930

Current issue: 
https://repl.rolldown.rs/#eNplUctOwzAQ/JWVT6mIXHHEqEeOiANHzMFNNsGVY6d+FKQq/87aTlFET/a+Zmdmr2xg4sompS0/hfy1TPyFLeso0tPsfITJ9TB4N4FkfO+TQcmepV2LKgSkZ61b16OoqdIkbedsiDCbNGoLB7hKCxmwlXahem3lIXrdxZdzUqaprZx6+IRRtfD4tKNO/CnrehxUMjdAyhNVZCL6hEvLjD5uxKxR1UJ4xJxXmJCZ5P2MhrKizdQtrGOVfnbgAB7PSXtssg2ELVnmJe09cta438PH2/GEXQRXns+inBQJ8qm6yA3aMX7BA7yTAXZsCGq3JskggM6jiihgSLaL2llodhWdSkTM0VrjRiJknOqxhwqbaQEsq8VFojOmd9+W09Sgx63a+0oV/s/vstWlOKcobhQG5ydFoWTdKUhWGAPMHummF3wttgQB+TaFEPFhC7G55NuQrhDZ8gst29p6

The binding finalization only considers when the required CJS module is in a common chunk, 
so it always converts 
```
const mod = require('./lib')
```
to 
```js
const mod = require_rule$1.require_rule()
```

This did not consider if the wrap_ref is exported via entry cjs module, which may generate 
```
Object.defineProperty(exports, 'default', {
  enumerable: true,
  get: function () {
    return require_rule();
  }
});
```

this pr fixed this scenario.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6755** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6755?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6743** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6743?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6743?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6743).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/mod.rs [hunk 1]
```diff
@@ -277,13 +296,21 @@ impl<'me, 'ast> ScopeHoistingFinalizer<'me, 'ast> {
...
-            self.snippet.literal_prop_access_member_expr_expr(require_binding, exported_name)
+            if self.ctx.chunk_graph.chunk_table[chunk_idx_of_canonical_symbol].entry_module_idx()
+              == Some(canonical_ref.owner)
+              && matches!(self.ctx.linking_infos[canonical_ref.owner].wrap_kind(), WrapKind::Cjs)
+            {
+              hint.insert(FinalizedExprProcessHint::FromCjsWrapKindEntry);
+              self.snippet.literal_prop_access_member_expr_expr(require_binding, "default")
+            } else {
+              let exported_name = &self.ctx.chunk_graph.chunk_table[chunk_idx_of_canonical_symbol]
+                .exports_to_other_chunks[&canonical_ref][0];
```
Comment (hyf0) [inline crates/rolldown/src/module_finalizers/mod.rs:310]: Would it be more proper to prevent the wrong logic in the begaining instead of catching it up here?

`&self.ctx.chunk_graph.chunk_table[chunk_idx_of_canonical_symbol]
                .exports_to_other_chunks[&canonical_ref][0]` seems just produce a wrong result based on the repl https://repl.rolldown.rs/#eNplUctOwzAQ/JWVT6mIXHHEqEeOiANHzMFNNsGVY6d+FKQq/87aTlFET/a+Zmdmr2xg4sompS0/hfy1TPyFLeso0tPsfITJ9TB4N4FkfO+TQcmepV2LKgSkZ61b16OoqdIkbedsiDCbNGoLB7hKCxmwlXahem3lIXrdxZdzUqaprZx6+IRRtfD4tKNO/CnrehxUMjdAyhNVZCL6hEvLjD5uxKxR1UJ4xJxXmJCZ5P2MhrKizdQtrGOVfnbgAB7PSXtssg2ELVnmJe09cta438PH2/GEXQRXns+inBQJ8qm6yA3aMX7BA7yTAXZsCGq3JskggM6jiihgSLaL2llodhWdSkTM0VrjRiJknOqxhwqbaQEsq8VFojOmd9+W09Sgx63a+0oV/s/vstWlOKcobhQG5ydFoWTdKUhWGAPMHummF3wttgQB+TaFEPFhC7G55NuQrhDZ8gst29p6

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/src/module_finalizers/mod.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/mod.rs:310]: The `default` binding is generated at the chunk level by string replace https://github.com/rolldown/rolldown/blob/8406bc782847411c199d321034fe5f7475667dba/crates/rolldown/src/utils/chunk/render_chunk_exports.rs?plain=1#L266-L280 .  .To do that, we need to bind the `canonical_ref` to chunk-level default binding; that's not possible for now.

Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/mod.rs:310]: Wait, it is expected to do that here, since the wrapper_ref binding generation depends on whether the `wrapper_ref` declaration is in the same chunk as the importer
