### PR TITLE
test: make dev server tests deterministic by replacing fixed sleeps with event-driven polling

### LINKED ISSUE #8556: Dev-server tests: replace time-based synchronization with event-driven approach
## Previous findings

- Dec 19, 2025 (#7588): Browser HMR tests were flaky because files modified during tests remained in modified state on retry, causing find-and-replace to fail. Fixed by adding `resetTestFiles()` in `beforeEach` hook.
- Dec 18, 2025: Dev-server tests separated into their own CI workflow due to flakiness affecting other test suites.
- Watch config uses poll-based watching (`usePolling: true`, 50ms interval) + debouncing (310ms duration, 300ms tick rate) specifically because native FS events are unreliable in CI.
- `sensibleTimeoutInMs` multiplies all timeouts by 3× in CI environments.
- Vitest configs set `retry: 3` in CI for both fixture and browser test suites.
- Test timeout increased from 40s to 90s for Windows compatibility.

## Why this matters

The hardcoded sleeps and retries make CI slow. A single fixture test step waits 2130ms (710ms × 3 CI multiplier) between HMR steps, plus 6000ms for module registration, plus 6000ms for reload waits. Multiply by retry count of 3 and multiple fixtures, and the dev-server test suite burns minutes on sleeping alone. Fixing the synchronization model removes both the flakiness and the wasted CI time.

## Problem

The dev-server tests (`packages/test-dev-server/`) are flaky because they rely on **hardcoded sleeps and polling** to synchronize with the dev engine pipeline:

```
File write → FS poll (50ms) → Debounce (310ms+300ms) → Coordinator → Build → HMR compute → JS callback → WebSocket → Client → Observable result
```

Each step has non-deterministic latency. Tests use fixed timeouts to "wait long enough", which is inherently fragile.

### Hardcoded timing hacks

| File | Sleep | Purpose |
|------|-------|---------|
| `fixtures.test.ts:102` | 710ms (2130ms CI) | Debounce gap between HMR steps |
| `fixtures.test.ts:130` | 2000ms (6000ms CI) | Wait before sending reload message |
| `fixtures.test.ts:184` | 2000ms (6000ms CI) | Wait for module registration |
| `test-utils.ts:25` | 1000ms | After every file edit for FS events |
| `vitest-setup-playwright.ts:146` | 3000ms | File reset on retry |
| `vitest.config.*.mts` | `retry: 3` in CI | Masks all the above |
| `src/utils.ts:20` | All timeouts ×3 in CI | Brute-force margin |

### Root causes

1. **FS watcher poll+debounce timing is non-deterministic**: A file write takes 360ms-660ms+ to be detected, depending on where in the poll/tick cycle it lands.

2. **No back-channel from dev engine to tests**: Tests have zero visibility into dev engine state. They write a file and blindly hope the entire pipeline completes within a hardcoded timeout.

3. **Module registration race** (`fixtures.test.ts:184`): Test sleeps 2s after starting artifact process, hoping WebSocket module registration completes. If the Node process or WebSocket is slow, HMR computation finds zero clients.

4. **Rust-side FIXME** (`bundle_coordinator.rs:84`): State set to `Idle` before initial build starts — acknowledged as wrong in a FIXME comment.

## Proposed solution

Replace time-based waits with **event-driven synchronization**:

1. Have the dev server expose a "pipeline idle" signal (REST endpoint like `GET /_dev/status` returning `{ idle: true, buildCount: N }`, or a signal file) that tests can await after each file edit.

2. Replace `sleep()` calls in fixture tests with: write file → await idle signal → assert result.

3. For module registration: emit a "client registered" event instead of sleeping 2s.

4. Fix the coordinator FIXME at `bundle_coordinator.rs:84`.

This would make tests deterministic regardless of system speed and allow removing the retry count and timeout multipliers.

### PR DESCRIPTION
**Pull request by Boshen**
## Summary

- Add a `/_dev/status` endpoint to the dev server exposing `buildSeq`, `moduleRegistrationSeq`, and bundle state counters
- Replace all fixed `setTimeout` sleeps in test synchronization with event-driven polling utilities (`waitForNextBuild`, `waitForBuildStable`, `waitForModuleRegistration`)
- Remove `sensibleTimeoutInMs` helper and unused `CONFIG.watch` references
- On retry, fully restart the dev server with fresh files instead of relying on sleep + page reload
- Fix `buildSeq` double-increment on full-reload HMR builds (skip increment in `onHmrUpdates` when FullReload is present, since `onOutput` will handle it)

Eliminates all hardcoded sleeps (710ms-6000ms, x3 on CI) that caused flakiness and wasted CI minutes.

### Local test results (macOS, 3 runs each)

| | main (sleeps) | this PR (polling) | Improvement |
|---|---|---|---|
| **Fixtures** | 17.24s avg | 7.54s avg | **56% faster** |
| **Browser** | 10.76s avg | 9.43s avg | **12% faster** |
| **Total** | 28.00s avg | 16.97s avg | **39% faster** |
| **Reliability** | 3/3 passed | 3/3 passed | OK |

### CI job time comparison (avg of 3 runs each)

| Platform | main | this PR | saved |
|----------|------|---------|-------|
| Ubuntu | 5m28s | 3m36s | 1m52s (34% faster) |
| macOS | 5m05s | 2m55s | 2m10s (43% faster) |
| Windows | 7m30s | 5m36s | 1m54s (25% faster) |

Closes #8556

### CODE REVIEW

File: packages/test-dev-server/tests/vitest-setup-playwright.ts [hunk 1]
```diff
@@ -142,8 +143,8 @@ beforeEach(async (ctx) => {
   const retryCount = ctx.task.result?.retryCount ?? 0;
   if (retryCount > 0) {
     await resetTestFiles();
-    // Wait for file system watcher to detect and process the changes
-    await new Promise((resolve) => setTimeout(resolve, 1000 * 3));
+    // Wait for the dev server to finish rebuilding after file reset
+    await waitForBuildStable(3000);
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/tests/vitest-setup-playwright.ts]: Fixed — now snapshot buildSeq before resetTestFiles() and waitForNextBuild() after. See 2d07fe8.

File: packages/test-dev-server/tests/test-utils.ts [hunk 2]
```diff
@@ -37,3 +36,82 @@ export function getPage() {
...
+  hasStaleOutput: boolean;
+  lastFullBuildFailed: boolean;
+  buildSeq: number;
+  connectedClients: number;
+  registeredClients: number;
+}
+
+async function fetchDevStatus(port: number): Promise<DevStatus> {
+  const res = await fetch(`http://localhost:${port}/_dev/status`);
+  return res.json();
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/tests/test-utils.ts]: Fixed — added 5s AbortSignal timeout and res.ok check. See 2d07fe8.

File: packages/test-dev-server/tests/test-utils.ts [hunk 3]
```diff
@@ -37,3 +36,82 @@ export function getPage() {
...
+  const start = Date.now();
+  let lastSeq = -1;
+  let lastChangeTime = start;
+  while (Date.now() - start < timeoutMs) {
+    try {
+      const status = await fetchDevStatus(port);
+      if (status.buildSeq !== lastSeq) {
+        lastSeq = status.buildSeq;
+        lastChangeTime = Date.now();
+      } else if (Date.now() - lastChangeTime >= stableMs) {
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/tests/test-utils.ts]: Intentionally not checking hasStaleOutput — it stays true in HMR mode (patches don't write full output), so requiring it to be false would cause the function to hang indefinitely for HMR builds.

File: packages/test-dev-server/tests/test-utils.ts [hunk 4]
```diff
@@ -12,6 +12,9 @@ export async function editFile(
   filename: string,
   replacer: (content: string) => string,
 ): Promise<void> {
+  // Wait for the build pipeline to stabilize before writing,
+  // so the watcher's debounce window from any previous edit has closed.
+  await waitForBuildStable(3000);
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/tests/test-utils.ts]: Added a clarifying comment. Extracting a constant triggers a knip unused-export warning since vitest-setup files aren't in knip's analysis scope.

File: packages/test-dev-server/src/dev-server.ts [hunk 5]
```diff
@@ -91,11 +93,13 @@ class DevServer {
...
           this.handleHmrUpdates(errOrUpdates.updates);
         }
+        this.#buildSeq++;
       },
       onOutput: (errOrOutputs) => {
         if (errOrOutputs instanceof Error) {
           console.error('Build error:', errOrOutputs);
         }
+        this.#buildSeq++;
       },
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/src/dev-server.ts:110]: onHmrUpdates and onOutput are mutually exclusive — HMR patches only fire onHmrUpdates, full rebuilds only fire onOutput. They don't double-increment for the same build event.

File: packages/test-dev-server/src/dev-server.ts [hunk 6]
```diff
@@ -169,6 +173,7 @@ class DevServer {
           case 'hmr:module-registered': {
             console.log('Registering modules:', clientMessage.modules);
             this.#devEngine?.registerModules(clientSession.id, clientMessage.modules);
+            this.#registeredClientCount++;
             break;
```
[the remark this answers is not in the document]
Comment (Boshen) [reply packages/test-dev-server/src/dev-server.ts:184]: Renamed to moduleRegistrationSeq on both server and client side. See 2d07fe8.

File: packages/test-dev-server/tests/fixtures.test.ts [hunk 7]
```diff
@@ -82,10 +87,12 @@ function main() {
 
         await waitForPathExists(nodeScriptPath);
 
-        let runningArtifactProcess = await runArtifactProcess(nodeScriptPath, tmpProjectPath);
+        let runningArtifactProcess = await runArtifactProcess(nodeScriptPath, tmpProjectPath, port);
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/fixtures.test.ts:91]: this one makes sense to me

File: packages/test-dev-server/tests/fixtures.test.ts [hunk 8]
```diff
@@ -95,16 +102,11 @@ function main() {
...
-          if (index !== 0) {
-            await sensibleTimeoutInMs(
-              CONFIG.watch.debounceDuration + CONFIG.watch.debounceTickRate + 100,
-            );
-          }
+          // Wait for buildSeq to stabilize before writing the next step's files.
+          // This ensures the debounce window from any previous build has closed,
+          // so the watcher will detect our new writes as a separate change.
+          const stable = await waitForBuildStable(port);
+          currentBuildSeq = stable.buildSeq;
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/fixtures.test.ts]: I guess this is wrong as it doesn't ensure that all edits are detected in a single build.

File: packages/test-dev-server/tests/fixtures.test.ts [hunk 9]
```diff
@@ -127,16 +129,24 @@ function main() {
...
+              currentBuildSeq = status.buildSeq;
             }
             await runningArtifactProcess.close();
             await waitForFileToBeModified(nodeScriptPath, currentArtifactContent);
-            runningArtifactProcess = await runArtifactProcess(nodeScriptPath, tmpProjectPath);
+            runningArtifactProcess = await runArtifactProcess(nodeScriptPath, tmpProjectPath, port);
+          } else {
+            // Wait for HMR build to complete
+            const status = await waitForNextBuild(port, currentBuildSeq);
+            currentBuildSeq = status.buildSeq;
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/fixtures.test.ts]: These make sense, but I guess it's not needed because ` await waitForPathExists(nodePath.join(tmpProjectPath, `ok-${index}`), 10 * 1000);` will wait for the same thing.

File: packages/test-dev-server/tests/test-utils.ts [hunk 10]
```diff
@@ -12,6 +12,10 @@ export async function editFile(
   filename: string,
   replacer: (content: string) => string,
 ): Promise<void> {
+  // Wait for the build pipeline to stabilize before writing,
+  // so the watcher's debounce window from any previous edit has closed.
+  // Port 3000 is the default dev server port used by browser tests
+  await waitForBuildStable(3000);
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/test-utils.ts]: The same with https://github.com/rolldown/rolldown/pull/8561/changes#r2923520761

File: packages/test-dev-server/tests/test-utils.ts [hunk 11]
```diff
@@ -37,3 +37,93 @@ export function getPage() {
...
+  hasStaleOutput: boolean;
+  lastFullBuildFailed: boolean;
+  buildSeq: number;
+  connectedClients: number;
+  moduleRegistrationSeq: number;
+}
+
+async function fetchDevStatus(port: number): Promise<DevStatus> {
+  const controller = new AbortController();
+  const timeout = setTimeout(() => controller.abort(), 5_000);
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/test-utils.ts]: nit: we can use `AbortSignal.timeout`

File: packages/test-dev-server/tests/test-utils.ts [hunk 12]
```diff
@@ -37,3 +37,93 @@ export function getPage() {
...
+  }
+}
+
+/** Poll until buildSeq increments past the given value (i.e., a new build completed). */
+export async function waitForNextBuild(
+  port: number,
+  currentBuildSeq: number,
+  timeoutMs = 30_000,
+): Promise<DevStatus> {
+  const start = Date.now();
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/test-utils.ts]: nit: we can use `vi.waitFor`

File: packages/test-dev-server/tests/test-utils.ts [hunk 13]
```diff
@@ -37,3 +37,93 @@ export function getPage() {
...
+  }
+  throw new Error(`Build not stable within ${timeoutMs}ms`);
+}
+
+/** Poll until moduleRegistrationSeq exceeds the given value (i.e., a new module registration happened). */
+export async function waitForModuleRegistration(
+  port: number,
+  currentSeq: number,
+  timeoutMs = 30_000,
+): Promise<DevStatus> {
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/test-utils.ts:124]: nit: we can use `vi.waitFor`

File: packages/test-dev-server/tests/vitest-setup-playwright.ts [hunk 14]
```diff
@@ -141,11 +142,12 @@ beforeAll(async () => {
...
   const retryCount = ctx.task.result?.retryCount ?? 0;
   if (retryCount > 0) {
+    // Snapshot buildSeq before resetting files so we can detect the resulting rebuild
+    const beforeReset = await waitForBuildStable(3000);
     await resetTestFiles();
-    // Wait for file system watcher to detect and process the changes
-    await new Promise((resolve) => setTimeout(resolve, 1000 * 3));
+    // Wait for the watcher-triggered rebuild to complete after file reset
+    await waitForNextBuild(3000, beforeReset.buildSeq);
     // Reload the page to ensure it reflects the reset file state
```
Comment (sapphi-red) [inline packages/test-dev-server/tests/vitest-setup-playwright.ts]: This does make sense but I guess it'd be easier to restarted the dev server here.
