### PR TITLE
fix: improve detection of `new URL(...)`

### LINKED ISSUE #2741: [Bug]: Rolldown crashes when the first argument of `new URL(, import.meta.url)` is a template literal
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-k7hfgs?file=src%2Fentry.js
2. `npm run build` runs automatically
3. rolldown crashes

I wrote ``new URL(`./${foo}.txt`, import.meta.url);`` in the reproduction above, but it seems it happens with ``new URL(`./foo.txt`, import.meta.url);`` as well.

### What is expected?

No crash happens and `new URL(, import.meta.url)` not to be processed by rolldown.

### What is actually happening?

A crash happens.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@cce5cde => 0.14.0
```

### Any additional comments?

I found this when I tried to upgrade rolldown in rolldown-vite.

### LINKED ISSUE #2744: [Bug]: throws an error with `new URL('data:image/png;base64,fooooo', import.meta.url)`
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-pu4nsy?file=src%2Fentry.js
2. `npm run build` runs automatically

### What is expected?

No error to happen and leave the `new URL` as-is.

### What is actually happening?

```
[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
invalid utf-8 sequence of 1 bytes from index 0

Error: Build failed
    at napi_create_error (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:4535:25)
    at eval (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1283:58)
    at NodeEnv.callIntoModule (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:639:19)
    at NodeEnv.callbackIntoModule (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:758:21)
    at f (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1277:37)
    at Object.dispatchOne (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1305:29)
    at Object.dispatch (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1321:43)
    at Worker.handler (/home/projects/github-xv4yss-k7hfgs/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:864:40) {
  code: 'GenericFailure'
}
```

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@cce5cde => 0.14.0
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by hyf0**
### Description

- Fixes #2741
- Fixes #2744

### CODE REVIEW

**Comment by hyf0** [comment]
* **#2749** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2747** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2747?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2747?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2746** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2746?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
...
...FbM/kEc3GLyOT+apHX21Sx/t9/rm92U7HrwSNd+/C797kzj1g4jK7jH2SW+qo0DTiB18Wj2GMomi5S/YBxoaETWsKBIsfXispyT5H1N6MZtijmNaI0YO7/epZeiRdHh1aac7cyypOHKN3Ttpeq5G+gO3iW4HS73N0nMDLYsAwuecSLL4YxCYqLVIw3mcDZWx4+mQjSnpAQdl5ib8WbN/nmJ+PXdPE//8iO1eA82MllY1VxldDEBzOXsfywJCkRVYPEbWBPn6H9KCEoGvHe48rpHaFJiDmk1BFUXJJHolFvjAyJnhyNp+CSBE4JtCfqC/7sccZB7Nv6DxpxReXe5mFezagJZIa8VyQ462I8Po3LPGyqShObodpyJI3cWKqiDJ3mzFJiOu+Kosyi+lr/V9jjWvlhCkf9uXa1QL5f3OHwN8P+z67YPwDRmTjc8j2oJ1ECn8w70f+XlFyfJrlGOpPjS93jrAWgN+X/+uUcuKZYZE3EQCRsFTJ42fqTZ5eCt/lXLrdjudA3vLexyBZzsyAJOIyu7uiv6olL/5pB+5YeakMelfC+rAL4NYGFiXaWO7eI1ID7fteXqr8y3zFn08xT4HdC6DjRb9bFX/IAkyWdzGAu1bpTVC02BVoJFa0PoGboq42Hwtpq1Yvp6LiIb5NU9LJ4EYRFHwEeOKLHas0PUN8UeiR+3zRTGCK38+ihBF4IL8IWvjQspsbbOperpfCxOq7tgLljv+Dj5ZrtPWolBGkY+YAj0KGuLYPXphkmZ3he7+UY9iGvgVNmHwMqrJs9RhAHrsbmBNdF/OD9tDFTyY/eroy6BYmBP1sd0BxMpQCO0wipCQB07biLfiz0iGQh/j5pbbiooso3ysDKgU6iEAENZ7GQtgcTxDAhPN5g/Y2OvfstKWAzeNAcgrfAfHreS9Cfa6M8NOpboCUg0xhYa7vBdl5VguSL4nHoDYDiztuQGrx4OgYPAtRFiVfWhdOCWLSXZ4ljQGi+KW3rG5V0X01dYZz6evIXP9wqHhkekw2K4y842vn82Rb6t+Pi6pgups0s1uNfLhui1LRbW34my38Go3JeuNaxQAfyW+4LPx9LvOHRxLR8XmMi3TGw1pSsP0Je64S2R4lD6XxOa/ujg+hf3Z3//R///o4r//ovn/9unf+Ebnn8cZgMBAwsVra6s78StHcigPdOIHNGzgAAAA==',
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js:2]: Do we really need such complex `data URL` as a snapshot test case?

Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js:2]: Need real-world data to check if everthing work as expected. Sush as logic here https://github.com/rolldown/rolldown/blob/2b4f224f665006daaccc8755847cc17607efa33a/crates/rolldown_plugin_data_url/src/data_url_plugin.rs#L39.

I didn't find a small dataurl data. This is copied from other tests.

Comment (IWANABETHATGUY) [reply crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js:2]: I don't think the data url  should be valid, since what you are test is https://github.com/rolldown/rolldown/pull/2747/files#diff-bb2d32b1441f7243e2d4eb6a81859573f1e93a5980ece94307d42247720dbc69R37

**Review by IWANABETHATGUY — APPROVED** [review]

**Comment by hyf0** [comment]
### Merge activity

* **Nov 15, 4:12 AM EST**: [Graphite](https://app.graphite.dev/github/pr/rolldown/rolldown/2747) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

File: crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js (hunk 1 above)
Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js:2]: The current solution may changes in the future. It may go through plugin hooks. I want use real-world data to ensure if everything work as expected in the future changes.

Comment (hyf0) [reply crates/rolldown/tests/rolldown/topics/new_url/dataurl/main.js:2]: We could switch to a small real-world dataurl I guess.

**Comment by sapphi-red** [comment]
@hyf0 It seems it's removed from merge-queue because of the flaky test.
