### PR TITLE
fix: `jsx.preserve` should also considering tsconfig json preserve

### LINKED ISSUE #8377: [Bug]: `UNTRANSPILED_SYNTAX` happens for `"jsx": "preserve"` in `tsconfig.json`
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNpVjUEKwzAMBL8idA7p3bT9Qj+gS0mU4pDaxlKDwfjvlZtLA7rszjKquKCr6MPMZVQpPQR0f8WAk2UuKWaFKQZRWGKEG1xnv8PlTpmCjRid5g+3AVVstfjXuEo01eE7l4ezUgAgnOI7+Y3zI6k3PaGDH+lsldIzYcosnHcm7KhRsMNm33YTbU9lUWxfDfZDgw==)

### What is expected?

To have the output the same with `transform.jsx: 'preserve'` ([REPL](https://repl.rolldown.rs/#eNptkEFqxDAMRa/y8SYthGQf2m56DW+cRO54cORgK2lK8N3r8XRKFwWB0NfXQ9KprBpO5Ximo5N03ApWwx+hVVOp6VhDFEyBk8CGgFe8zG5H/6aj5mIiNUjcKLcqBu/n8MldMVv30V3TA/pP5053S6WfmMk6pvfaRoaNYUHzGGs0a/5ZpBjN5mv+HXg6NQOO100G3JHdQmK6KrXoe8iFYJ2nhESeJqEZ41dVx00kMEqQmS4QM95gEg0nG+IyoMKBazoGNGukRHGnshKQNefn8oRcjt/LNd4IJVH5G0CAeCI=)).

### What is actually happening?

The following error happens:

> [UNTRANSPILED_SYNTAX] Error: JSX syntax should be transpiled before bundling. Found untranspiled JSX in "index.tsx"

### System Info

```Shell
REPL 1.0.0-rc.5
```

### Any additional comments?

Probably #8324 fixes this. Making an issue to track

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Previously, `FlatOptions::JsxPreserve` was determined once from the static bundler configuration (`transform_options.is_jsx_preserve()`). This didn't account for per-module tsconfig discovery — when a module's local `tsconfig.json` specifies `"jsx": "preserve"`, the static flag wouldn't reflect it.

This PR determines `preserve_jsx` per-module during transformation by checking the resolved `transform_options.jsx.jsx_plugin` after tsconfig discovery, then updates `FlatOptions::JsxPreserve` on the module's context accordingly.

closed https://github.com/rolldown/rolldown/issues/8377

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#8324** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8324?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8324?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#8323** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8323?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8324).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/pre_process_ecma_ast.rs [hunk 1]
```diff
@@ -113,6 +115,9 @@ impl PreProcessEcmaAst {
         let transform_options = bundle_options
           .transform_options
           .options_for_file(is_not_js.then_some(Path::new(resolved_id)), &mut warnings)?;
+        if !transform_options.jsx.jsx_plugin {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/pre_process_ecma_ast.rs:116]: I find that the flag is sufficient to determine whether the JSX needs to be transformed. Related code:

https://github.com/rolldown/rolldown/blob/fba05847ca942112dfdcad1dd9f3d72b655e2101/crates/rolldown_common/src/inner_bundler_options/types/transform_option/mod.rs#L118-L128

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Feb 20, 1:55 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Feb 20, 1:55 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Feb 20, 2:06 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
