### PR TITLE
fix: treat namespace member access as side-effect-free

### LINKED ISSUE #9061: [Bug]: unreachable dynamic chunks are kept
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNqNU02P0zAQ/SuzvqRFXfceVHFg98BlQYA4RUJuMt4NOHZlTwqlyn9n7HyQsql2o3zZbzx+M+/5LLTIz8I7R/JHiL9W5NNwI0oe1c3BeYIzfFX2C6ny52fXEvo7PJJzJkAH2rsGCiG3wZm6uvUJv62GgEK8LXxh44O/Uyrd2pJqZ0E7t1rDOUIApbO8HqVxj6vlrdYxsGNaKHLyLXYbsbjjrJSr+EVtb0AFmApK5WRyu0wi41LGQiJlutaXXSzq4F2JIUi0R/nw8e7++/3DN7jZ7SBjMmjcoUFLnBL4evevMakraTJeHqn1FmxrzDjZ9T/5xFous3gl2Q/2k3dVT/nFjL0AWpkQFViOmklwPaDXYKRnVAjXejlY5MIvAL16K5bKqD8nzpglh8TuRKPEl2CGAzjyGYf97nPXZRGKfSIW5aZPFhN4Z0zlflnJkK4fJc1OyjPkv0NToa4tvk/weFSycdncSxyoWpO+04JVMkFtDy3lQ7WyQVIyTW1guwV6QtC1wQABDZaEFexPaXbfErGV+EZVPgGpfUxGXtmgnW/y0WH9htMQIFsybZZDVghGqjZZtBCDa5MTu018s2aJ6ZCJ2TW1rfUph2SWFMPh3frSQ9zhY9KFMJDo/gKRipc3)

### What is expected?

`lazy-BUetEruU.js` is not output because it is not used in `root.js`.

### What is actually happening?

`lazy-BUetEruU.js` is output.

### System Info

```Shell
REPL 1.0.0-rc.15
```

### Any additional comments?

If you set `output.minify: false`, you can see that the dynamic import is still there. This means the dynamic import is removed in the minification step.

Originally reported at https://github.com/vitejs/vite/issues/21968

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
## Summary
- Treat property reads on ES module namespace objects (`import * as ns`) as side-effect-free, since namespace objects are frozen/sealed by spec with no getters
- Track namespace import symbols in the AST scanner and pass them to the `SideEffectDetector`
- This allows tree-shaking of unused exports whose initializers reference namespace member expressions (e.g. `ns.foo`), preventing unnecessary dynamic chunks from being emitted

## Limitation

This optimization only applies to **direct** (one-level) namespace member access — e.g. `ns.foo` — not deeper chains like `ns.foo.bar`.

For `ns.foo.bar`, the outer `.bar` access has `ns.foo` (a member expression) as its object, not the namespace identifier directly, so it won't be recognized as a namespace access. While `ns.foo` itself is side-effect-free, the value it returns could be any object with getters, so treating `ns.foo.bar` as side-effect-free would require knowing the type of the resolved export.

Supporting deeper chains would require re-analyzing side effects after the `bind_imports_and_exports` phase, where member expressions are resolved to their target symbols through the module graph. This would add a second side-effect analysis pass, which has performance implications. The current single-level approach covers the most common patterns (like the reported issue) without requiring this additional pass.

Closes #9061

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#9099** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9099?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/9099?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=9099).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by IWANABETHATGUY** [comment]
@sapphi-red Is this pr enough for now? It’s a trade-off between peak performance and problem-solving efficiency, see `Limitation` section for more details about the reason.

**Comment by sapphi-red** [comment]
Yes, I think it's enough for now.

**Review by h-a-n-a — APPROVED** [review]

File: packages/rolldown/tests/fixtures/issues/9061/_config.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+export default defineTest({
+  config: {
+    input: './main.js',
+    transform: {
+      define: {
+        'process.env.NODE_ENV': '"production"',
+      },
+    },
+  },
+  afterTest(output) {
```
Comment (hyf0) [inline packages/rolldown/tests/fixtures/issues/9061/_config.ts:13]: Feel like rust test is enough?

**Review by hyf0 — APPROVED** [review]

File: packages/rolldown/tests/fixtures/issues/9061/_config.ts (hunk 1 above)
Comment (IWANABETHATGUY) [reply packages/rolldown/tests/fixtures/issues/9061/_config.ts:13]: This test case needs to ensure that only one entry chunk is generated and that the lazy chunk(the dynamic chunk) is eliminated.

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Apr 14, 6:16 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Apr 14, 6:16 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Apr 14, 6:23 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
