### PR TITLE
fix: should not set default value for treeshake in cli normalization

### LINKED ISSUE #3392: [Bug]: `treeshake.moduleSideEffects` array does not work anymore
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-nci4o6nk-icging8o?file=rolldown.config.mjs
2. `npm i` runs automatically
3. `npm run build` runs automatically
4. See `dist/index.js`.

### What is expected?

`dist/index.js` is empty.

### What is actually happening?

`dist/index.js` is not empty.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: 1.0.0-beta.2-commit.f069c5d => 1.0.0-beta.2-commit.f069c5d
```

### Any additional comments?

It happens with `1.0.0-beta.1-commit.14867ce` and does not happen with `1.0.0-beta.1-commit.c170008` so something between that broke it: https://github.com/rolldown/rolldown/compare/c170008ce20773988958630a9ee312337d6e15d6...14867ce9fdde0ec50692c4c2d77f0072ebce1018

I found this when I tried bundling Vite itself with Rolldown.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Close #3392

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#3398** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3398?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3398?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/src/utils/validator.ts [hunk 1]
```diff
@@ -256,7 +256,7 @@ const InputCliOverrideSchema = v.strictObject({
     v.description('Inject import statements on demand'),
   ),
   treeshake: v.pipe(
-    v.optional(v.boolean(), true),
+    v.optional(v.boolean()),
```
Comment (IWANABETHATGUY) [inline packages/rolldown/src/utils/validator.ts:259]: If we give `treeshake` a default value, in https://github.com/rolldown/rolldown/blob/83cd091b5ab95b4d949564330e8b59fc3260c89c/packages/rolldown/src/cli/commands/bundle.ts?plain=1#L144, `treeshake` will always be set to `true`, regardless of whether the user sets `treeshake` in the config file.

Comment (IWANABETHATGUY) [reply packages/rolldown/src/utils/validator.ts:259]: @shulaoda, I'm not sure if the default value is useful in other situations. Can you help me double-check it?

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
Since this is a high priority issue, let's merge it first and wait for @shulaoda's feedback

File: packages/rolldown/src/utils/validator.ts (hunk 1 above)
Comment (shulaoda) [reply packages/rolldown/src/utils/validator.ts:259]: It doesn't have a special purpose, we can remove it.

Comment (IWANABETHATGUY) [reply packages/rolldown/src/utils/validator.ts:259]: > It doesn't have a special purpose, we can remove it.

got it.
