### PR TITLE
test: add testcase for #6880 and #6879

### LINKED ISSUE #6879: [Bug]: "use strict" is not injected even if it is written in the entryfile
### Reproduction link or steps

https://repl.rolldown.rs/#eNptjkEKwzAMBL8idPEl+AEu/YkvwbFLiisFW24DwX+v0tDSQy5adiVmtWFCt+FMU1xtuNfdELq/YMCg3mOrEaqUOYjHiydPcV24SLWJGa5gVIwnPY/opLTYByyc88QvsoEpzTcrP/zJ5ug5oDDFNLYssPniCYCbLE3c1wIkLo9RA6MfmiPsu3wGdu1+KiyPEqtgfwNltE1r

### What is expected?

The output to be
```js
"use strict";
//#region index.cjs
exports.foo = "foo";

//#endregion
```

### What is actually happening?

The output is:
```js

//#region index.cjs
exports.foo = "foo";

//#endregion
```

### System Info

```Shell
REPL 1.0.0-beta.47
```

### Any additional comments?

The expected behavior is to be aligned with esbuild (https://github.com/rolldown/rolldown/pull/4557). esbuild appends `use strict` for the same input ([esbuild try](https://esbuild.github.io/try/#YgAwLjI1LjEyAC0tYnVuZGxlIC0tZm9ybWF0PWNqcwBlAGVudHJ5LmNqcwAidXNlIHN0cmljdCI7CmV4cG9ydHMuZm9vID0gJ2Zvbyc)).

But I wonder if it's more easier to understand if we add [`output.strict` option](https://rollupjs.org/configuration-options/#output-strict) (and have it `true` by default). 

related: https://github.com/rolldown/rolldown/issues/5865

### LINKED ISSUE #6880: [Bug]: "use strict" in a function is stripped
### Reproduction link or steps

https://repl.rolldown.rs/#eNptjtEKwjAMRX8l5KUKYx8w8E/2UrpWKjUZbaqD0X83VZQ9+JJwbsK9d8eA046RFr+N7lY6EE4HYUCn7LeVs5QxMMMFQiUnkQns6Qz7TACmFg9FcnRiOmcvNRMY/VduM6mPx0ly9W3AzCkt/KTRMYV4HeWX++dyLACLD7Ym0dDcY7jKWmX6IkDgfLcqGK1uPmLr6z2wafZDzZIVXwTbC0ipVdw=

### What is expected?

The output to be:
```js

//#region index.cjs
exports.foo = function a() {
	"use strict";
	return "foo";
};

//#endregion
```

### What is actually happening?

The output is:
```js

//#region index.cjs
exports.foo = function a() {
	return "foo";
};

//#endregion
```

### System Info

```Shell
1.0.0-beta.47
```

### Any additional comments?

Maybe related to https://github.com/rolldown/rolldown/issues/6879

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #6880, closed #6879

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7107** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7107?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7107?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7107).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/tests/rolldown/issues/6880/main.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+exports.foo = function a() {
```
Comment (hyf0) [inline crates/rolldown/tests/rolldown/issues/6880/main.js:2]: Is it possible to use `toString` to add an assertion here? Just curious, I remember toString could return the source code.

Comment (IWANABETHATGUY) [reply crates/rolldown/tests/rolldown/issues/6880/main.js:2]: done

Comment (hyf0) [reply crates/rolldown/tests/rolldown/issues/6880/main.js:2]: That's clever!
