### PR TITLE
fix(rust): avoid panic when `assetFileNames` hash length exceeds `22`

### LINKED ISSUE #4016: [Bug]: an asset file name with [hash:23] panics rolldown
### Reproduction link or steps

Set `output.assetFileNames` to `"[hash:23].[ext]"`

### What is expected?

Based on the unit tests and behaviors I could find `output.chunkFileNames` will limit the hash length to 21 characters even if requesting more. While for assets, you can request 22 and get 22, a behavior that's possibly even more buggy than the panic.

### What is actually happening?

For `[hash:22]`, a 22-character hash is created (which is not possible for chunk filenames). For `[hash:23]` rolldown panics:

```
thread '<unnamed>' panicked at crates/rolldown_common/src/file_emitter.rs:190:40:
byte index 23 is out of bounds of `BKe-RU-cO4wpXAsrT9DUL7`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 772515008
error: script "build" was terminated by signal SIGABRT (Abort)
Aborted
```

### System Info

```Shell
System:
    OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) arm64 unknown
    Memory: 26.79 GB / 31.29 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.19.0 - /usr/local/share/nvm/versions/node/v20.19.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/local/share/nvm/versions/node/v20.19.0/bin/npm
    pnpm: 10.7.0 - /usr/local/share/nvm/versions/node/v20.19.0/bin/pnpm
    bun: 1.2.6 - /usr/local/bin/bun
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
### Description

closes #4016 

I will improve the related test cases based on https://github.com/rolldown/rolldown/pull/3761 in a follow-up.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Please add a test case

File: crates/rolldown_common/src/file_emitter.rs [hunk 1]
```diff
@@ -187,7 +187,7 @@ impl FileEmitter {
       let mut filename = filename_template.render(
         name,
         Some(extension.unwrap_or_default()),
-        Some(|len: Option<usize>| &hash[..len.unwrap_or(8)]),
+        Some(|len: Option<usize>| &hash[..len.map_or(8, |len| len.min(21))]),
```
Comment (IWANABETHATGUY) [inline crates/rolldown_common/src/file_emitter.rs:190]: rollup set the minimum length as `22`

Comment (shulaoda) [reply crates/rolldown_common/src/file_emitter.rs:190]: Related to https://github.com/rollup/rollup/issues/5720, https://github.com/rolldown/rolldown/pull/2740

This limitation exists because we ported `Rollup`’s `xxhash` logic, and we are aligning with the latest `Rollup` behavior.

Comment (shulaoda) [reply crates/rolldown_common/src/file_emitter.rs:190]: Since `assetFileNames` is also generated using `xxhash_with_base`, it inherits the same limitation.

Comment (IWANABETHATGUY) [reply crates/rolldown_common/src/file_emitter.rs:190]: https://stackblitz.com/edit/github-xwippssu-vnppmf3n?file=src%2Fentry.js, rollup still generate 22 hash char when set `[hash:23]`

Comment (shulaoda) [reply crates/rolldown_common/src/file_emitter.rs:190]: Okay. The `assetFileNames` in `rollup` is generated on the `node` side, so it doesn't use the new `xxxhash` function implemented in `rust`, and therefore doesn't encounter this issue.

Comment (shulaoda) [reply crates/rolldown_common/src/file_emitter.rs:190]: However, since we are using the `xxxhash`, the issue does exist on our side. Should we consider enforcing consistency?

Comment (IWANABETHATGUY) [reply crates/rolldown_common/src/file_emitter.rs:190]: I think it is ok to merge this first. Please open another issue to track it, and discuss it next week.

**Review by IWANABETHATGUY — APPROVED** [review]
