### PR TITLE
fix: dataurl plugin resolve panic

### LINKED ISSUE #3821: [Bug]: base64 data url triggers "invalid utf-8 sequence of 1 bytes from index 60" in css
### Reproduction link or steps

Save following css code as `index.css` and then run `npx rolldown index.css`:

```css
@font-face {
    font-family: "swiper-icons";
    src: url("data:application/font-woff;charset=utf-8;base64, d09GRgABAAAAAAZgABAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAAGRAAAABoAAAAci6qHkUdERUYAAAWgAAAAIwAAACQAYABXR1BPUwAABhQAAAAuAAAANuAY7+xHU1VCAAAFxAAAAFAAAABm2fPczU9TLzIAAAHcAAAASgAAAGBP9V5RY21hcAAAAkQAAACIAAABYt6F0cBjdnQgAAACzAAAAAQAAAAEABEBRGdhc3AAAAWYAAAACAAAAAj//wADZ2x5ZgAAAywAAADMAAAD2MHtryVoZWFkAAABbAAAADAAAAA2E2+eoWhoZWEAAAGcAAAAHwAAACQC9gDzaG10eAAAAigAAAAZAAAArgJkABFsb2NhAAAC0AAAAFoAAABaFQAUGG1heHAAAAG8AAAAHwAAACAAcABAbmFtZQAAA/gAAAE5AAACXvFdBwlwb3N0AAAFNAAAAGIAAACE5s74hXjaY2BkYGAAYpf5Hu/j+W2+MnAzMYDAzaX6QjD6/4//Bxj5GA8AuRwMYGkAPywL13jaY2BkYGA88P8Agx4j+/8fQDYfA1AEBWgDAIB2BOoAeNpjYGRgYNBh4GdgYgABEMnIABJzYNADCQAACWgAsQB42mNgYfzCOIGBlYGB0YcxjYGBwR1Kf2WQZGhhYGBiYGVmgAFGBiQQkOaawtDAoMBQxXjg/wEGPcYDDA4wNUA2CCgwsAAAO4EL6gAAeNpj2M0gyAACqxgGNWBkZ2D4/wMA+xkDdgAAAHjaY2BgYGaAYBkGRgYQiAHyGMF8FgYHIM3DwMHABGQrMOgyWDLEM1T9/w8UBfEMgLzE////P/5//f/V/xv+r4eaAAeMbAxwIUYmIMHEgKYAYjUcsDAwsLKxc3BycfPw8jEQA/gZBASFhEVExcQlJKWkZWTl5BUUlZRVVNXUNTQZBgMAAMR+E+gAEQFEAAAAKgAqACoANAA+AEgAUgBcAGYAcAB6AIQAjgCYAKIArAC2AMAAygDUAN4A6ADyAPwBBgEQARoBJAEuATgBQgFMAVYBYAFqAXQBfgGIAZIBnAGmAbIBzgHsAAB42u2NMQ6CUAyGW568x9AneYYgm4MJbhKFaExIOAVX8ApewSt4Bic4AfeAid3VOBixDxfPYEza5O+Xfi04YADggiUIULCuEJK8VhO4bSvpdnktHI5QCYtdi2sl8ZnXaHlqUrNKzdKcT8cjlq+rwZSvIVczNiezsfnP/uznmfPFBNODM2K7MTQ45YEAZqGP81AmGGcF3iPqOop0r1SPTaTbVkfUe4HXj97wYE+yNwWYxwWu4v1ugWHgo3S1XdZEVqWM7ET0cfnLGxWfkgR42o2PvWrDMBSFj/IHLaF0zKjRgdiVMwScNRAoWUoH78Y2icB/yIY09An6AH2Bdu/UB+yxopYshQiEvnvu0dURgDt8QeC8PDw7Fpji3fEA4z/PEJ6YOB5hKh4dj3EvXhxPqH/SKUY3rJ7srZ4FZnh1PMAtPhwP6fl2PMJMPDgeQ4rY8YT6Gzao0eAEA409DuggmTnFnOcSCiEiLMgxCiTI6Cq5DZUd3Qmp10vO0LaLTd2cjN4fOumlc7lUYbSQcZFkutRG7g6JKZKy0RmdLY680CDnEJ+UMkpFFe1RN7nxdVpXrC4aTtnaurOnYercZg2YVmLN/d/gczfEimrE/fs/bOuq29Zmn8tloORaXgZgGa78yO9/cnXm2BpaGvq25Dv9S4E9+5SIc9PqupJKhYFSSl47+Qcr1mYNAAAAeNptw0cKwkAAAMDZJA8Q7OUJvkLsPfZ6zFVERPy8qHh2YER+3i/BP83vIBLLySsoKimrqKqpa2hp6+jq6RsYGhmbmJqZSy0sraxtbO3sHRydnEMU4uR6yx7JJXveP7WrDycAAAAAAAH//wACeNpjYGRgYOABYhkgZgJCZgZNBkYGLQZtIJsFLMYAAAw3ALgAeNolizEKgDAQBCchRbC2sFER0YD6qVQiBCv/H9ezGI6Z5XBAw8CBK/m5iQQVauVbXLnOrMZv2oLdKFa8Pjuru2hJzGabmOSLzNMzvutpB3N42mNgZGBg4GKQYzBhYMxJLMlj4GBgAYow/P/PAJJhLM6sSoWKfWCAAwDAjgbRAAB42mNgYGBkAIIbCZo5IPrmUn0hGA0AO8EFTQAA")
        format("woff");
}
```

### What is expected?

No error

### What is actually happening?

Error: [UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
invalid utf-8 sequence of 1 bytes from index 60

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Memory: 3.39 GB / 15.64 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE 
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD 
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD    
    pnpm: 9.15.4 - C:\Program Files\nodejs\pnpm.CMD  
    bun: 1.1.26 - ~\AppData\Roaming\npm\bun.CMD      
  Browsers:
    Edge: Chromium (131.0.2903.99)
  npmPackages:
    rolldown: ^1.0.0-beta.4 => 1.0.0-beta.4
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed https://github.com/rolldown/rolldown/issues/3821

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#3822** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3822?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3822?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_plugin_data_url/src/data_url_plugin.rs [hunk 1]
```diff
@@ -37,7 +37,8 @@ impl Plugin for DataUrlPlugin {
           return Ok(None);
         };
         let decoded_data = if parsed.is_base64 {
-          String::from_utf8(base64_simd::STANDARD.decode_to_vec(parsed.data)?)?
```
Comment (hyf0) [inline crates/rolldown_plugin_data_url/src/data_url_plugin.rs:40]: Would it be a problem of decoding? Is it expected to generate invalid utf8 character?

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown_plugin_data_url/src/data_url_plugin.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown_plugin_data_url/src/data_url_plugin.rs:40]: Let me see how other bundle behave.

Comment (IWANABETHATGUY) [reply crates/rolldown_plugin_data_url/src/data_url_plugin.rs:40]: We just generate almost identical css as esbulid, 
image
except esbuild has a prefix `\`, but webpack did not have the prefix `\`.

Comment (IWANABETHATGUY) [reply crates/rolldown_plugin_data_url/src/data_url_plugin.rs:40]: rolldown generate the same dataurl string as webpack, so I think it's fine.

Comment (IWANABETHATGUY) [reply crates/rolldown_plugin_data_url/src/data_url_plugin.rs:40]: As the function doc said, it returned `bytes` and did not ensure it was a valid `Utf8` string.
image
