### PR TITLE
fix: strip path for require identifier with `preserveModules`

### LINKED ISSUE #4700: [Bug]: strip path for require identifier with `preserveModules`
### Reproduction link or steps

https://stackblitz.com/edit/github-tsmem1ox?file=rolldown.config.mjs

### What is expected?

```js
const require__child = require('./child.js');

//#region src/entry.js
require__child.childFn();

//#endregion
```

### What is actually happening?

used full path `require__home_projects_github_tsmem1ox_src_child` in `dist/entry.js`.
```js
const require__home_projects_github_tsmem1ox_src_child = require('./child.js');

//#region src/entry.js
require__home_projects_github_tsmem1ox_src_child.childFn();

//#endregion
```

### System Info

```Shell
N/A
```

### Any additional comments?

Downstream: https://github.com/rolldown/tsdown/issues/267

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed #4700

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4704** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4704?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4704?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by hyf0 — APPROVED** [review]
Could you make a meaningful title?

File: crates/rolldown/src/ast_scanner/mod.rs [hunk 1]
```diff
@@ -458,7 +458,8 @@ impl<'me, 'ast: 'me> AstScanner<'me, 'ast> {
       let importee_repr = self.result.import_records[record_id]
         .module_request
         .as_path()
-        .representative_file_name(false);
+        .representative_file_name(false)
```
Comment (hyf0) [inline crates/rolldown/src/ast_scanner/mod.rs]: I want to suggest to have a specific function just for the feature `preserveModules`.

The old `representative_file_name` doesn't affect the runtime correctness while it does now.
