### PR TITLE
fix: set ExportsKind to Esm when json is none object literal 

### LINKED ISSUE #7804: When `unbundle` and `cjs format`, JSON file had imported by ESM which was lost export
### stackblitz
https://stackblitz.com/github/Gehbt/250107-tsdown-bug-repo

### github
https://github.com/Gehbt/250107-tsdown-bug-repo

## steps 
1. run `pnpm run build`
2. run `pnpm run start`

Output have Assertion fail.

### What is expected?

run `npm run node.start`, there were no Assertion fail.

### What is actually happening?

`dist/data.js` has no export syntax. So that  `undefined` be imported

### Any additional comments?

On `bundle mode` or `format esm` is fine.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #7804

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7808** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7808?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7808?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7808).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/generate_lazy_export.rs [hunk 1]
```diff
@@ -86,6 +86,12 @@ impl LinkStage<'_> {
         };
         *stmt = snippet.export_default_expr_stmt(expr);
       });
+
+      // Ensure exports_kind is set to Esm for all modules that generate ESM export syntax.
+      // This is needed for proper CJS export rendering in preserveModules mode.
+      let module = &mut self.module_table[module_idx];
+      let module = module.as_normal_mut().unwrap();
+      module.exports_kind = ExportsKind::Esm;
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/link_stage/generate_lazy_export.rs:94]: For object expr, the module exports kind is set at https://github.com/rolldown/rolldown/blob/80ec93500d477bf9fcd81243d2545d65be76dbd9/crates/rolldown/src/stages/link_stage/generate_lazy_export.rs#L265

**Review by shulaoda — APPROVED** [review]
