### PR TITLE
fix: pad `encode_hash_with_base` output to fixed length to prevent slice panics

### LINKED ISSUE #8270: [Panic]: byte index 21 is out of bounds of `AQZUku11Kfs-GgIXiQXV`
### Panic message

```Shell
Rolldown panicked. This is a bug in Rolldown, not your code.

thread 'tokio-runtime-worker' (4853) panicked at /home/runner/work/rolldown/rolldown/crates/rolldown/src/utils/chunk/finalize_chunks.rs:117:74:
byte index 21 is out of bounds of `AQZUku11Kfs-GgIXiQXV`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction

I've previously reported very similar bugs (#4016, #4017) and this crash is haunting me once more. I believe it's due to base64 encoding not always giving us 21 characters. I think the math checks out to: 75% of the time we get 22 characters, 24.6% of the time we get 21 characters, and 0.4% of the time we get 20 characters (hence a crash if we request 21).

The fix could be something like this:

```diff
diff --git a/crates/rolldown_utils/src/xxhash.rs b/crates/rolldown_utils/src/xxhash.rs
--- a/crates/rolldown_utils/src/xxhash.rs
+++ b/crates/rolldown_utils/src/xxhash.rs
@@ -18,12 +18,25 @@ pub fn xxhash_with_base(input: &[u8], base: u8) -> String {
   let hash = if input.len() == 16 { input } else { &xxh3_128(input).to_le_bytes() };

   let chars = match base {
     64 => CHARACTERS_BASE64,
     36 => &CHARACTERS_BASE64[26..(26 + 36)],
     16 => CHARACTERS_BASE16,
     _ => {
       unreachable!()
     }
   };

-  to_string(hash, base, chars).unwrap()
+  let mut result = to_string(hash, base, chars).unwrap();
+  // `base_encode::to_string` produces variable-length output like decimal
+  // (no leading-zero padding). Left-pad with the zero-digit to the maximum
+  // length for a 128-bit value so that `&hash[..placeholder.len()]` in
+  // finalize_chunks.rs never panics on a shorter-than-expected string.
+  let max_len = match base {
+    64 => 22, // ceil(128 / log2(64))
+    36 => 25, // ceil(128 / log2(36))
+    16 => 32, // 128 / 4
+    _ => unreachable!(),
+  };
+  while result.len() < max_len {
+    result.insert(0, chars[0] as char);
+  }
+  result
 }

 #[test]
 fn test_xxhash_with_base() {
-  assert_eq!(&xxhash_with_base(b"hello", 64), "YOFJeqs95x38-Gwetwem1");
+  assert_eq!(&xxhash_with_base(b"hello", 64), "AYOFJeqs95x38-Gwetwem1");
   assert_eq!(&xxhash_with_base(b"hello", 36), "bpwli5k6mqm0gij09mxrh9npj");
   assert_eq!(&xxhash_with_base(b"hello", 16), "1838525eaacf79c77f3e1b07adc1e9b5");
 }
```

But I'm sure there are more performant ways to do it.

### System Info

```Shell
System:
    OS: macOS 26.3
    CPU: (16) arm64 Apple M3 Max
    Memory: 52.42 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.22.0 - /Users/blixt/.local/share/mise/installs/node/22.22.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.4 - /Users/blixt/.local/share/mise/installs/node/22.22.0/bin/npm
    pnpm: 10.28.1 - /Users/blixt/.local/share/mise/installs/node/22.22.0/bin/pnpm
    bun: 1.2.23 - /Users/blixt/.bun/bin/bun
    Deno: 2.6.8 - /opt/homebrew/bin/deno
  Browsers:
    Safari: 26.3
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
closes #8270, related to rollup/rollup#5720

### Summary

`base_encode::to_string` performs a true mathematical base conversion (repeated division), which produces **variable-length output** depending on the numeric magnitude of the input. For a 128-bit xxhash encoded in base 64, the output is typically 21 or 22 characters (~75% chance of 22, ~25% chance of 21), and can be shorter (~0.4% chance) if the least-significant bytes of the hash happen to be zero.

This caused two issues:

1. **Potential panic**: Callers slice the hash at fixed offsets (e.g. `hash[..placeholder.len()]`), which panics if the hash string is shorter than expected.
2. **Incorrect `MAX_HASH_SIZE`**: It was set to 21, but the actual maximum for base 64 is `ceil(128/6) = 22`, preventing users from using `[hash:22]`.

### Additional

For the xxhash use case, the 128-bit hash output is approximately uniformly random. Having 13+ leading zero bytes would require a probability of   `1/256¹³ ≈ 10⁻³¹`, which is practically impossible. In practice, the output is almost always 21 characters (~75%) or 22 characters (~25%), with   an occasional 20 characters (~0.4%).

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#8320** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8320?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8320?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#8319** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8319?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8320).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by shulaoda** [comment]
I’ll submit a PR to Rollup later.

File: crates/rolldown_utils/src/xxhash.rs [hunk 1]
```diff
@@ -31,7 +35,22 @@ pub fn encode_hash_with_base(hash: &[u8; 16], base: u8) -> String {
...
+
+  let result = to_string(hash, base, chars).unwrap();
+
+  // Left-pad with the zero character to ensure the output is at least 21 chars
+  // (MAX_HASH_SIZE). `base_encode::to_string` produces variable-length output
+  // depending on the numeric magnitude, which can cause panics when callers
+  // slice the result at a fixed offset (e.g. `hash[..placeholder.len()]`).
+  let pad_len = 21usize.saturating_sub(result.len());
+  if pad_len > 0 {
+    let mut padded = String::with_capacity(pad_len + result.len());
```
Comment (IWANABETHATGUY) [inline crates/rolldown_utils/src/xxhash.rs]: I think we could just use `21` here, or use a constant variable.

**Review by hyf0 — APPROVED** [review]

**Comment by shulaoda** [comment]
### Merge activity

* **Feb 13, 12:32 PM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Feb 13, 12:35 PM UTC**: `shulaoda` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Feb 13, 12:47 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
