### PR TITLE
fix: Panic with "jsx": "preserve" when rewrite a `memberExpression`

### LINKED ISSUE #6036: [Bug]: Panic with `"jsx": "preserve"`
### Reproduction link or steps

https://github.com/issueset/rolldown-issue-6036

```bash
$ git clone https://github.com/issueset/rolldown-issue-6036
$ cd rolldown-issue-6036
$ pnpm install 
$ pnpm run build:rolldown
```

### What is expected?

No error occurs, like what esbuild does:

```bash
$ pnpm run build:esbuild

> 5@1.0.0 build:esbuild /private/tmp/5
> esbuild src/index.ts --bundle --tsconfig=tsconfig.json --outdir=dist/esbuild


  dist/esbuild/index.js  46.1kb

⚡ Done in 17ms
```

_OR_, if `"jsx": "preserve"` in `tsconfig.json` is something not supported by `rolldown`, a friendly error message for users.

### What is actually happening?

Panic error

```bash
$ pnpm run build:rolldown

> 5@1.0.0 build:rolldown /private/tmp/5
> rolldown -c rolldown.config.ts


thread '<unnamed>' panicked at crates/rolldown/src/module_finalizers/impl_visit_mut.rs:506:17:
internal error: entered unreachable code: Should always rewrite to Identifier for JsxMemberExpression::get_identifier()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 ERROR  internal error: entered unreachable code: Should always rewrite to Identifier for JsxMemberExpression::get_identifier()
```

### System Info

```Shell
System:
    OS: macOS 15.6.1
    CPU: (8) arm64 Apple M2
    Memory: 167.27 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.3 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 10.11.0 - /opt/homebrew/bin/pnpm
    bun: 1.2.15 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 140.0.7339.81
    Safari: 18.6
    Safari Technology Preview: 26.0
  npmPackages:
    rolldown: 1.0.0-beta.35 => 1.0.0-beta.35
```

### Any additional comments?

If I comment out `"jsx": "preserve"` in `tsconfig.json`, then the error goes away.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
This pr only ensures bundle `jsx`​ successfully when it meets `MemberExpression` rewrite, the rest part I will do in another pr after `StaticCommonjsPropAccess` optimization, which will rewrite commonjs prop access like, 

```js
var import_react = /* @__PURE__ */ __toESM(require_react());
const import_react_default = import_react.default.
function Hello() {
	return <import_react_default.Fragment>
      <h1>Hello</h1>
    </import_react_default.Fragment>;
}

```

After the optimization, we could just capitalize the binding if it is used as `JSXElement`

Almost fixed #6036()， since the issue only required build without panic

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6192** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6192?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6192?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6192).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/tests/rolldown/issues/6036/react.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+module.exports = {}
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/issues/6036/react.ts:1]: simulate react cjs wrapped kind

File: crates/rolldown_ecmascript_utils/src/extensions/ast_ext/jsx.rs [hunk 2]
```diff
@@ -21,4 +31,45 @@ impl<'ast> JsxExt<'ast> for JSXMemberExpressionObject<'ast> {
...
+      Expression::ThisExpression(expr) => Some(JSXMemberExpressionObject::ThisExpression(expr)),
+      _ => None,
+    }
+  }
+}
+
+impl<'ast> JsxExt<'ast> for JSXMemberExpression<'ast> {
+  type AstKind = StaticMemberExpression<'ast>;
+  fn rewrite_ident_reference(&mut self, _ident_ref: JSXMemberExpressionObject<'ast>) {
+    todo!()
```
Comment (IWANABETHATGUY) [inline crates/rolldown_ecmascript_utils/src/extensions/ast_ext/jsx.rs:56]: Only `JSXMemberExpressionObject` needs to rewrite first `ident_reference`

**Review by shulaoda — APPROVED** [review]
