### PR TITLE
fix: auto polyfill import.meta.* in none esm format

### LINKED ISSUE #3413: [Bug]: `import.meta` included in `.cjs` file
### Reproduction link or steps

Image

### What is expected?

`import.meta.env` is polyfilled.

### What is actually happening?

If I run node directly on this file: `SyntaxError: Cannot use 'import.meta' outside a module`.

### System Info

```Shell
1.0.0-beta.3
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed https://github.com/rolldown/rolldown/issues/3413

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#3454** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3454?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3454?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3439** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/3439?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/normalize_options.rs [hunk 1]
```diff
@@ -65,6 +65,27 @@ pub fn normalize_options(mut raw_options: crate::BundlerOptions) -> NormalizeOpt
     }
   }
 
+  // replace all `import.meta.*` with `undefined` for none `esm` format
+  // note: Any definition more specific than `import.meta.*` will be replace first
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/normalize_options.rs:69]: ref: https://rollupjs.org/repl/?version=4.32.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnNvbGUubG9nKGltcG9ydC5tZXRhLnRlc3QpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHF1eCUyMCUzRCUyMCdRVVgnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnF1eC5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJzeXN0ZW0lMjIlN0QlN0QlN0Q=

File: crates/rolldown/src/utils/normalize_options.rs [hunk 2]
```diff
@@ -65,6 +65,27 @@ pub fn normalize_options(mut raw_options: crate::BundlerOptions) -> NormalizeOpt
...
+  if !matches!(format, OutputFormat::Esm) {
+    match raw_define.entry("import.meta.*".to_string()) {
```
Comment (hyf0) [inline crates/rolldown/src/utils/normalize_options.rs:71]: Cool. Just realize that oxc supports `*` pattern.

**Review by hyf0 — APPROVED** [review]
