### PR TITLE
fix: NormalizedOutputOptions option

### LINKED ISSUE #3445: [Feature]: Support passing `NormalizedOutputOptions#assetFilenames` with function
### Reproduction link or steps

1. `pnpx nuxi@latest init nuxt`
2. Override Vite to Rolldown Vite
3. `pnpm build`

### What is expected?

Build successfully

### What is actually happening?

Error:
```
[plugin ssr-styles]
Error: UNSUPPORTED: You should not take NormalizedOutputOptions#assetFilenames and call it directly
```

Nuxt ssr-styles plugin code:
```js
const base = typeof outputOptions.assetFileNames === 'string'
  ? outputOptions.assetFileNames
  : outputOptions.assetFileNames({
      type: 'asset',
      name: `${fileName}-styles.mjs`,
      names: [`${fileName}-styles.mjs`],
      originalFileName: `${fileName}-styles.mjs`,
      originalFileNames: [`${fileName}-styles.mjs`],
      source: '',
    })
```

### System Info

```Shell
vite: https://pkg.pr.new/rolldown/vite@c7224b3
rolldown: 1.0.0-beta.3-commit.bc5b1e7
```

### Any additional comments?

```
assetFileNames: nuxt.options.dev ? undefined : (chunk) => withoutLeadingSlash(join(nuxt.options.app.buildAssetsDir, `${sanitizeFilePath(filename$1(chunk.name))}.[hash].[ext]`))
```
to
```
assetFileNames: nuxt.options.dev ? undefined : (chunk) => withoutLeadingSlash(join(nuxt.options.app.buildAssetsDir, `${sanitizeFilePath(filename$1(chunk.names[0]))}.[hash].[ext]`))
```

Should replace code before build for fix `Cannot read properties of undefined (reading 'split')` error.

### PR DESCRIPTION
**Pull request by underfin**
### Description
including  filenames/addons/plugins/sourcemapPathTransform/globals options.

close  https://github.com/rolldown/rolldown/issues/3445

### CODE REVIEW

File: packages/rolldown/src/options/normalized-output-options.ts [hunk 1]
```diff
@@ -177,4 +180,15 @@ export class NormalizedOutputOptionsImpl implements NormalizedOutputOptions {
...
+  get plugins(): RolldownPlugin[] {
+    return this.normalizedOutputPlugins
+  }
+}
+
+function normalizeAddon(value?: string | AddonFunction) {
+  if (typeof value === 'function') {
+    return value
+  }
+  return () => value || ''
```
Comment (IWANABETHATGUY) [inline packages/rolldown/src/options/normalized-output-options.ts:193]: The logic operator seems unreachable.

**Review by IWANABETHATGUY — APPROVED** [review]

File: packages/rolldown/src/options/normalized-output-options.ts (hunk 1 above)
Comment (IWANABETHATGUY) [reply packages/rolldown/src/options/normalized-output-options.ts:193]: I misremember the operator precedence,  ignore me.
