### PR TITLE
fix: when preserveEntrySignatures: false is set, output includes a circular import

### LINKED ISSUE #5277: [Bug]: when `preserveEntrySignatures: false` is set, output includes a circular import
### Reproduction link or steps

1. Download https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-uqjtkhzd?file=rolldown.config.mjs locally
2. Link rolldown https://github.com/rolldown/rolldown/tree/1b63cd986c591fed1de8659eb3e16dc30d8203f5 by pnpm overrides
3. `pnpm i`
4. `pnpm build`

### What is expected?

The output doesn't include a circular import.

### What is actually happening?

`dist/router.js` imports `dist/dist-DhhjUhDd.js` and `dist/dist-DhhjUhDd.js` imports `dist/router.js`.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 2.86 GB / 31.92 GB
  Binaries:
    Node: 22.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.12.4 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.2.17 - ~\AppData\Local\Microsoft\WinGet\Links\bun.EXE
  Browsers:
    Edge: Chromium (136.0.3240.92)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    rolldown: link:D:/documents/GitHub/rolldown/packages/rolldown => 1.0.0-beta.27
```

### Any additional comments?

Originally reported at https://github.com/vitejs/rolldown-vite/issues/325
Maybe related to https://github.com/rolldown/rolldown/issues/4976

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #5277

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#5365** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5365?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5365?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
I can't generate a minimum reproduction, so no test added

File: crates/rolldown/src/stages/generate_stage/code_splitting.rs [hunk 1]
```diff
@@ -478,21 +478,22 @@ impl GenerateStage<'_> {
   ) {
     let static_entry_chunk_reference: FxHashMap<ChunkIdx, FxHashSet<ChunkIdx>> =
       self.construct_static_entry_to_reached_dynamic_entries_map(chunk_graph);
+
+    let entry_chunk_idx =
+      chunk_graph.chunk_table.iter_enumerated().map(|(idx, _)| idx).collect::<FxHashSet<_>>();
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/generate_stage/code_splitting.rs:483]: We can't use `chunk_graph.chunk_table.get(*idx)` becuase `chunk_table` is mutated during the loop.

**Comment by IWANABETHATGUY** [comment]
Let's wait @sapphi-red to verify it, I tested it locally and no circular referenced any more.

**Review by sapphi-red — APPROVED** [review]
It worked for me as well 👍
