### PR TITLE
fix(rolldown_binding): use Record instead of Map

### LINKED ISSUE #6705: [Bug]: broken native manifest plugin
https://github.com/rolldown/rolldown/pull/6684 is not working because napi-rs does not support deserializing `Map` into `HashMap`.
https://github.com/napi-rs/napi-rs/blob/3d5f5bf2ce3fcef39086115534bd5debc9371656/crates/napi/src/bindgen_runtime/js_values/map.rs#L55-L73

Note that deserializing `Set` into `HashSet` is supported.
https://github.com/napi-rs/napi-rs/blob/3d5f5bf2ce3fcef39086115534bd5debc9371656/crates/napi/src/bindgen_runtime/js_values/set.rs#L35-L57

This should be fixed before the next release.

### PR DESCRIPTION
**Pull request by shulaoda**
close #6705

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#6715** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6715?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6715).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_binding/src/options/plugin/config/binding_manifest_plugin_config.rs [hunk 1]
```diff
@@ -11,7 +11,7 @@ pub struct BindingManifestPluginConfig {
   pub out_path: String,
   #[napi(ts_type = "() => boolean")]
   pub is_legacy: Option<JsCallback<(), bool>>,
-  #[napi(ts_type = "() => Map<string, string>")]
+  #[napi(ts_type = "() => Record<string, string>")]
```
Comment (sapphi-red) [inline crates/rolldown_binding/src/options/plugin/config/binding_manifest_plugin_config.rs:14]: Do we still need the `ts_type`?
```suggestion
  #[napi]
```

**Review by sapphi-red — APPROVED** [review]

File: crates/rolldown_binding/src/options/plugin/config/binding_manifest_plugin_config.rs (hunk 1 above)
Comment (shulaoda) [reply crates/rolldown_binding/src/options/plugin/config/binding_manifest_plugin_config.rs:14]: Because `napi-rs` doesn't correctly parse `JsCallback`, we need to explicitly annotate the function type here.
