### PR TITLE
fix: should rewrite hmr related ast after test if `experimental.hmr` is enabled.

### LINKED ISSUE #4921: [Bug]: no entry found for key
### Reproduction link or steps

Repo: https://github.com/zaaack/remix-starter/tree/rolldown-issue
Set vite version to `npm:rolldown-vite@6.3.19`
Run `pnpm dev`

### What is expected?

No error

### What is actually happening?

```bash
thread '<unnamed>' panicked at crates\rolldown\src\module_finalizers\hmr.rs:128:47:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Panic in async function] { code: 'GenericFailure' }
```

### System Info

```Shell
-
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #4921

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4972** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4972?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4972?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/hmr.rs [hunk 1]
```diff
@@ -108,6 +108,10 @@ impl<'ast> ScopeHoistingFinalizer<'_, 'ast> {
   }
 
   pub fn rewrite_hot_accept_call_deps(&self, call_expr: &mut ast::CallExpression<'ast>) {
+    if !self.ctx.options.is_hmr_enabled() {
```
Comment (hyf0) [inline crates/rolldown/src/module_finalizers/hmr.rs:111]: Is this the opposite to this PR title? Instead `should`, should it be `shouldn't`?

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/src/module_finalizers/hmr.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/hmr.rs:111]: https://github.com/rolldown/rolldown/blob/72bdeb3a45af3e30f7535efd4be9edfcfcb12066/crates/rolldown/src/ast_scanner/hmr.rs?plain=1#L12-L14

Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/hmr.rs:111]: > Is this the opppisite to this PR title?

I think they just represent the same meaning, since this is early return, align with related code in `ast_scanner`

Comment (IWANABETHATGUY) [reply crates/rolldown/src/module_finalizers/hmr.rs:111]: The title maybe related to personal preference, perhaps I prefer declarative sentences a bit more
