### PR TITLE
fix: handle lexical declarations in root scope

### LINKED ISSUE #6227: [Bug]: variables with same name declared in a block is not deconflicted when `experimental.strictExecutionOrder: true`
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNqNUcFqhDAQ/ZUhF10q7vYqbG+9FXopPe0l1XFJyWYkjqtU/PdOjFYpPRQk+l7ey3tORlWrYlTGVTjkn234dqrYcKbKAG8NeYYkP9ZEQicXt1Ef2kdKxKgK9h1OmfJkbUW9y0tytbnuzv5jJ6bgMB9ZYa07yzBeHIBw6M0NHWtbRAqgZW9Kfh6w7NiQe/UV+gJCcNifsrBSw+ZmvnQQ/BiPR2BqXvCO9l3vLRcnj5La8f/WqgtahlBDGgwHOc0Hl/RvGUQDZ0jklcAD9DI56nNBUdMiv0l96jhND3B+Wr3RTRZzS9dU5IfITxk8nk4zmMISOsUBr50W9J9OIt11ErRpfifHsPkCa21bnCT3LgFWM7aspm/eubZa)

### What is expected?

`barundefined` and `fooundefined` is output when running the bundled output.

In other words, `foo = "foo" + window.foo;` and `foo = "bar" + window.bar;` to be assign to a different variable.

### What is actually happening?

`barundefined` is output twice when running the bundled output.

In other words, `foo = "foo" + window.foo;` and `foo = "bar" + window.bar;` are assign to the same variable.

### System Info

```Shell
REPL 1.0.0-beta.38
```

### Any additional comments?

This was fine in 1.0.0-beta.29 and broken since 1.0.0-beta.30.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed https://github.com/rolldown/rolldown/issues/6227

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#6230** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6230?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6230?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=6230).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_finalizers/impl_visit_mut.rs [hunk 1]
```diff
@@ -34,6 +34,7 @@ impl<'ast> VisitMut<'ast> for ScopeHoistingFinalizer<'_, 'ast> {
       TraverseState::IsTopLevel,
       self.scope_stack.iter().rev().all(|flag| flag.is_block() || flag.is_top()),
     );
+    self.state.set(TraverseState::IsRootLevel, self.scope_stack.iter().all(|flag| flag.is_top()));
```
Comment (sapphi-red) [inline crates/rolldown/src/module_finalizers/impl_visit_mut.rs]:
```suggestion
    self.state.set(TraverseState::IsRootLevel, self.scope_stack.iter().rev().all(|flag| flag.is_top()));
```
Maybe this is slightly performant? Also this aligns with the line above.

File: crates/rolldown/src/module_finalizers/impl_visit_mut.rs [hunk 2]
```diff
@@ -42,6 +43,7 @@ impl<'ast> VisitMut<'ast> for ScopeHoistingFinalizer<'_, 'ast> {
...
```
Comment (sapphi-red) [inline crates/rolldown/src/module_finalizers/impl_visit_mut.rs]:
```suggestion
    self.state.set(TraverseState::IsRootLevel, self.scope_stack.iter().rev().all(|flag| flag.is_top()));
```

**Review by sapphi-red — APPROVED** [review]
