### PR TITLE
fix: avoid panic on untranspiled JSX syntax by reporting a diagnostic error

### LINKED ISSUE #8216: [Bug]: Panic in side_effect_detector: "jsx should be transpiled" when @content-collections/vite plugin triggers SSR dep scan
### Human Note

AI assisted generating this issue over the course of debugging. Did not confirm the analysis section below.

### Potential Repro

The app I have this issue is quite large and not exactly able to get it to repro exactly, but I think this may give some insights.

https://github.com/austinm911/rolldown-jsx-cloudflare-repro

### Rolldown Version

1.0.0-rc.3 (via Vite 8.0.0-beta.13)

### Description

Rolldown panics with `internal error: entered unreachable code: jsx should be transpiled` in `side_effect_detector/mod.rs:659` during dev server startup when the `@content-collections/vite` plugin is active.

The content-collections plugin itself generates **pure JS data files** (no JSX). The panic occurs when Rolldown's SSR dep optimizer scans `.tsx` route files that import from the `content-collections` alias. The side-effect detector encounters JSX AST nodes before any transform plugin has run and hits an `unreachable!()` assertion.

### Reproduction

1. Vite 8.0.0-beta.13 with TanStack Start (React)
2. Add `@content-collections/vite` plugin (order doesn't matter — tested first and last)
3. Have `.tsx` files that `import { ... } from 'content-collections'`
4. Start dev server → panic

Removing the content-collections plugin eliminates the panic. The plugin only:
- Registers an alias (`"content-collections" → .content-collections/generated/`)
- Adds `optimizeDeps.exclude: ["content-collections"]` (client-side only)
- Runs a builder in `configureServer`/`buildStart`

Plugin source: https://github.com/sdorra/content-collections/blob/main/packages/vite/src/index.ts

### Stack Trace

```
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/ast_scanner/side_effect_detector/mod.rs:659:9:
internal error: entered unreachable code: jsx should be transpiled
stack backtrace:
   0: _napi_register_module_v1
   1: _napi_register_module_v1
   ...
  30: __pthread_cond_wait
```

### Analysis

The `unreachable!()` at `side_effect_detector/mod.rs:659` assumes JSX has been transpiled before the AST scanner runs. During SSR dep optimization, Rolldown scans the full import graph including `.tsx` files. Since transform plugins (e.g., `@vitejs/plugin-react`) haven't processed these files yet at scan time, the side-effect detector encounters raw JSX nodes and panics.

The fix should replace the `unreachable!()` with a safe fallback — either:
- Parse JSX natively in the side-effect detector, or
- Conservatively assume side-effectful when JSX is encountered

### Workaround

Disable the `@content-collections/vite` plugin.

### Environment

- **Rolldown**: 1.0.0-rc.3
- **Vite**: 8.0.0-beta.13
- **OS**: macOS arm64
- **Runtime**: Bun 1.3.3
- **Framework**: TanStack Start (React)
- **React plugin**: @vitejs/plugin-react with babel-plugin-react-compiler

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #8216

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#8226** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8226?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8226?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8226).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/tweak_ast_for_scanning.rs [hunk 1]
```diff
@@ -173,13 +173,14 @@ impl<'ast> VisitMut<'ast> for PreProcessor<'ast> {
...
+      | Declaration::ClassDeclaration(_)
+      | Declaration::TSTypeAliasDeclaration(_)
       | Declaration::TSInterfaceDeclaration(_)
       | Declaration::TSEnumDeclaration(_)
       | Declaration::TSModuleDeclaration(_)
       | Declaration::TSImportEqualsDeclaration(_)
-      | Declaration::TSGlobalDeclaration(_) => unreachable!(),
+      | Declaration::TSGlobalDeclaration(_) => {}
     }
     walk_mut::walk_declaration(self, it);
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/tweak_ast_for_scanning.rs:185]: Will emit an error in the later visit pass.

**Review by shulaoda — APPROVED** [review]

File: crates/rolldown/src/ast_scanner/impl_visit.rs [hunk 2]
```diff
@@ -419,6 +427,87 @@ impl<'me, 'ast: 'me> Visit<'ast> for AstScanner<'me, 'ast> {
     walk::walk_expression(self, it);
   }
 
+  // --- Outermost TS visitor overrides ---
+  // Empty bodies prevent the walker from descending into TS subtrees.
+  // We only record the untranspiled syntax flag so the scan stage can report the error.
+
+  fn visit_ts_enum_declaration(&mut self, _it: &ast::TSEnumDeclaration<'ast>) {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/ast_scanner/impl_visit.rs:434]: Update the flag on the visitor directly rather than on the parent node using `match` to avoid unnecessary overhead.
