### PR TITLE
fix: preserve more js plugin hook errors

### LINKED ISSUE #2551: [Bug]: Rolldown does not show the stacktrace when an error happened inside JS plugins
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss?file=package.json,rolldown.config.mjs
2. `npm i` and `npm run build` runs automatically
3. The error is shown

### What is expected?

The following error happens:
```
[!] (plugin foo) Error: throw!
src/entry.js
    at Object.transform (file:///home/projects/xoriwgqxmv.github/rolldown.config.mjs:24:15)
    at eval (/home/.npm/_npx/1ee1cf83ded2a161/node_modules/rollup/dist/shared/rollup.js:1087:40)
    at <anonymous> (https://xoriwgqxmvgithub-1r5y.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:22847)
```

It does not have to be the same. The important points are

- show which plugin failed
- show the stacktrace
- show the processing file when that error happened

### What is actually happening?

The following error happens:
```
[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, Error: throw!

[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, Error: throw!

Error: Build failed
    at napi_create_error (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:4535:25)
    at eval (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1283:58)
    at NodeEnv.callIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:639:19)
    at NodeEnv.callbackIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:758:21)
    at f (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1277:37)
    at Object.dispatchOne (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1305:29)
    at Object.dispatch (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1321:43)
    at Worker.handler (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:864:40) {
  code: 'GenericFailure'
}
```

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@6aa4503 => 0.13.2
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- closes https://github.com/rolldown/rolldown/issues/2551

Let me try this again. It looks like `resolveId` handled by https://github.com/rolldown/rolldown/issues/2551 wasn't actually a main error handling code path. Instead, there is `Vec<BuildDiagnostic>` which needs to be resurfaced back as js errors.

~I couldn't find a way to aggregate multiple error objects back to js side, so for now I'm handling at most single js error, which I think is sufficient for many cases.~

_todo_

- how to handle multiple errors/diagnostics?
  - rollup doesn't have such concept and they can throw only single `RollupError`. Currently Vite's error handling is based on that model (cf. https://github.com/vitejs/vite/pull/16540)
  - esbuild returns each error detail in `Error.errors: types.Message[]`. Additionally they use `Error.message` to include a summary with up-to-5 error messages combined. https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/lib/shared/common.ts#L1673-L1683
  - I did something similar to esbuild.

### CODE REVIEW

File: crates/rolldown_binding/src/bundler.rs [hunk 1]
```diff
@@ -183,12 +183,26 @@ impl Bundler {
...
-        "{}",
-        err.into_diagnostic_with(&DiagnosticOptions { cwd: self.cwd.clone() }).to_color_string()
-      );
-    });
+    // TODO: is it possible to return as an aggregated error back to js side?
+    // it seems difficult since `Env` is not even available in async fn.
+    // for now, we only surface single js error.
+    // https://github.com/napi-rs/napi-rs/issues/1981#issuecomment-1978208322
+    // https://github.com/napi-rs/napi-rs/issues/945
+    for err in errs {
```
Comment (IWANABETHATGUY) [inline crates/rolldown_binding/src/bundler.rs]: I think we could put the napi error at the end of the errs, so we could print as much `diagnostic` as possible, also napi Error usually means something wrong in js side and usually not recoverable, only print one and let user solve them one by one is ok.

**Comment by IWANABETHATGUY** [comment]
LGTM, we could merge it once you are ready

File: crates/rolldown_binding/src/bundler.rs (hunk 1 above)
Comment (hi-ogawa) [reply crates/rolldown_binding/src/bundler.rs]: I just tried a different approach where we can bring back diagnostics on js side via `BindingOutputs.errors` https://github.com/rolldown/rolldown/pull/2759/commits/92e92a81503ae9c654654abd13b95ce8077fa763. In this way, we can bring back native diagnostics to js api as well. For example, this is how syntax error shows up on cli now:

<details>

```sh
$ pnpm -C examples/basic-typescript build

> @example/typescript@ build /home/hiroshi/code/others/rolldown/examples/basic-typescript
> rolldown --config ./rolldown.config.js

file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-kw1CzMnA.mjs:141
                const errors2 = errors.map((e) => e instanceof Error ? e : Object.assign(new Error(), e));
                                                                                         ^

Error: [PARSE_ERROR] Error: Expected a semicolon or an implicit semicolon after a statement, but found none
   ╭─[index.ts:1:7]
   │
 1 │ syntax error import { hello } from './hello'
   │       │ 
   │       ╰─ 
   │ 
   │ Help: Try insert a semicolon here
───╯

    at file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-kw1CzMnA.mjs:141:76
    at Array.map (<anonymous>)
    at transformToRollupOutput (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-kw1CzMnA.mjs:141:26)
    at RolldownBuild.write (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-kw1CzMnA.mjs:2746:10)
    at async bundleInner (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/esm/cli.mjs:393:23) {
  kind: 'PARSE_ERROR'
}
```

</details>

Comment (IWANABETHATGUY) [reply crates/rolldown_binding/src/bundler.rs]: IMO, giving stack trace for a BuildDiagnostic is misleading.

Comment (IWANABETHATGUY) [reply crates/rolldown_binding/src/bundler.rs]: Can you try if there are multiple error scenarios?

Comment (hi-ogawa) [reply crates/rolldown_binding/src/bundler.rs]: > giving stack trace for a BuildDiagnostic is misleading.

Right, that doesn't make sense, but we can probably strip it before rethrowing on js.

> Can you try if there are multiple error scenarios?

I was wondering that scenario, but couldn't think of it. Is there any example already? I also plan to check how rollup and esbuild show multiple errors.

Comment (hi-ogawa) [reply crates/rolldown_binding/src/bundler.rs]: When there are multiple parse errors, it looks like below. Node prints `AggregatedError.errors`, so probably we don't need `eprintln` on rust side. I also stripped stacktrace for native diagnostics. 

<details>

```
$ pnpm -C examples/basic-typescript build

> @example/typescript@ build /home/hiroshi/code/others/rolldown/examples/basic-typescript
> rolldown --config ./rolldown.config.js

file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-AcwZUxfw.mjs:145
                throw new AggregateError(causes, "Build failed");
                      ^

AggregateError: Build failed
    at transformToRollupOutput (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-AcwZUxfw.mjs:145:9)
    at RolldownBuild.write (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-AcwZUxfw.mjs:2746:10)
    at async bundleInner (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/esm/cli.mjs:393:23) {
  [errors]: [
    [Error: [PARSE_ERROR] Error: Unexpected token
       ╭─[hello.ts:1:33]
       │
     1 │ export function hello(): void { :(
       │                                 ┬  
       │                                 ╰── 
    ───╯
    ] {
      kind: 'PARSE_ERROR'
    },
    [Error: [PARSE_ERROR] Error: Expected a semicolon or an implicit semicolon after a statement, but found none
       ╭─[index.ts:1:32]
       │
     1 │ import { hello } from './hello' :(
       │                                │ 
       │                                ╰─ 
       │ 
       │ Help: Try insert a semicolon here
    ───╯
    ] {
      kind: 'PARSE_ERROR'
    }
  ]
}

Node.js v20.18.0
 ELIFECYCLE  Command failed with exit code 1.
```

</details>

**Review by IWANABETHATGUY — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
LGTM, I left others to have a look

File: crates/rolldown_binding/src/bundler.rs (hunk 1 above)
Comment (hi-ogawa) [reply crates/rolldown_binding/src/bundler.rs]: This is a final version of errors on CLI. I used a getter trick from esbuild to avoid expanding `errors` when printed from `console.error`.

```sh
$ pnpm -C examples/basic-typescript build

> @example/typescript@ build /home/hiroshi/code/others/rolldown/examples/basic-typescript
> rolldown --config ./rolldown.config.js

file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-BcFJfRrY.mjs:169
                const wrapper = new Error(summary);
                                ^

Error: Build failed with 2 errors:
[PARSE_ERROR] Error: Invalid Character ` `
   ╭─[index.ts:3:6]
   │
 3 │ foo # bar console.log(hello())
   │      ┬  
   │      ╰── 
───╯

[PARSE_ERROR] Error: Expected a semicolon or an implicit semicolon after a statement, but found none
   ╭─[index.ts:3:4]
   │
 3 │ foo # bar console.log(hello())
   │    │ 
   │    ╰─ 
   │ 
   │ Help: Try insert a semicolon here
───╯


    at handleOutputErrors (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-BcFJfRrY.mjs:169:19)
    at transformToRollupOutput (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-BcFJfRrY.mjs:152:2)
    at RolldownBuild.write (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/shared/src_index-BcFJfRrY.mjs:2786:10)
    at async bundleInner (file:///home/hiroshi/code/others/rolldown/packages/rolldown/dist/esm/cli.mjs:393:23) {
  errors: [Getter/Setter]
}

Node.js v20.18.0
```

**Review by hyf0 — APPROVED** [review]
Cool!
