### PR TITLE
fix: removing unused dynamic imported chunks

### LINKED ISSUE #3998: After removing unused dynamic imported chunks, rolldown outputs different results compared to rollup
I'm investigating #3981. I'm not sure if this is the root cause of #3981 but should be a follow up issue of #2604. @IWANABETHATGUY cc

Image

while rollup only outputs one file.

https://stackblitz.com/edit/github-ifzxqzwt?file=rolldown.config.mjs,src%2Fentry.js,src%2Fshared.js,src%2Fdyn-entry.js

https://rollupjs.org/repl/?version=4.38.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwaW1wb3J0KCcuJTJGZHluLWVudHJ5LmpzJyklM0IlNUNuJTdEJTVDbmV4cG9ydCUyMCU3QiUyMHZhbHVlJTIwJTdEJTIwZnJvbSUyMCcuJTJGc2hhcmVkJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwdmFsdWUlMjAlN0QlMjBmcm9tJTIwJy4lMkZzaGFyZWQnJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmR5bi1lbnRyeS5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHZhbHVlJTIwJTNEJTIwJ3NoYXJlZCclM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMnNoYXJlZC5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmlubGluZUR5bmFtaWNJbXBvcnRzJTIyJTNBZmFsc2UlN0QlN0QlN0Q=

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed https://github.com/rolldown/rolldown/issues/3998

---

This PR makes unused dynamic entries disappear instead continuing participate in calculations related to enries.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4656** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4656?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4655** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4655?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4655?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/stages/link_stage/mod.rs [hunk 1]
```diff
@@ -137,55 +136,59 @@ impl<'a> LinkStage<'a> {
...
-            let lived = stmt_info.is_included && !all_dead_pure_dynamic_import;
-            if !lived {
-              // satisfy rustc borrow checker
-              let module = self.module_table.modules[*module_idx]
-                .as_normal_mut()
-                .expect("should be a normal module");
-              for ele in dead_pure_dynamic_import_record_idx {
-                let rec = &mut module.import_records[ele];
-                rec.meta.insert(ImportRecordMeta::DEAD_DYNAMIC_IMPORT);
+  fn get_lived_entry(
```
Comment (hyf0) [inline crates/rolldown/src/stages/link_stage/mod.rs]: We need a more proper name for this. Something like `tweak_ununsed_entries`.  I first thought this method still a pure function.

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/src/stages/link_stage/mod.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/src/stages/link_stage/mod.rs]: yup, it is just a poc, I need to clean up a little bit.

File: crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs [hunk 2]
```diff
@@ -48,34 +50,80 @@ impl LinkStage<'_> {
...
+          }
+        });
+      }
+    }
+
+    let mut unused_record_idxs = vec![];
+
+    dynamic_entries.sort_by_key(|item| self.module_table.modules[item.id].exec_order());
+
+    dynamic_entries.retain(|entry| {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/link_stage/tree_shaking/include_statements.rs:94]: We can't compute the unused dynamic entry AOT, because some dynamic entries maybe descendants of a dynamic entry module.
