### PR TITLE
fix: use `process.on('exit')` instead of `signal-exit` on webcontainers

### LINKED ISSUE #7381: [Bug]: `signal-exit` is incompatible with StackBlitz
### Reproduction link or steps

https://stackblitz.com/edit/stackblitz-starters-rf7brvcm?file=index.mjs

### What is expected?

Throw an error

### What is actually happening?

No output

### System Info

```Shell
StackBlitz only.
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by sapphi-red**
fixes #7381

### CODE REVIEW

**Comment by sapphi-red** [comment]
* **#7421** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7421?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7421?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7421).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/src/utils/signal-exit.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { onExit as originalOnExit } from 'signal-exit';
+
+export function onExit(...args: Parameters<typeof originalOnExit>): void {
```
Comment (hyf0) [inline packages/rolldown/src/utils/signal-exit.ts:3]: Could we add some context here to explain why? Or maybe just append the issue link,

**Review by hyf0 — APPROVED** [review]

File: packages/rolldown/src/utils/signal-exit.ts (hunk 1 above)
Comment (sapphi-red) [reply packages/rolldown/src/utils/signal-exit.ts:3]: Yep 👍
