### PR TITLE
fix(rolldown_plugin_alias): only replace the first matched alias

### LINKED ISSUE #328: Build error when enabling the enableNativePlugin
### Describe the bug

Enabling the enableNativePlugin causes a build error if the static resource image name contains @

Image

### Reproduction

https://codesandbox.io/p/live/167cc878-5f2c-48ec-b8d5-cb5ddf6cc9d7

### Steps to reproduce

npm run build

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 2.64 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 22.16.0 - /usr/local/share/nvm/versions/node/v22.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.9.2 - /usr/local/share/nvm/versions/node/v22.16.0/bin/npm
    pnpm: 8.15.6 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^5.2.1 => 5.2.4 
    rolldown-vite:  7.0.9
```

### Used Package Manager

npm

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by shulaoda**
closes https://github.com/vitejs/rolldown-vite/issues/328

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#5412** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5412?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5412?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_utils/src/js_regex.rs [hunk 1]
```diff
@@ -46,6 +46,21 @@ impl HybridRegex {
...
+  pub fn replace<'a>(&self, haystack: &'a str, replacement: &str) -> Cow<'a, str> {
+    match self {
+      HybridRegex::Optimize(r) => r.replace(haystack, replacement),
+      HybridRegex::Ecma(reg) => {
+        let next = reg.find_iter(haystack).next();
+        let Some(m) = next else { return Cow::Borrowed(haystack) };
+        let mut ret = String::with_capacity(haystack.len());
+        ret.push_str(&haystack[..m.start()]);
+        ret.push_str(replacement);
+        ret.push_str(&haystack[m.end()..]);
```
Comment (IWANABETHATGUY) [inline crates/rolldown_utils/src/js_regex.rs]: use `concat_string` in rolldown_utils seems better: 

        Cow::Owned(concat_string!(&haystack[..m.start()], replacement, &haystack[m.end()..]))

**Review by IWANABETHATGUY — APPROVED** [review]
