### PR TITLE
fix: transform JS files containing `</script>` to escape template literals

### LINKED ISSUE #6829: Keep `</script>` as-is for tagged templates
### Reproduction link or steps

In `sv` (svelte cli), we started to use `tsdown` and we just got this report https://github.com/sveltejs/cli/issues/761
After investigations it looks like it's the way `tsdown` is bundling Template Literals.

Here is a repro where I compare the [output of rolldown and tsdown](https://github.com/jycouet/template-rolldown-tsdown)

You can see that in the bundle we have `<\/script>` while I would expect `</script>`

### What is expected?

I would expect `</script>`

### What is actually happening?

When bundling `</script>`, we have `<\/script>` in the bundle.

### Any additional comments?

If you run the script on the repo you will see this summary

Image

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #6829

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7987** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7987?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7987?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7987).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by IWANABETHATGUY** [comment]
### Merge activity

* **Jan 21, 10:18 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Jan 21, 10:47 AM UTC**: `IWANABETHATGUY` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Jan 21, 10:58 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).

**Review by shulaoda — APPROVED** [review]

**Comment by hyf0** [comment]
Let's wait for the benchmark results

File: crates/rolldown_common/src/inner_bundler_options/types/transform_option/mod.rs [hunk 1]
```diff
@@ -83,7 +83,7 @@ impl TryFrom<TransformOptions> for oxc::transformer::TransformOptions {
       // helper_loader: options
       //   .helpers
       //   .map_or_else(HelperLoaderOptions::default, HelperLoaderOptions::from),
-      plugins: options.plugins.map(oxc::transformer::PluginsOptions::from).unwrap_or_default(),
+      plugins: oxc::transformer::PluginsOptions::from(options.plugins.unwrap_or_default()),
```
Comment (IWANABETHATGUY) [inline crates/rolldown_common/src/inner_bundler_options/types/transform_option/mod.rs:86]: Always create a default `plugins` entry, since we need to enable `tagged_template_transform` unconditionally

**Comment by IWANABETHATGUY** [comment]
1% ~ 4% could be treated as noise, and CodeSpeed did not warn about the regression.
