### PR TITLE
fix(iife): `MISSING_NAME_OPTION_FOR_IIFE_EXPORT` is output even if nothing is exported from the entrypoint

### LINKED ISSUE #2255: [Bug]: `MISSING_NAME_OPTION_FOR_IIFE_EXPORT` is output even if nothing is exported from the entrypoint
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-qkv41p?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. see `MISSING_NAME_OPTION_FOR_IIFE_EXPORT` is output
4. run `npm run build:up` to run rollup
5. see no warning is output

### What is expected?

no warning is output

### What is actually happening?

`MISSING_NAME_OPTION_FOR_IIFE_EXPORT` warning is output

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@dab103f => 0.13.2
```

### Any additional comments?

This is not something urgent.

### PR DESCRIPTION
**Pull request by shulaoda**
### Description

closes #2255 

The main improvements include adding a check for `hasExports` and altering some of the structural writing, which makes the code clearer.

The following are the conditions for warning in `Rollup`.
```ts
if (hasExports && !name) {
	log(LOGLEVEL_WARN, logMissingNameOptionForIifeExport());
}
```
At present, there is no clue about `reexports`.
```ts
const renderedExports = exportMode === 'none' ? [] : this.getChunkExportDeclarations(format);
let hasExports = renderedExports.length > 0;
let hasDefaultExport = false;
for (const renderedDependence of renderedDependencies) {
	const { reexports } = renderedDependence;
	if (reexports?.length) {
		hasExports = true;
		if (!hasDefaultExport && reexports.some(reexport => reexport.reexported === 'default')) {
			hasDefaultExport = true;
		}
		if (format === 'es') {
			renderedDependence.reexports = reexports.filter(
				// eslint-disable-next-line unicorn/prefer-array-some
				({ reexported }) => !renderedExports.find(({ exported }) => exported === reexported)
			);
		}
	}
}
```

### CODE REVIEW

**Comment by shulaoda** [comment]
The main improvements include adding a check for `hasExports` and altering some of the structural writing, which makes the code clearer.

The following are the conditions for warning in `Rollup`.
```ts
if (hasExports && !name) {
	log(LOGLEVEL_WARN, logMissingNameOptionForIifeExport());
}
```
At present, there is no clue about `reexports`.
```ts
const renderedExports = exportMode === 'none' ? [] : this.getChunkExportDeclarations(format);
let hasExports = renderedExports.length > 0;
let hasDefaultExport = false;
for (const renderedDependence of renderedDependencies) {
	const { reexports } = renderedDependence;
	if (reexports?.length) {
		hasExports = true;
		if (!hasDefaultExport && reexports.some(reexport => reexport.reexported === 'default')) {
			hasDefaultExport = true;
		}
		if (format === 'es') {
			renderedDependence.reexports = reexports.filter(
				// eslint-disable-next-line unicorn/prefer-array-some
				({ reexported }) => !renderedExports.find(({ exported }) => exported === reexported)
			);
		}
	}
}
```

File: crates/rolldown/src/ecmascript/format/utils/namespace.rs [hunk 1]
```diff
@@ -64,50 +64,58 @@ pub fn generate_identifier(
...
-      // This behavior is aligned with Rollup. If using `output.extend: true`, this error won't be triggered.
-      let name = ArcStr::from(name);
-      Err(vec![BuildDiagnostic::illegal_identifier_as_name(name)])
-    }
-  } else {
-    // If the `name` is empty, you may be impossible to call the result.
-    // But it is normal if we do not have exports.
-    // However, if there is no export, it is recommended to use `app` format.
+  // Handle the diagnostic warning
+  if ctx.options.name.is_none() && !matches!(export_mode, OutputExports::None) {
```
Comment (7086cmd) [inline crates/rolldown/src/ecmascript/format/utils/namespace.rs]: Consider the situation: the name is a empty string.

**Review by 7086cmd — APPROVED** [review]
LGTM

**Review by hyf0 — APPROVED** [review]
Nice!
