### PR TITLE
fix: validator of `output.minify`

### LINKED ISSUE #6061: [Bug]: Rolldown emits warning for minify.mangle incorrectly
### Reproduction link or steps

```ts
// "rolldown": "^1.0.0-beta.35"
import { rolldown } from 'rolldown';

const input = await rolldown({
  input: import.meta.dir + '/index.ts',
  transform: {
    typescript: {
      rewriteImportExtensions: true
    }
  }
});

const output = await input.generate({
  inlineDynamicImports: true,
  minify: {
    compress: false,
    // This works fine btw it just warns incorrectly
    mangle: {
      toplevel: true
    }
  }
});

// index.ts
console.log('Hi');
```

### What is expected?

No warnings

### What is actually happening?

```ts
Warning: Invalid output options (1 issue found)
- For the "minify.mangle". Invalid type: Expected boolean but received Object.
```

### System Info

```Shell
System:
    OS: Linux 6.15 EndeavourOS
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 11.60 GB / 15.36 GB
    Container: Yes
    Shell: 5.2.37 - /bin/bash
  Binaries:
    Node: 24.4.1 - ~/.config/nvm/versions/node/v24.4.1/bin/node
    npm: 11.4.2 - ~/.config/nvm/versions/node/v24.4.1/bin/npm
    bun: 1.2.21 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 138.1.80.124
  npmPackages:
    rolldown: ^1.0.0-beta.35 => 1.0.0-beta.35
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #6061

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#5893** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6062** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6062?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/6062?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/src/utils/validator.ts [hunk 1]
```diff
@@ -292,10 +292,45 @@ const ChecksOptionsSchema = v.strictObject({
...
+    v.literal('es2019'),
+    v.literal('es2020'),
+    v.literal('es2021'),
+    v.literal('es2022'),
+    v.literal('es2023'),
+    v.literal('es2024'),
+  ])),
+  dropConsole: v.optional(v.boolean()),
+  dropDebugger: v.optional(v.boolean()),
+  keepNames: v.optional(v.union([v.boolean(), CompressOptionsKeepNamesSchema])),
```
Comment (sapphi-red) [inline packages/rolldown/src/utils/validator.ts]:
```suggestion
  keepNames: v.optional(CompressOptionsKeepNamesSchema),
```
`CompressOptions['keepNames']` has `CompressOptionsKeepNames` instead of `boolean | CompressOptionsKeepNames`.
Probably we should improve oxc-minifier side.

**Review by sapphi-red — APPROVED** [review]
