### PR TITLE
fix: deduplicate entry point

### LINKED ISSUE #4946: [Bug]: generate `n + 1` chunks, if user declare same entry `n` times
### Reproduction link or steps

https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-swq5umnb?file=rolldown.config.mjs,package.json

### What is expected?

should auto-deduplicate entry point

### What is actually happening?

did not auto-deduplicate entry point

### System Info

```Shell
n/a
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #4946

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4956** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4956?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/tests/fixtures/input/deduplicate/emit-file/_config.ts [hunk 1]
```diff
@@ -19,7 +19,6 @@ export default defineTest({
 	},
 	afterTest: function (output) {
 		let chunkNames = getOutputChunkNames(output).sort();
-    // two entry chunks + shared chunk
-		expect(chunkNames.length).toStrictEqual(3);
+		expect(chunkNames.length).toStrictEqual(1);
```
Comment (IWANABETHATGUY) [inline packages/rolldown/tests/fixtures/input/deduplicate/emit-file/_config.ts:22]: Fixed issues in previous pr.

File: packages/rolldown/tests/fixtures/input/deduplicate/emit-file2/_config.ts [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+				},
+        renderChunk() {
+          fn();
+        }
+			},
+		],
+	},
+	afterTest: function () {
+    // entry, main.d.ts and a shared chunk
+    expect(fn).toHaveBeenCalledTimes(3);
```
Comment (IWANABETHATGUY) [inline packages/rolldown/tests/fixtures/input/deduplicate/emit-file2/_config.ts:38]: https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-jqg7vnkw?file=rolldown.config.mjs,src%2Findex.js,package.json

Before we will generate 4 chunks, now deduplicate the same chunk for `main.d.ts`
However, rollup generate two chunks, this is due to different chunk split strategy, which is not realted to this pr.

**Review by hyf0 — APPROVED** [review]
