### PR TITLE
fix: chunk sorting total order

### LINKED ISSUE #3429: [Bug]: Sorting  panic in https://github.com/vitejs/vite-ecosystem-ci/blob/rolldown-vite/README-temp.md
### Reproduction link or steps

[n/https://github.com/vitejs/vite-ecosystem-ci/blob/rolldown-vite/README-temp](https://github.com/vitejs/vite-ecosystem-ci/blob/rolldown-vite/README-temp.md)

### What is expected?

don't panic

### What is actually happening?

panic

### System Info

```Shell
n/a
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/rolldown/rolldown/issues/3429#issuecomment-2618556361

There's a total order violation as explained in https://github.com/rolldown/rolldown/issues/3429#issuecomment-2618556361. I'm not entirely sure about the original comment's intent, but I interpreted in a following way and fixed the sorting accordingly.

```
EntryPoint (is_user_defined: true) < EntryPoint (is_user_defined: false) or Common
[order by chunk index]               [order by exec order]
```

### CODE REVIEW

File: crates/rolldown/src/stages/generate_stage/code_splitting.rs [hunk 1]
```diff
@@ -172,41 +172,16 @@ impl GenerateStage<'_> {
...
-            if *a_is_user_defined && *b_is_user_defined {
-              // Using user specific order of entry
-              index_a.cmp(index_b)
-            } else {
-              a.exec_order.cmp(&b.exec_order)
-            }
-          }
-          _ => a.exec_order.cmp(&b.exec_order),
-        }
+      .sorted_by_key(|(index, a)| match &a.kind {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/generate_stage/code_splitting.rs]: Can you change `a` into a more meaningful name?

**Review by IWANABETHATGUY — APPROVED** [review]
