### PR TITLE
fix: deconfilct chunk name after name generated

### LINKED ISSUE #4177: [Bug]: should deconflict filename for chunkFileNames with same name returned by a function
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-nci4o6nk-fnskzcj7?file=package.json,rolldown.config.mjs
2. `pnpm i` runs automatically
3. `pnpm run build` runs automatically
4. `dist/js` only contains `foo.js`
5. run `npm run build:up` to use rollup
6. `dist/js` contains `foo.js` and `foo2.js` (the file name is deconflicted)

### What is expected?

`dist/js` to contain `foo.js` and `foo2.js` like rollup.

### What is actually happening?

`dist/js` only contains `foo.js`.

### System Info

```Shell
StackBlitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @rolldown/browser:  1.0.0-beta.7-commit.cef50bd
```

### Any additional comments?

It works correctly with `chunkFileNames: 'js/[name].js',`.

Originally reported at https://github.com/vitejs/rolldown-vite/issues/127

### PR DESCRIPTION
**Pull request by underfin**
### Description
close https://github.com/rolldown/rolldown/issues/4177.

Here follow rollup deconfilct chunk name after name generated, it is used with `bundle` as `used_name_counts`, so here merge the js/css to one map.ref https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L588

Extract it to an isolated function because the asset also could be using it.

### CODE REVIEW

**Comment by underfin** [comment]
* **#4195** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4195?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4194** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4194?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4193** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4193?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4191** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4191?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_common/src/chunk/mod.rs [hunk 1]
```diff
@@ -219,9 +210,16 @@ impl Chunk {
       }
     });
 
-    let filename = filename_template.render(Some(&name), None, hash_replacer);
+    let filename = filename_template.render(Some(chunk_name), None, hash_replacer).into();
+
+    let name = if has_hash_pattern {
+      make_unique_name(&filename, used_name_counts);
```
Comment (IWANABETHATGUY) [inline crates/rolldown_common/src/chunk/mod.rs:216]: You could extract it before the ifStmt, since it will exec anyway

Comment (underfin) [reply crates/rolldown_common/src/chunk/mod.rs:216]: Yeah. Here could be improved, here not change it because i want to make pr minimal compare pevious.

Comment (underfin) [reply crates/rolldown_common/src/chunk/mod.rs:216]: Let's review it at https://github.com/rolldown/rolldown/pull/4195.

File: crates/rolldown/tests/rolldown/issues/4129/_config.json [hunk 2]
```diff
@@ -1,4 +1,5 @@
 {
+  "expectExecuted": false,
```
Comment (underfin) [inline crates/rolldown/tests/rolldown/issues/4129/_config.json:2]: Disabled it because the hmr using ws, it failed at executed test.

**Review by sapphi-red — APPROVED** [review]

**Review by sangquangnguyen — APPROVED** [review]
🚀
