### PR TITLE
fix(node): ensure comments option got passed to rust

### LINKED ISSUE #4491: [Bug]: Comments are preserved even with `minify: true` + `comments: 'none'`
### Reproduction link or steps

https://stackblitz.com/edit/github-jpqghezu-w5svmyzh?file=package.json

### What is expected?

No comments are included in the output.

### What is actually happening?

Some comments are included in the output.

### System Info

```Shell
N/A
```

### Any additional comments?

Reported by @sapphi-red https://github.com/rolldown/tsdown/issues/218

### PR DESCRIPTION
**Pull request by hyf0**
### Description

Closes #4491

### CODE REVIEW

**Comment by hyf0** [comment]
* **#4528** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4527** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4527?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4527?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#4526** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/src/utils/bindingify-output-options.ts [hunk 1]
```diff
@@ -70,6 +70,7 @@ export function bindingifyOutputOptions(
     sanitizeFileName,
     preserveModules,
     virtualDirname,
+    comments: outputOptions.comments,
```
Comment (IWANABETHATGUY) [inline packages/rolldown/src/utils/bindingify-output-options.ts]: NIT:
you could destruct `comments` from `outputOptions` just like other fields

**Review by IWANABETHATGUY — APPROVED** [review]

File: packages/rolldown/src/utils/bindingify-output-options.ts (hunk 1 above)
Comment (hyf0) [reply packages/rolldown/src/utils/bindingify-output-options.ts]: DONE
