### PR TITLE
fix: return `moduleSideEffects` set by native plugins from `this.resolve`

### LINKED ISSUE #317: moduleSideEffects from `this.resolve` is incorrect w/ native plugins
### Describe the bug

I discovered this when testing rolldown-vite with native plugins enabled on a project that uses [Sonda](https://sonda.dev/). When I combined the two, tree-shaking broke pretty drastically, and the main bundle size went from ~700 KB to 3.5 MB.

It looks like what is happening is that `this.resolve` seems to return `moduleSideEffects: null` even for files within packages that are set as `"sideEffects": "false"` in their package.json. As a result, the simple little wrapper `resolveId` hook that returns the value of `this.resolve` seems to force include all the code.

### Reproduction

https://stackblitz.com/edit/vitejs-rolldown-vite-hczyjpvm?file=vite.config.js

### Steps to reproduce

In the reproducer, I used lodash-es as an example of a library that sets `sideEffects: false` and I'm importing a single function from lodash-es and never using it.

With native plugins **enabled** and running `npm run build`, the js files is 92.19 kB and all of lodash-es appears to be included.
With native plugins **disabled**, all the files under lodash-es correctly return `moduleSideEffects: false` and the resulting bundle size is 2.57 kB

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown-vite:  7.0.5
```

### Used Package Manager

npm

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sapphi-red**
`moduleSideEffects` on the native side was not returned from `this.resolve`.

fixes https://github.com/vitejs/rolldown-vite/issues/317

### CODE REVIEW

**Comment by sapphi-red** [comment]
* **#5206** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5206?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5205** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5205?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5205?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#5204** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5204?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5203** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5203?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/rolldown/src/plugin/plugin-context.ts [hunk 1]
```diff
@@ -184,6 +184,8 @@ export class PluginContextImpl extends MinimalPluginContextImpl {
         )
         : res.external,
       ...info,
+      moduleSideEffects: info.moduleSideEffects ?? res.moduleSideEffects ??
+        null,
```
Comment (sapphi-red) [inline packages/rolldown/src/plugin/plugin-context.ts:188]: I'm not sure about the merge here. There aren't much information about what `info.moduleSideEffects` is and how that should be handled.

**Review by hyf0 — APPROVED** [review]

File: packages/rolldown/src/plugin/plugin-context.ts (hunk 1 above)
Comment (hyf0) [reply packages/rolldown/src/plugin/plugin-context.ts:188]: I don't understand how module option is. If you identify which has higher priority, I think the current merge logic is fine.
