### PR TITLE
fix: dynamic chunk not exported when using preserveModules

### LINKED ISSUE #4647: [Bug]: Chunk Not Exported When Using preserveModules
### Reproduction link or steps

https://bundler.sxzz.dev/#eNptjksKwzAMRK8ivHEDwW23hvQGvUE2IZZLij/BnzYQfPfKpB8K2Wk0M8xbmWZyZZNTuIgU6+2Y/OmWjSRxmX1IMHoXE1ivoINDA90FJluNAxdH+lKeN72jDjKZQsbSsuCNUf7pBHX1dBP378SO8zemUA/ZJFh7B+BzmnOSmwCYA0YMD7x6lQ1GCXWt3Tztgx0oyjFaXl+FjEJYRLNBfgjeanf1fGKllBddHV4A

### What is expected?

`mod_default` is exported in `mod.js`

### What is actually happening?

```js
//#region mod.ts
var mod_default = 10;

//#endregion
```

### System Info

```Shell
N/A
```

### Any additional comments?

https://github.com/rolldown/tsdown/issues/256

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed https://github.com/rolldown/rolldown/issues/4647

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4650** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4650?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4650?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#4648** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4648?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/chunk/render_chunk_exports.rs [hunk 1]
```diff
@@ -321,9 +317,6 @@ pub fn get_export_items(
 
   match chunk.kind {
     ChunkKind::EntryPoint { module, is_user_defined, .. } => {
-      if options.preserve_modules && !is_user_defined {
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/chunk/render_chunk_exports.rs:324]: This hack code is not needed since https://github.com/rolldown/rolldown/pull/4626/files

**Review by hyf0 — APPROVED** [review]

**Comment by ywenhao** [comment]
nice
