### PR TITLE
fix: `preserveModules` co exists with multi entrypoints

### LINKED ISSUE #4624: [Bug]: Generated imports reference non-existent exports when using preserveModules/unbundle
### Reproduction link or steps

https://github.com/pcfreak30/rolldown-unbundle-repro

### What is expected?

```
// dist/esm/a.js
import { b_default } from "./b.js"; // ❌ Importing non-existent named export
export { b_default as B };

// dist/esm/b.js
export { b_default as default }; // ✅ Only exports default
```

### What is actually happening?

```
// Invalid import of non-existent named export
import { b_default } from "./b.js";
export { b_default as B };
```

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 7.66 GB / 62.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v22.14.0/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
    bun: 1.2.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 135.1.77.101
    Chrome: 135.0.7049.114
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed #4624

### CODE REVIEW

File: crates/rolldown/src/stages/generate_stage/render_chunk_to_assets.rs [hunk 1]
```diff
@@ -182,6 +185,18 @@ impl GenerateStage<'_> {
     let mut index_preliminary_assets: IndexInstantiatedChunks =
       IndexVec::with_capacity(chunk_graph.chunk_table.len());
     let chunk_index_to_codegen_rets = self.create_chunk_to_codegen_ret_map(chunk_graph);
+    let render_export_items_index_vec = &chunk_graph
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/stages/generate_stage/render_chunk_to_assets.rs:188]: Pre generate the `export_items_index_vec`, because now render chunk_imports may use other chunk `export_item` info

File: crates/rolldown/src/ecmascript/format/esm.rs [hunk 2]
```diff
@@ -104,9 +103,9 @@ fn render_esm_chunk_imports(ctx: &GenerateContext<'_>) -> Option<String> {
       .filter_map(|item| {
         let canonical_ref = ctx.link_output.symbol_db.canonical_ref_for(item.import_ref);
         let imported = &ctx.chunk.canonical_names[&canonical_ref];
-        let Specifier::Literal(alias) = item.export_alias.as_ref().unwrap() else {
-          panic!("should not be star import from other chunks")
-        };
+        let alias = &ctx.render_export_items_index_vec[*exporter_id]
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/ecmascript/format/esm.rs:106]: In some case the `export_alias` can't represent the alias correctly, so I use info from imported chunk `exports_info` instead, use the test case as an example: 

```bash
[crates/rolldown/src/ecmascript/format/esm.rs:99:5] &ctx.chunk.name = Some(
    "main",
)
[crates/rolldown/src/ecmascript/format/esm.rs:105:9] &item = CrossChunkImportItem {
    export_alias: Some(
        Literal(
            Rstr(
                "b_default",  // the alias should be `default` but here it return `b_default`
            ),
        ),
    ),
    import_ref: SymbolRef {
        owner: 3,
        symbol: SymbolId(
            4294967294,
        ),
    },
}
[crates/rolldown/src/ecmascript/format/esm.rs:108:9] &imported = Rstr(
    "b_default",
)
[crates/rolldown/src/ecmascript/format/esm.rs:99:5] &ctx.chunk.name = Some(
    "a",
)
[crates/rolldown/src/ecmascript/format/esm.rs:105:9] &item = CrossChunkImportItem {
    export_alias: Some(
        Literal(
            Rstr(
                "b_default",
            ),
        ),
    ),
    import_ref: SymbolRef {
        owner: 3,
        symbol: SymbolId(
            4294967294,
        ),
    },
}
[crates/rolldown/src/ecmascript/format/esm.rs:108:9] &imported = Rstr(
    "b_default",
)
```

File: crates/rolldown/src/ecmascript/format/esm.rs [hunk 3]
```diff
@@ -104,9 +103,9 @@ fn render_esm_chunk_imports(ctx: &GenerateContext<'_>) -> Option<String> {
...
+          .get(&item.import_ref)
+          .expect("should have export item index")[0];
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/ecmascript/format/esm.rs:108]: Same symbol may have multiple alias, e.g.: 

```js
const a = 1000;
export {
  a, 
  a as b
}
```
always use the same alias is alright, since the both point to the same `symbol` finally.

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
* **#4628** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4628?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4626** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4626?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4626?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
