### PR TITLE
fix: chunk level directives rendering

### LINKED ISSUE #4548: [Bug]: Hoist Comment Directives
### Reproduction link or steps

https://bundler.sxzz.dev/#eNptjUsKwzAMRK9itEkLwQfwWbIptlxcjFQcmRqM7t6E/DbZzfCYNx0iuA6JAjYr85oJ3NVH8Esd6ozG54Qkw0QTYftyERMreUlMpj2epq9AlwGCk1JRRyicc+AfWc8U09t+Tv8N2Z52c8D4qlkOqar+AdpdOjY=

### What is expected?

Rolldown:
```js
"use client";

//#region index.ts
function x() {}

//#endregion
export { x };
```

### What is actually happening?

esbuild: 
```js
"use client";

// index.ts
function x() {
}
export {
  x
};
```

### System Info

```Shell
N/A
```

### Any additional comments?

Downstream: https://github.com/rolldown/tsdown/issues/157

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed #4548

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4551** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4551?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4551?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/ecmascript/format/app.rs [hunk 1]
```diff
@@ -1,28 +1,34 @@
...
     source_joiner.append_source(hashbang);
   }
   if let Some(banner) = banner {
     source_joiner.append_source(banner);
   }
 
+  if !directives.is_empty() {
+    source_joiner.append_source(render_chunk_directives(directives.iter()));
+    source_joiner.append_source("");
+  }
```
[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply crates/rolldown/src/ecmascript/format/app.rs:30]: There is no such function in the codebase, bad copilot.

File: crates/rolldown/tests/esbuild/dce/preserve_directives_minify_bundle/artifacts.snap [hunk 2]
```diff
@@ -1,27 +1,24 @@
...
+'use 1'
+'use 2'
+'use 3'
+
 (function() {
 
 "use strict";
 
 //#region nested.js
-"use A";
```
Comment (Boshen) [inline crates/rolldown/tests/esbuild/dce/preserve_directives_minify_bundle/artifacts.snap:15]: What should happen to these? It's not present in the output.

Comment (IWANABETHATGUY) [reply crates/rolldown/tests/esbuild/dce/preserve_directives_minify_bundle/artifacts.snap:15]: just align with esbuild, 
image

**Review by hyf0 — APPROVED** [review]
