### PR TITLE
fix: remove redundant bare side-effect imports in entry/facade chunks

### LINKED ISSUE #8252: [Bug]: redundant side-effect imports in facade entry chunks
### Reproduction link or steps

https://repl.rolldown.rs/#eNqtUj1PwzAQ/SsnL0mlNhQJMQQxlZmlCJYuJrk0ps65cuwWKcp/5/KdtkJiIINjv7v37vnOlchEXIlCKoq+ymZLIh6PS5HwSRVHYx1UYLE0+oRvuaI91JBZU0AQ3fUwE4KnHe0Iv9v8zFPilCHQRqbvD+ECqh0Bizhv6UIrXDCv3hHXQxE767FeipI10M5MTcD/2EosSofbVvUv5tjTJDmYmiGdq8RQ6VjgaM3GeGJteAbCM2xNga4RfMVzq3nr6LLslaNJcObHaJ2aM0VcNVP7ua/byFXXUswU4aYNj10baBcd40zpdfsfGWFrTtHRu7gzCtANKIZgnFSw7CLNe2K8f1YdWrers4hlLg8Y89Zjixnv5rKJRkkvioXHDIDM2EJyToBlMVUhL/Um93QoQ5X2DWw+lQEDEVJafiiXh8HsbSwWQ48HtLn8L7zpZjNaB66SpvDE7aPkte6x7sbNWjfzFzVP8MQjuY/W0Xr1iU5Gj2tR/wBi4TaX

### What is expected?

No `import "./resolve-DNfst9LS.js";` in the `sorter.js`output

### What is actually happening?

The `sorter.js` output has a redundant import `import "./resolve-DNfst9LS.js`, which should be removed.

`import "./resolve-DNfst9LS.js` is redundant because the `import { t as createSorter } from "./sorter-chunk-CJmPqDr7.js";` already implicitly imported `import "./resolve-DNfst9LS.js`.

### System Info

```Shell
Not related to this
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by h-a-n-a**
## Summary

Remove redundant bare side-effect imports from entry/facade chunks. Previously, a bit-based pass added
bare imports for ALL reachable side-effectful chunks to entry points, even when those chunks were already
transitively loaded through binding imports.

## Changes

- Replace the broad bit-based chunk lookup with import-record-based checks that add bare imports only where the
actual dependency exists (any chunk, not just entries)
- Ensure facade entries import their entry module's chunk so it executes. (This was implicitly handled in bit-based reachability check)
- Add `.has_side_effectful_runtime_dep` field if runtime has side-effect (e.g. runtime in dev/HMR mode)

## Related issues

closes https://github.com/rolldown/rolldown/issues/8252

### CODE REVIEW

**Comment by h-a-n-a** [comment]
* **#8804** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8804?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/8804?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=8804).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js
Comment (hyf0) [inline crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js:1]: The test case is complicated than the one raised in https://github.com/rolldown/rolldown/issues/8252#issue-3914805485. Can the original version trigger the behavior?

**Comment by hyf0** [comment]
I just checked https://github.com/rolldown/rolldown/issues/8252, I think the original code is not even a bug.

File: crates/rolldown/src/types/linking_metadata.rs [hunk 1]
```diff
@@ -82,6 +82,9 @@ pub struct LinkingMetadata {
   /// also need to link the exported facade symbol.
   pub included_commonjs_export_symbol: FxHashSet<SymbolRef>,
   pub depended_runtime_helper: RuntimeHelper,
+  /// Dependencies that need bare imports but aren't available in import records.
+  /// e.g. the runtime module injected in dev/HMR mode.
+  pub injected_side_effect_deps: Vec<ModuleIdx>,
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/types/linking_metadata.rs]: Since the `injected_side_effect_deps` can only store ' runtime_idx`, we can use a boolean flag to record the related status, and then retrieve `self.runtime.id` to get the index later at `crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs`.

File: crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js
Comment (h-a-n-a) [reply crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js:1]: This test doesn't use the manual code splitting trick in the original issue. It was instead derived from the `prettier-plugin-tailwindcss` from this comment https://github.com/rolldown/rolldown/issues/8252#issuecomment-3869772050.

I will add another test to the original reproduction.

**Review by hyf0 — APPROVED** [review]
Overall LGTM.

**Comment by hyf0** [comment]
@h-a-n-a One convention rule is that only PR's assignee gets to merge the PR.

**Review by IWANABETHATGUY — APPROVED** [review]

File: crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js
Comment (h-a-n-a) [reply crates/rolldown/tests/rolldown/issues/8252/node_modules/enhanced-resolve/lib/index.js:1]: I tried to migrate the original test case and adapted the `manualChunks()` to the current `manualCodeSplitting`. but rust test result is quite different than it. It does not create a facade sorter module even if i use `preserveEntrySingatures`. I haven't looked into it. Do you have any context here maybe? cc @hyf0

File: crates/rolldown/src/types/linking_metadata.rs (hunk 1 above)
Comment (h-a-n-a) [reply crates/rolldown/src/types/linking_metadata.rs]: Fixed.

Previously, I though there would be a case where multiple runtime modules are generated.

File: crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs [hunk 2]
```diff
@@ -511,64 +521,58 @@ impl GenerateStage<'_> {
...
+        if !self.options.is_strict_execution_order_enabled() {
+          for &module_idx in &chunk.modules {
+            let Some(module) = self.link_output.module_table[module_idx].as_normal() else {
+              continue;
+            };
+
+            // From import records.
+            // This adds side-effectful imports as bare imports if necessary.
+            for rec in &module.import_records {
+              if rec.kind == ImportKind::DynamicImport {
```
[the remark this answers is not in the document]
Comment (h-a-n-a) [reply crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs]: Fixed. I think you are correct.

`DynamicImport` creates its own entry.
`Require` will automatically call `require_xxx()` to init.
`NewUrl` and `HotAccept` uses respective syntax.

So only `Import` needs this.

**Comment by h-a-n-a** [comment]
### Merge activity

* **Mar 21, 11:32 AM UTC**: The merge label 'graphite: merge-when-ready' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown) once it meets the requirements.
* **Mar 21, 11:32 AM UTC**: `h-a-n-a` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
* **Mar 21, 11:37 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=rolldown&repo=rolldown).
