### PR TITLE
fix(rolldown): options `context` should be available in renderStart

### LINKED ISSUE #5670: [Bug]: `context` options should be available in renderStart
### Reproduction link or steps

From https://github.com/rollup/rollup/blob/e4082a84063490503a6ee3b4ac74b45be745f111/test/function/samples/options-in-renderstart/_config.js, I know that although Rollup supports `option.context` recently, it has no option `context` available in renderStart, causing a misalignment issue.

### What is expected?

As title shown.

### What is actually happening?

As title shown.

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04.3 LTS 24.04.3 LTS (Noble Numbat)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-1340P
    Memory: 21.60 GB / 31.34 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.14.0 - /run/user/1000/fnm_multishells/365300_1754653888976/bin/node
    npm: 10.9.2 - /run/user/1000/fnm_multishells/365300_1754653888976/bin/npm
    pnpm: 10.14.0 - /run/user/1000/fnm_multishells/365300_1754653888976/bin/pnpm
  npmPackages:
    rolldown: workspace:* => 1.0.0-beta.31
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by situ2001**
fixes https://github.com/rolldown/rolldown/issues/5670

### CODE REVIEW

File: crates/rolldown_binding/src/types/binding_normalized_options.rs [hunk 1]
```diff
@@ -275,4 +275,9 @@ impl BindingNormalizedOptions {
   pub fn minify_internal_exports(&self) -> bool {
     self.inner.minify_internal_exports
   }
+
+  #[napi(getter)]
+  pub fn context(&self) -> String {
```
Comment (hyf0) [inline crates/rolldown_binding/src/types/binding_normalized_options.rs:280]: We had a test for this, could add this field in that test too?

https://github.com/rolldown/rolldown/blob/cf09f465b87e0d4b6cf1071ad132314f3b56b13c/packages/rolldown/tests/fixtures/verify-options/_config.ts

**Comment by hyf0** [comment]
@situ2001 Nicely done! Could you run `just test-node rollup --update` to update the status files.

**Review by hyf0 — APPROVED** [review]
Thank you!
