### PR TITLE
fix: used exports from dynamic imported module are removed incorrectly

### LINKED ISSUE #5340: [Bug]: used exports from dynamic imported module are removed incorrectly
### Reproduction link or steps

https://repl.rolldown.rs/#eNptjs0OgjAQhF9lsxcgwYqeDAafpJcKC6mB1rRVMU3f3VbjTwyXTXZmdr712GPtUaqOZjadbFoU1j9CiW3caT5r46DVyjrotYYGhL2rFvICmgOIm5AO5JRCOUe27sRgKN1zLPZcxRbC2pkLhRI/3hv2FRZghuIr5o/nueEKngk9Ehv1kGevYFYkK6SBIcKusW/DKlatjuQE2+4wPADBdE5n

### What is expected?

Returned value from `foo()` to be `Object.freeze({ __proto__: null, render: async () => { console.log('render') } })`

### What is actually happening?

Returned value from `foo()` is `Object.freeze({ __proto__: null })`. (does not have `render` export)

### System Info

```Shell
REPL

happens with 1.0.0-beta.15 (the oldest version that works in REPL) and 1.0.0-beta.28
```

### Any additional comments?

Originally reported at https://github.com/vitejs/rolldown-vite/issues/228

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
1. Closed #5340

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#5342** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5342?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5341** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5341?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/5341?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/tests/rolldown/tree_shaking/dynamic_import_issue_5340/main.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+export const foo = async () => await import("./dagre.mjs");
+
```
Comment (hyf0) [inline crates/rolldown/tests/rolldown/tree_shaking/dynamic_import_issue_5340/main.js:2]: Could we have a assertion here?

```js
assert_eq(typeof (await foo()).render,  'function')
```

**Review by hyf0 — APPROVED** [review]

File: crates/rolldown/tests/rolldown/tree_shaking/dynamic_import_issue_5340/main.js (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown/tests/rolldown/tree_shaking/dynamic_import_issue_5340/main.js:2]: yes
