### PR TITLE
fix: export runtime helpers for cross-chunk access

### LINKED ISSUE #7655: Runtime helpers not properly injected into dynamically imported chunks in CJS format
### Description
When using dynamic import with CJS output format, the runtime helper functions (like `__commonJSMin`) are not properly injected into the dynamically imported chunks. Instead, the generated code incorrectly tries to import them from the entry chunk.

### Reproduction

REPL: https://repl.rolldown.rs/#eNptUM1KxDAQfpUhl7ZQ4yqKEFlfQfCcS23T3UqSKWmyu1L67s6kXVzQS8j8fH8zi16oWQy+MxcZJ/57oX7rWrRcuhFDLLWQ9w11tahkPBpflq6C/Ru06Ce0Rlo8lE52pm+SjVX1SmgjVAzJLLVg4JU+/1dqh10iqLmwwgR7mHXQHuDU2GQUPD3Wa3001qKC4ozBdkVuLvwIog5obYdnL8lIPxxuhP6Z3CaC+D0amOFjW3sf40BZYIE+oIPiCi+0155TRs5KROoPhI2TzcGPKSpY6aUzsZG5VfMQU8zTvAnQY3ANlUX7NZECwMKZSGk9BmyH3CQ5KmU9kfkHuZO7u08mf34Ryw/rx5ge

```js
// index.js
import("./a.ts").then((m) => console.log(m.default));

// a.ts
module.exports = {
  value: 42,
  hello: 'world',
}
```

### Actual Output
The dynamically imported `chunk a-DKX7L-vB.js` incorrectly generates:
```js
const require_index = require('./index.js');

var require_a = /* @__PURE__ */ require_index.__commonJSMin(((exports, module) => {
    // ...
}));
```
The output tries to access ` __commonJSMin` from the entry chunk via `require('./index.js').__commonJSMin`, which doesn't work because `index.js` doesn't export the runtime helpers.

### Expected Behavior

The runtime helper `__commonJSMin` should be export.

### PR DESCRIPTION
**Pull request by shulaoda**
closes #7655, #7656

### CODE REVIEW

**Comment by shulaoda** [comment]
* **#7658** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7658?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7658?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7658).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by hyf0** [comment]
While this PR fixes the problem, I don't understand why it works and how the errro is caused.

File: crates/rolldown/src/utils/chunk/render_chunk_exports.rs [hunk 1]
```diff
@@ -154,7 +154,13 @@ pub fn render_chunk_exports(
         ChunkKind::EntryPoint { module, .. } => {
           let module =
             &link_output.module_table[module].as_normal().expect("should be normal module");
-          if matches!(module.exports_kind, ExportsKind::Esm) {
+          if !matches!(module.exports_kind, ExportsKind::Esm) {
+            export_items.retain(|(_, export_ref)| {
```
Comment (hyf0) [inline crates/rolldown/src/utils/chunk/render_chunk_exports.rs:158]: @shulaoda I commented out this line and test is still passed.

Comment (shulaoda) [reply crates/rolldown/src/utils/chunk/render_chunk_exports.rs:158]: What do you mean? Are you referring to the original `L157`, or the modified `L157`?

Comment (hyf0) [reply crates/rolldown/src/utils/chunk/render_chunk_exports.rs:158]: I moved the test into the main branch and it couldn't pass anymore. Guess something wrong with my local machine.

**Review by hyf0 — APPROVED** [review]

**Review by IWANABETHATGUY — APPROVED** [review]
