### PR TITLE
fix: stable generated exports

### LINKED ISSUE #312: Unstable generated exports
image

See https://github.com/rolldown-rs/rolldown/actions/runs/6902791859/job/18780184300#step:5:238 for details.

Might be related to https://github.com/rolldown-rs/rolldown/pull/131#discussion_r1377102878, need to invesigate.

### PR DESCRIPTION
**Pull request by hyf0**
### Description

Closes #312.

### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #313** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/313?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/313?utm_source=stack-comment).

File: crates/rolldown/src/bundler/chunk/render_chunk_exports.rs [hunk 1]
```diff
@@ -31,7 +31,8 @@ impl Chunk {
       }
     }
 
-    let export_items = self.get_export_items(graph);
+    let mut export_items = self.get_export_items(graph);
+    export_items.sort_unstable_by(|a, b| a.0.as_str().cmp(b.0.as_str()));
```
Comment (underfin) [inline crates/rolldown/src/bundler/chunk/render_chunk_exports.rs]: The `OutputChunk` `exports` is also used it, Could you sort it at `get_export_items`? Other `linking_info
          .sorted_exports()` is also sorted, you only sort the `exports_to_other_chunks` exports is ok.

Comment (hyf0) [reply crates/rolldown/src/bundler/chunk/render_chunk_exports.rs]: Cool.

**Review by underfin — APPROVED** [review]
