### PR TITLE
fix: improve JSON parsing with serde_json to emit proper diagnostic

### LINKED ISSUE #7403: [Bug]: BigInt literals are allowed in JSON files
### Reproduction link or steps

[REPL](https://repl.rolldown.rs/#eNpFTUsKwjAQvUqYlUKJqLtcxXER2lQi6YwkY0FC7m5G0e7e/1WYwVUIJPll70Uxgdv4AGOncXlwFjN58WbOvBgEe1DWI0wImJFGpsIp2MS3nVp7FXs/gJP8DG2Af+H3sgnfm6oVFIRIq09xQnDmcjyd6apG+wy2PrT2bPISikB7A0feQFg=)

### What is expected?

A parse error to happen.

### What is actually happening?

No error happens.

### System Info

```Shell
REPL 1.0.0-beta.53
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #7403

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7443** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7442** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7442?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7442?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7442).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown_common/src/ecmascript/json_to_program.rs [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+  builder: AstBuilder<'a>,
+) -> oxc::ast::ast::Expression<'a> {
+  match value {
+    Value::Null => builder.expression_null_literal(SPAN),
+
+    Value::Bool(b) => builder.expression_boolean_literal(SPAN, *b),
+
+    Value::Number(n) => {
+      // serde_json::Number can always be represented as f64 for JSON numbers
+      let f = n.as_f64().unwrap_or(f64::NAN);
```
Comment (sapphi-red) [inline crates/rolldown_common/src/ecmascript/json_to_program.rs]:
```js
JSON.parse('{ "v": 9007199254740995 }').v // 9007199254740996
```
If the value cannot be represented with f64, we need to round it to the nearest one. If it does have this behavior, I guess we can call `.expect()` as `.unwrap_or` will hide a bug.

File: crates/rolldown_common/src/ecmascript/json_to_program.rs [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+        let key_expr = builder.expression_string_literal(SPAN, builder.atom(key), None);
+        let value_expr = json_value_to_expression(val, builder);
+
+        builder.object_property_kind_object_property(
+          SPAN,
+          oxc::ast::ast::PropertyKind::Init,
+          oxc::ast::ast::PropertyKey::from(key_expr),
+          value_expr,
+          false, // shorthand
+          true,  // computed
```
[the remark this answers is not in the document]
Comment (sapphi-red) [reply crates/rolldown_common/src/ecmascript/json_to_program.rs]: I think this is correct.

**Comment by sapphi-red** [comment]
Would you also remove this line?
https://github.com/rolldown/rolldown/blob/ea2a07f9d7d096113ff95432ec76b6c35ecd1709/scripts/src/esbuild-tests/reasons.ts#L56-L57

File: crates/rolldown_common/src/ecmascript/json_to_program.rs (hunk 1 above)
Comment (IWANABETHATGUY) [reply crates/rolldown_common/src/ecmascript/json_to_program.rs]: image
since we did not enable the `arbitrary_precision` feature, I think serde_json already handle it. 
image

**Review by sapphi-red — APPROVED** [review]
