### PR TITLE
fix: don't unwatch files when close watcher

### LINKED ISSUE #4084: [Bug]: watcher.close crashes when certain modules are imported, maybe related to pnpm
### Reproduction link or steps

Minimal reproduction is at https://github.com/dumbmatter/rolldown-watch-close-bug

[The rolldown code is:](https://github.com/dumbmatter/rolldown-watch-close-bug/blob/5dd6ab1cd520c3bd1995de781838b309db00dfc9/watch.js)

```js
import { watch } from "rolldown";

console.log("Starting watch...");
const watcher = await watch({
	input: "app.js",
	output: {
		file: "build.js",
	},
});
console.log("Done!");

setTimeout(async () => {
	console.log("Stopping watch...");
	await watcher.close();
	console.log("Done!");
}, 1000);
```

[app.js is just:](https://github.com/dumbmatter/rolldown-watch-close-bug/blob/5dd6ab1cd520c3bd1995de781838b309db00dfc9/app.js)

```js
export { Modal } from "react-bootstrap";
```

### What is expected?

The above script should run without error when using pnpm.

### What is actually happening?

When dependencies are installed with pnpm, I see this error when running the first script above:

```
$ pnpm install
$ node watch.js
Starting watch...
Done!
Stopping watch...
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Rolldown internal error: Invalid argument (os error 22) about ["/home/user/rolldown-watch-close-bug/node_modules/.pnpm/@restart+hooks@0.4.16_react@19.1.0/node_modules/@restart/hooks/esm/useMergedRefs.js"]] {
  code: 'GenericFailure'
}

Node.js v22.14.0
```

But when installed with npm, it works:

```
$ npm install
$ node watch.js
Starting watch...
Done!
Stopping watch...
Done!
```

### System Info

```Shell
Ubuntu 24.04, Node 22.14, pnpm 10.7.1, and rolldown 1.0.0-beta.7
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Closed #4084

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#4105** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4105?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/4105?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by IWANABETHATGUY** [comment]
Maybe related to https://github.com/notify-rs/notify/issues/245, according to the description in #4084 notify-rs has some issue when process hard link.

**Comment by IWANABETHATGUY** [comment]
We don't need to unwatch all files manually since when you drop the watcher https://github.com/notify-rs/notify/blob/e96e0e2045b380e5ea588d56952bfbbb9ec424cd/notify/src/inotify.rs#L182, it will clear the watched files automatically

**Review by underfin — APPROVED** [review]

File: crates/rolldown/src/watch/watcher.rs [hunk 1]
```diff
@@ -153,11 +150,7 @@ impl WatcherImpl {
     self.exec_tx.send(ExecChannelMsg::Close)?;
     // stop watching files
     // TODO the notify watcher should be dropped, because the stop method is private
-    let mut inner = self.notify_watcher.lock().await;
```
Comment (underfin) [inline crates/rolldown/src/watch/watcher.rs:156]: The 151-152 commnets is outdate,could be removed.
