### PR TITLE
fix: normalize preserveModulesRoot path

### LINKED ISSUE #7733: `preserveModulesRoot` exhibits different behaviors in `rollup` and `tsdown`
### Reproduction link or steps

https://stackblitz.com/~/github.com/momei-LJM/tsdown_demo

`preserveModulesRoot` exhibits different behaviors in `rollup` and `tsdown`；

tsdown,
Image

rollup:

Image

### What is expected?

My expected behavior is consistent with Rollup: files in the main directory should be extracted and hoisted out of the main directory.

### What is actually happening?

preserveModulesRoot: Files not hoisted to parent directory

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #7733

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7737** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7737?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7737?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge-when-ready</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7737).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/utils/prepare_build_context.rs [hunk 1]
```diff
@@ -440,11 +441,7 @@ pub fn prepare_build_context(
       .unwrap_or_else(|| arcstr::literal!("_virtual")),
     preserve_modules_root: raw_options.preserve_modules_root.map(|preserve_modules_root| {
       let p = Path::new(&preserve_modules_root);
-      if p.is_absolute() {
-        preserve_modules_root
-      } else {
-        cwd.join(p).to_string_lossy().to_string()
-      }
+      cwd.join(p).normalize().to_string_lossy().to_string()
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/utils/prepare_build_context.rs:444]: Needs to normalize the path after concatenation because in Windows, the join will generate an unexpected path like:
`E:\\from\\to\\src/main`

**Review by shulaoda — APPROVED** [review]
