### PR TITLE
fix: tree shake unused dynamic entry when `inlineDynamicImports` is enabled

### LINKED ISSUE #6935: [Bug]: build with `output.inlineDynamicImports` doesn't treeshake properly and produces invalid ESM code
### Reproduction link or steps

repro: https://github.com/BlankParticle/rolldown-inlineDynamicImports-reprod

build the code with `pnpm build`, the output code in `dist/index.js` (`//#region node_modules/.pnpm/undici@7.16.0/node_modules/undici/index.js`) will have `module.exports.[module]` code in global scope without the `__CommonJS` wrapper, which is invalid ESM code and causes node to crash

ideally undici code shouldn't even be in the bundle as it was a dynamic import in a function that was treeshaken out, so it has no use even with import side effects.

Image

### What is expected?

Ideally Undici code will be entirely treeshaken out
right now, it shouldnt produce invalid ESM code

### What is actually happening?

Undici code is still in the bundle and invalid code is produced in build

### System Info

```Shell
System:
    OS: macOS 26.0.1
    CPU: (16) arm64 Apple M4 Max
    Memory: 5.43 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.3.0 - /Users/blank/.local/state/fnm_multishells/1025_1762850271844/bin/node
    npm: 11.4.2 - /Users/blank/.local/state/fnm_multishells/1025_1762850271844/bin/npm
    pnpm: 10.20.0 - /Users/blank/.local/state/fnm_multishells/1025_1762850271844/bin/pnpm
    bun: 1.3.0 - /Users/blank/.bun/bin/bun
  Browsers:
    Chrome: 142.0.7444.135
    Safari: 26.0.1
  npmPackages:
    rolldown: 1.0.0-beta.49 => 1.0.0-beta.49
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
closed #6935

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7131** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7131?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7129** <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7129?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/rolldown/rolldown/7129?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>graphite: merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/rolldown?ref=merge-queue-instructions-in-stack-comment&prId=7129).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/rolldown/src/module_loader/module_loader.rs [hunk 1]
```diff
@@ -683,18 +683,16 @@ impl<'a> ModuleLoader<'a> {
...
-        EntryPoint {
-          name: None,
-          idx,
-          kind: EntryPointKind::DynamicImport,
-          file_name: None,
-          related_stmt_infos,
-        }
-      }));
-    }
+    let dynamic_import_entry_ids = dynamic_import_entry_ids.into_iter().collect::<Vec<_>>();
```
Comment (IWANABETHATGUY) [inline crates/rolldown/src/module_loader/module_loader.rs:686]: tree shake unused dynamic import module relies on https://github.com/rolldown/rolldown/blob/07e2ecf02af620eaa674e0803b2afe125ce3510c/crates/rolldown_common/src/types/entry_point.rs?plain=1#L14-L15, so we need to preserve them until `link::include_statements` .

File: crates/rolldown/tests/rolldown/function/inline_dynamic_imports/cjs/artifacts.snap [hunk 2]
```diff
@@ -27,9 +27,9 @@ var init_esm = __esm({ "esm.js": (() => {
 
 //#endregion
 //#region main.js
-Promise.resolve().then(() => /* @__PURE__ */ __toESM(require_foo()));
+Promise.resolve().then(() => /* @__PURE__ */ Object.freeze({ __proto__: null }));
```
Comment (IWANABETHATGUY) [inline crates/rolldown/tests/rolldown/function/inline_dynamic_imports/cjs/artifacts.snap:30]: Those two module are side effect free.

**Review by shulaoda — APPROVED** [review]
